/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Fruit.ui;

import java.awt.Cursor;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.zip.Deflater;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;

/**
 *
 * @author rafi
 */
public class B extends javax.swing.JFrame {

    /**
     * Creates new form backup
     */
    Date d=new Date();
    SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
    String dt =df.format(d).toString();
    private static B backUpInstance;
    public B() {
        initComponents();
        try {
            UIManager.setLookAndFeel(new MetalLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(B.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public static B getInstance(){
        if(backUpInstance==null)
        {
            System.out.println("Fruit.ui.B.getInstance()");
            

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B().setVisible(true);
            }
        });
        }
        return backUpInstance;
    }
    public static String getBackUpPath() {

         String backUpPath = "";
         JFileChooser fc = null;
         
         if (fc == null) {
                fc = new JFileChooser();
                fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                fc.setAcceptAllFileFilterUsed(false);
                //fc.setApproveButtonText("SAVE");
        }
        int returnVal = fc.showDialog(null, "Save");
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            backUpPath = file.getAbsolutePath();
        }
        
       return backUpPath;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtbackuppath = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "BackUp", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Agency FB", 0, 12))); // NOI18N

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("BackUp to     ");
        jPanel2.add(jLabel4);
        jPanel2.add(txtbackuppath);

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jPanel2.add(jLabel1);

        jButton3.setText("RESTORE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton2.setText("BACKUP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         txtbackuppath.setText(getBackUpPath());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        String backuppath=txtbackuppath.getText();
//    String Database =txtdatabasename.getText();
//    String Password =txtpassword.getText();
//    String user=txtuser.getText();
//        String backuppath="D://BackUp/";
        if(backuppath==null || backuppath.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please select directory..");
            return;
        }
            
    String Database = config.Config.getInstancce().getProperty("db_name");//"business_db";
    String Password =config.Config.getInstancce().getProperty("bd_user");//"root";
    String user=config.Config.getInstancce().getProperty("bd_user");//"root";
    Backup b = new Backup();
    try
   {     //Backup bk=new Backup();
       setCursorWait();
       byte[] data = b.getData("localhost", "3306", user,   Password, Database).getBytes();
       File filedst = new File(backuppath+"\\"+Database.concat(dt)+".zip");
       FileOutputStream dest = new FileOutputStream(filedst);
       ZipOutputStream zip = new ZipOutputStream(new BufferedOutputStream(dest));
       zip.setMethod(ZipOutputStream.DEFLATED);
       zip.setLevel(Deflater.BEST_COMPRESSION);
       zip.putNextEntry(new ZipEntry("data.sql"));
       zip.write(data);
       zip.close();
       dest.close();
      JOptionPane.showMessageDialog(null, "Back Up Successfully."+"\n"+"For Database: "+Database+"\n        "+"On Dated: ","Database BackUp Wizard",JOptionPane.INFORMATION_MESSAGE);
      txtbackuppath.setText("");
   }catch (Exception ex){
    JOptionPane.showMessageDialog(null, "Back Up Failed."+"\n"+"For Database: "+Database+"\n "+"On     Dated: ","Database BackUp Wizard",JOptionPane.INFORMATION_MESSAGE);
    ex.printStackTrace();
  } finally {
        setCursorNormal();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     // TODO add your handling code here:
//     SwingUtilities.invokeLater(new Runnable() {
//         @Override
//
//         public void run() {
                          String backuppath="";
        JFileChooser fileChooser = new JFileChooser();
        int r=fileChooser.showOpenDialog(null);
        if(r==JFileChooser.APPROVE_OPTION)
            backuppath=fileChooser.getSelectedFile().getAbsolutePath();
        else
            return;
//    String Database =txtdatabasename.getText();
//    String Password =txtpassword.getText();
//    String user=txtuser.getText();
//        String backuppath="D://BackUp/";
    String Database = config.Config.getInstancce().getProperty("db_name");
    String Password =config.Config.getInstancce().getProperty("bd_user");
    String user=config.Config.getInstancce().getProperty("bd_user");
    
    Backup b = new Backup();
    try
   {     //Backup bk=new Backup();
        setCursorWait();
       if(backuppath.isEmpty())
           JOptionPane.showMessageDialog(null, "null Path");
       else 
       {
           if(backuppath.endsWith(".zip")|| backuppath.endsWith(".sql")){
              
//               /ExecuteRestore er = new  ExecuteRestore(backuppath);
//               er.execute();
//               startThread(backuppath);
//        
               int result = b.restoreData("localhost", "3306", user,   Password, Database, backuppath);
               if(result==0)
                JOptionPane.showMessageDialog(null, "Restore Successfully..!");
               else
                  JOptionPane.showMessageDialog(null, "Restore failed.");

       
           }
       }
   }catch (Exception ex){
    JOptionPane.showMessageDialog(null, "Restore Failed, due to \n"+ex.getMessage());
    ex.printStackTrace();
  } finally {
        setCursorNormal();
    }

//         }
//     });
     
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtbackuppath;
    // End of variables declaration//GEN-END:variables

    private void setCursorWait() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
    }
    private void setCursorNormal() {
        this.setCursor(Cursor.getDefaultCursor());
    }

    private static void startThread(final String backuppath) 
	{ 

		SwingWorker sw1 = new SwingWorker() 
		{ 
                    Backup b = new  Backup();

			@Override
			protected String doInBackground() throws Exception 
			{ 
                            String Database = config.Config.getInstancce().getProperty("db_name");
    String Password =config.Config.getInstancce().getProperty("bd_user");
    String user=config.Config.getInstancce().getProperty("bd_user");
    
				// define what thread will do here 
//				for ( int i=10; i>=0; i-- ) 
//				{ 
//					Thread.sleep(100); 
//					System.out.println("Value in thread : " + i); 
//					publish(i); 
//				} 
				
                            
                            int result = b.restoreData("localhost", "3306", user,   Password, Database, backuppath);
//               if(result==0)
//                JOptionPane.showMessageDialog(null, "Restore Successfully..!");
//               else
//                  JOptionPane.showMessageDialog(null, "Restore failed.");
                            publish();
                            String res = "Finished Execution"; 
				return res; 
			} 

			@Override
			protected void process(List chunks) 
			{ 
				// define what the event dispatch thread 
				// will do with the intermediate results received 
				// while the thread is executing 
//				int val = (int) chunks.get(chunks.size()-1); 
				                        System.out.println(".process()"+chunks);
				
			} 

			@Override
			protected void done() 
			{ 
				// this method is called when the background 
				// thread finishes execution 
				try
				{ 
					String statusMsg = (String) get(); 
                                        
					System.out.println("Inside done function"); 
//					statusLabel.setText(statusMsg); 
                                        
					if(isCancelled()){
                                            System.out.println(".done()");
                                            b.process.destroy();
                                            
                                        } else{
                                            System.out.println("gng to cancel");
                                            this.cancel(true);
                                        }
                                            
				} 
				catch (InterruptedException e) 
				{ 
					e.printStackTrace(); 
				} 
				catch (ExecutionException e) 
				{ 
					e.printStackTrace(); 
				} 
			} 
		}; 
		
		// executes the swingworker on worker thread 
		sw1.execute(); 
	}
}
