/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Fruit.ui;

import Fruit.Common.CommonMethods;
import Fruit.DAL.ReportDAL;
import Fruit.Model.RegistrationModel;
import Fruit.TableModel.BalanceSheetTableModel;
import Fruit.component.util.TableCustomiseUtil;
import Fruit.test.Test1;
import com.User.StatementModel;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import practise.WhAPIMessageSender;

/**
 *
 * @author raffiuddin
 */
public class BalanceSheet extends javax.swing.JFrame {

    /**
     * Creates new form BalanceSheet
     */
    static Logger logger = LogManager.getLogger(BalanceSheet.class);
    List<String> items = new ArrayList<>();
    List<RegistrationModel> customerModelList = new ArrayList<>();
    private int customerId;
    private String cty;
    private String toMobile;
    public BalanceSheet() {
        initComponents();
        updateDropDown();
        TableCustomiseUtil.setTableHeaderFont(jTable1);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Fruit/Resource/strawberry.png")));
    }

    
    public BalanceSheet(TableModel jTable1) {
         initComponents();
        this.jTable1.setModel(jTable1);
        
        
        updateDropDown();
    }
    public void updateDropDown(){
        items.clear();
        Map m =new HashMap();
        
        customerModelList.clear();
     if(commonMethods.getSuppliers()!=null){
            customerModelList = commonMethods.getCustomers();
         for (RegistrationModel customerModelList1 : customerModelList) {
             items.add(customerModelList1.toString());
         }
        
        }
        Test1.setupAutoComplete(jTextField1, (ArrayList<String>) items);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1CaretUpdate(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Local", "Non Local", "Mini" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton1)
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Statement");
        jButton2.setToolTipText("Statement report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Report");
        jButton3.setToolTipText("Balance sheet");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("With Date");

        jButton4.setText("Send Msg");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jCheckBox1)
                            .addComponent(jButton4))))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton2)
                        .addGap(13, 13, 13)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String tot1 = "";
                long t = 0;
              
                boolean withDate = jCheckBox1.isSelected();
                System.out.println("withDate "+withDate);
            ArrayList<StatementModel> list1 = custDAL.getCustomerBalance(jComboBox1.getSelectedItem().toString(), customerId==0? null:String.valueOf(customerId));
                for (StatementModel model : list1) {
                    t += new Fruit.Common.CommonMethods().rupeeToInt(model.getTotalBalance());
                System.out.println("date "+model.getPtotal());
                    if(withDate){
//                        model.setPtotal("");//otherwise set date as empty
                        
                    } else{
                        
                        model.setPtotal("");//otherwise set date as empty
                        System.out.println("after date "+model.getPtotal());
                    }
                }
                if(withDate)
                tot1 = new Fruit.Common.CommonMethods().rupee(Long.toString(t));
            JRBeanCollectionDataSource beanCollectionDataSource = new JRBeanCollectionDataSource(list1);
                    Map m = new HashMap();
                    m.put("tot", tot1);
                    m.put("l", this.jComboBox1.getSelectedItem().toString());

                    JasperDesign design = JRXmlLoader.load("Business_Report\\blancesheet.jrxml");
                    JasperReport jasperReport = JasperCompileManager.compileReport(design);
                    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, m, beanCollectionDataSource);
                    JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
                    jasperViewer.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed
ArrayList<StatementModel> list = new ArrayList<>();
Fruit.DAL.CustomerDAL custDAL = new Fruit.DAL.CustomerDAL();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            
            list = custDAL.getCustomerBalance(jComboBox1.getSelectedItem().toString(), customerId==0? null:String.valueOf(customerId));
            System.out.println("list "+list.size());
            Fruit.TableModel.BalanceSheetTableModel bstm = new BalanceSheetTableModel(list);
            jTable1.setModel(bstm);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
ReportDAL reportDAL = new ReportDAL();
Fruit.Common.CommonMethods commonMethods = new CommonMethods();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if(jTable1.getSelectedRowCount()>0){
                
                StatementModel sm_1 = ((BalanceSheetTableModel)this.jTable1.getModel()).getModel(jTable1.getSelectedRow());
                int customerId = sm_1.getSno();
                System.err.println("ID : "+customerId);
                List<StatementModel> slist = new ArrayList<>();
List<Integer> ptotList = new ArrayList<>();
List<Integer> paidtotList = new ArrayList<>();
        try {
            String dt1 = "", dt2 = "NOW()";
            if(customerId!=0){
//                if(date1.getDate()!=null)
//                    dt1 = commonMethods.datesaveformat(date1.getDate());
//                if(date2.getDate()!=null)
//                    dt2 = commonMethods.datesaveformat(date2.getDate());
                String pbal = reportDAL.getCustomerBallanceByDate(customerId, dt1);
                System.out.println("pbal : "+pbal);
                if(pbal != null){
                slist.add(new StatementModel(
                        0, null, null, null, "Balance", commonMethods.rupee(pbal)));
                }
                Date d = new Date();
                dt2 = commonMethods.datesaveformat(d);
             List<StatementModel>   statementModel = reportDAL.getCustomerT_Id(customerId, dt1, dt2);
                System.out.println(statementModel.size());
//                System.out.print("T_ID  ");
                    System.out.print("\tDate  ");
                    System.out.print("\tItems  ");
                    System.out.print("\tpurchase  ");
                    System.out.print("\tpaid  ");
                    System.out.println("\tbalance  ");
                for(StatementModel model:statementModel){
                    
                    System.out.println("T_ID = "+model.getSno());
                    System.out.print("\tDate = "+model.getDate());
//                    System.out.print("\t"+model.getItems());
//                    System.out.println("v \t"+model.getPtotal());
//                    System.out.print("\t"+model.getCashPaid());
//                    System.out.print("\t Bal"+model.getTotalBalance());
                    String pto = "0";
                    if(model.getPtotal()!=null)
                        pto = model.getPtotal();
                    if(Integer.parseInt(pto)!=0){
                        List<StatementModel> l = reportDAL.getCustomerTtlTrxBy_Tid(model.getSno());
                        for(int i=0;i<l.size();i++){
//                            System.out.print(""+model.getSno());
//                    System.out.print("\t"+l.get(i).getDate());
//                    System.out.print("\t"+l.get(i).getItems());
//                    System.out.print("\t"+l.get(i).getPtotal());
//                    System.out.print("\t"+l.get(i).getCashPaid());
//                    System.out.println("\t"+l.get(i).getTotalBalance());
                            StatementModel sm1 = null;
                            if(i==0){
                                
                                if(l.size()==1){
                                    sm1 = new StatementModel(
                                    0,
                                    commonMethods.dateviewformat(java.sql.Date.valueOf(l.get(i).getDate())),
                                    l.get(i).getItems(),
                                    l.get(i).getRate(),
                                    commonMethods.rupee(l.get(i).getRtotal()),
                                    commonMethods.rupee(l.get(i).getPtotal()),
                                    commonMethods.rupee(l.get(i).getCashPaid()),
                                    commonMethods.rupee(l.get(i).getTotalBalance())
                                    );
                                } else {
                                    sm1 = new StatementModel(
                                    0,
                                    commonMethods.dateviewformat(java.sql.Date.valueOf(l.get(i).getDate())),
                                    l.get(i).getItems(),
                                    l.get(i).getRate(),
                                    commonMethods.rupee(l.get(i).getRtotal()),
                                    null,
                                    null, 
                                    null
                                    );
                                }
                            } else if(i==l.size()-1){
                         sm1 = new StatementModel(
                                0,
                                null,
                                l.get(i).getItems(),
                                    l.get(i).getRate(),
                                    commonMethods.rupee(l.get(i).getRtotal()),
                                   commonMethods.rupee(l.get(i).getPtotal()),
                                commonMethods.rupee(l.get(i).getCashPaid()), 
                                commonMethods.rupee(l.get(i).getTotalBalance())
                                );
                            } else {
                         sm1 = new StatementModel(
                                0,
                                null,
                                l.get(i).getItems(),
                                    l.get(i).getRate(),
                                    commonMethods.rupee(l.get(i).getRtotal()),
                                   null,
                                null, 
                                null
                                );
                            }
                            slist.add(sm1);
                        }
                        
                        
                        
                        
                    } else if(model.getPtotal()==null && model.getCashPaid()==null){
                        
                        StatementModel sms=reportDAL.getCustomerPreBal(customerId, model.getSno());
//                        System.out.println("prev : "+sms.getTotalBalance());
                        sms.setDate(commonMethods.dateviewformat(java.sql.Date.valueOf(sms.getDate())));
                        sms.setTotalBalance(commonMethods.rupee(sms.getTotalBalance()));
                    slist.add(sms);
                    
                    } else if(model.getPtotal()==null && model.getCashPaid()!=null){
                        
                        StatementModel sms=reportDAL.getCustomerDamOrDiscount(customerId, model.getSno());
//                        System.out.println("prev : "+sms.getTotalBalance());
                        sms.setDate(commonMethods.dateviewformat(java.sql.Date.valueOf(sms.getDate())));
                        sms.setTotalBalance((sms.getTotalBalance()));
                    slist.add(sms);
                    
                    } else {
//                        System.err.println("tid : "+model.getCashPaid());
                        
                        StatementModel sm = new StatementModel(
                                0,
                                commonMethods.dateviewformat(java.sql.Date.valueOf(model.getDate())),
                                null,
                                null,
                                commonMethods.rupee(model.getCashPaid()), 
                               commonMethods.rupee(model.getTotalBalance())
                                );
                        slist.add(sm);
                        
                        
                        
                    }
                }
                for(StatementModel model: slist){
                    System.out.print(model.getDate());
                    System.out.print("\t"+model.getItems());
                    System.out.print("\t"+model.getPtotal());
                    System.out.print("\t"+model.getCashPaid());
                    System.out.println("\t"+model.getTotalBalance());
                    
                }
                if(slist.size()>0){
                  JRBeanCollectionDataSource beanCollectionDataSource = new JRBeanCollectionDataSource(slist);
                  Map m = new HashMap();
                  m.put("cname", sm_1.getItems().trim());
                  m.put("pl", this.jComboBox1.getSelectedItem().toString());
                try {
                    JasperDesign design = JRXmlLoader.load("Business_Report\\statementreport.jrxml");
                    JasperReport jasperReport = JasperCompileManager.compileReport(design);
                    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, m, beanCollectionDataSource);
                    JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
                    jasperViewer.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                } else {
                    JOptionPane.showMessageDialog(null, "No data");
                }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }

                
            
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            int[] rows = this.jTable1.getSelectedRows();
            for (int i : rows) {
                StatementModel bl = ((BalanceSheetTableModel)this.jTable1.getModel()).getModel(i);
                System.out.println("row no "+i+" data : Mobile "+bl.getCashPaid()+" getDate "+bl.getDate()+" Name "+bl.getItems()+" getPtotal "+bl.getPtotal()+" getRate "
                        + bl.getRate()+" getRtotal "+bl.getRtotal()+" getTotalBalance "+bl.getTotalBalance()+" getSno "+bl.getSno());
                StringBuffer msgData = new StringBuffer("Hi ");
                msgData.append(bl.getItems());
                msgData.append(", ");
                msgData.append("your balance amount is : ");
                msgData.append(bl.getTotalBalance());
                msgData.append(" -- ");
                msgData.append(config.Config.getInstancce().getProperty("companyName"));
                
                String toMobile = bl.getCashPaid();
                if(null!= toMobile && toMobile.trim().length()==10){
                    toMobile = "91"+toMobile;
                }
                final String custName = bl.getItems();
                
                
                WhAPIMessageSender sender = new WhAPIMessageSender(msgData.toString(), toMobile, custName, true);
                final String checkValid = sender.checkValid();
            
                System.out.println(" Valid "+checkValid);
//                if("valid".equalsIgnoreCase(checkValid)){
                    logger.info("Valid no, so going to send msg.");
                    Thread t1 = new Thread(sender);
                    t1.start();

//                } else {
//                    JOptionPane.showMessageDialog(rootPane, "Customer No is not Watsup no."+toMobile);
//                }
            }
            
        } catch (Exception e) {
            logger.error("Exception while sending Watsup message in Balance sheet ",e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1CaretUpdate
       try {
                   int cidIn = this.items.indexOf(this.jTextField1.getText().trim());
                   
       //            logger.info(" sgfg : "+cidIn);
                   if(cidIn >= 0){
                       
                       customerId = customerModelList.get(cidIn).getCsID();
                       cty = customerModelList.get(cidIn).getCity();
                       toMobile = customerModelList.get(cidIn).getMobile();
       //                logger.info("CID : "+customerId);
       //                if(customerId!=0){
       //                   cusBalance = trxDAL.getCustomerBalance(customerId);
       //                   preBal.setText(commonMethods.rupee(Integer.toString(cusBalance)));
       //                }
       //                upDateTable();
                   } else{
                       customerId=0;
                       cty = null;
                       toMobile = null;
                   }
               } catch (Exception e) {
                   e.printStackTrace();
               }
    
    }//GEN-LAST:event_jTextField1CaretUpdate

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        jTextField1CaretUpdate(null);
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalanceSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalanceSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalanceSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalanceSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalanceSheet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
