/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Fruit.ui;

import Fruit.Common.CommonMethods;
import Fruit.Common.DbConnection;
import Fruit.DAL.ExpenditureDAL;
import Fruit.DAL.ReportDAL;
import Fruit.Model.CashOnDateModel;
import Fruit.Model.ExpenditureAmountModel;
import Fruit.Model.ExpenditureModel;
import Fruit.Model.RegistrationModel;
import Fruit.TableModel.CashTableModel;
import Fruit.TableModel.ExpenditureTableModel;
import Fruit.component.util.Logger;
import Fruit.test.Test1;
import java.awt.Toolkit;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Raffiuddin
 */

public class CashOnDate extends javax.swing.JFrame {

    /**
     * Creates new form CashOnDate
     */
    Fruit.Common.CommonMethods cm = new CommonMethods();
    Fruit.DAL.ReportDAL reportDAL = new ReportDAL();
     List<String> items = new ArrayList<>();
    Fruit.test.Test1 test1;
    List<RegistrationModel> customerModelList = new ArrayList<>();
    org.apache.log4j.Logger log = Logger.getLogger(CashOnDate.class);
    
    private int customerId;
    public CashOnDate() {
        initComponents();
        updateDropDown();
        cname.requestFocus();
        this.dat2.setDate(new Date());
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Fruit/Resource/strawberry.png")));
//        jTable1.setForeground(Color.red);
        
        updateExpenditure();
    }
    
    
  public void updateExpenditure(){
//      Object obj = cm.loadExpenditure();
      expCombo.setModel(cm.update_combo_expend());
  }
  List<ExpenditureAmountModel> explist = new ArrayList<>();
  public void updateExpenditureTable(){
//      Object obj = cm.loadExpenditure();
//      expTable.setModel(expenditureDAL.getExpenditureAmount(null));
      String dt1 = "",dt2 = "";
      explist.clear();
      if(dat1.getDate()!=null)
          dt1 = cm.datesaveformat(dat1.getDate());
      if(dat2.getDate()!=null)
          dt2 = cm.datesaveformat(dat2.getDate());
      explist = expenditureDAL.getExpenditureAmount(dt1, dt2);
      ExpenditureTableModel etm = new ExpenditureTableModel(explist);
      expTable.setModel(etm);
  }
  public void updateDropDown(){
        items.clear();
        customerModelList.clear();
     if(cm.getSuppliers()!=null){
            customerModelList = cm.getCustomers();
         for (RegistrationModel customerModelList1 : customerModelList) {
             items.add(customerModelList1.toString());
         }
        
        }
        Test1.setupAutoComplete(cname, (ArrayList<String>) items);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        expCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        expAmt = new javax.swing.JTextField();
        expAddBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        expDeleteBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        expTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        dat1 = new com.toedter.calendar.JDateChooser();
        dat2 = new com.toedter.calendar.JDateChooser();
        nat = new javax.swing.JComboBox();
        cname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cash On date");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Name", "City", "Cash", "Mobile"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("Report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setAlignmentX(1.5F);
        jPanel4.setAlignmentY(1.5F);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setText("+");
        jLabel1.setToolTipText("Add Expenditure type");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel1);

        expCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(expCombo);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("-");
        jLabel2.setToolTipText("Delete Expenditure Type");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel2);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 5, 0));
        jPanel5.add(expAmt);

        expAddBtn.setText("Add");
        expAddBtn.setToolTipText("Save Expenditure Amount");
        expAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expAddBtnActionPerformed(evt);
            }
        });
        jPanel5.add(expAddBtn);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        expDeleteBtn.setText("Delete");
        expDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expDeleteBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 229;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 15, 16, 15);
        jPanel6.add(expDeleteBtn, gridBagConstraints);

        expTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Expenditure", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        expTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        expTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(expTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 274;
        gridBagConstraints.ipady = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 15, 0, 15);
        jPanel6.add(jScrollPane2, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        dat1.setDateFormatString("dd/MM/yyyy");
        dat1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dat1PropertyChange(evt);
            }
        });
        jPanel3.add(dat1);

        dat2.setDateFormatString("dd/MM/yyyy");
        dat2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dat2PropertyChange(evt);
            }
        });
        jPanel3.add(dat2);

        nat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Local", "Non Local", "Mini" }));
        jPanel3.add(nat);
        jPanel3.add(cname);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
List<CashOnDateModel> saleList = new ArrayList<>();

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            if(dat2.getDate()==null){
                if(evt!=null)
                JOptionPane.showMessageDialog(null, "Enter Date..!");
                dat2.requestFocus();
            } else {
                int cidIn = this.items.indexOf(this.cname.getText().trim());
            
//            System.out.println(" sgfg : "+cidIn);
                if(cidIn >= 0){

                    customerId = customerModelList.get(cidIn).getCsID();

                } else {
                    customerId=0;
                }
                String nativ = nat.getSelectedItem().toString().trim();
                String dt1 = "";
                if(dat1.getDate()!=null)
                 dt1 = cm.datesaveformat(dat1.getDate());
                
                String dt2 = cm.datesaveformat(dat2.getDate());
                //                if(jDateChooser2.getDate()!=null)
                //                dt2 = cm.datesaveformat(jDateChooser2.getDate());
                 saleList = reportDAL.getCollectionByDates(customerId, dt1,dt2, nativ);
//                List<BalanceModel> saleList1 = reportDAL.getLoadTaxes(saleList.get(0).getSno());

//                for (Iterator<CashOnDateModel> it = saleList.iterator(); it.hasNext();) {
//                    CashOnDateModel string = it.next();
//                    //string.getTotalBalance();
//                    
//                }

                            //System.out.println("gsdf " +saleList.size());
                CashTableModel tableModel = new CashTableModel(saleList);
//                System.out.println(tableModel.getRowCount());
                jTable1.setModel(tableModel);
                jTable1.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(35);
                updateExpenditureTable();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        try(Connection c = DbConnection.getConnection()) {
            
//            List<StatementModel> saleList = reportDAL.getCollection(customerId, cm.datesaveformat(dat2.getDate()), nat.getSelectedItem().toString().trim());;
            if(saleList.size()>0){
                String dt1 = "",dt2="";
                if(dat1.getDate()!=null)
                    dt1 = cm.datesaveformat(dat1.getDate());
                if(dat2.getDate()!=null)
                    dt2 = cm.datesaveformat(dat2.getDate());
//                List<ExpenditureAmountModel> list = expenditureDAL.getExpenditureAmount(dt1, cm.datesaveformat(dat2.getDate()));
//                ExpenditureTableModel etm = new ExpenditureTableModel(list);
//                List<StatementModel> irm = reportDAL.getTotalCollection(cm.datesaveformat(dat2.getDate()), nat.getSelectedItem().toString().trim());
               long tot_C =  Long.parseLong(saleList.get(0).getTotalCollection());
               long tot_e = 0;
               if(explist != null && !explist.isEmpty()){
                   System.out.println("tot exp : "+ explist.get(0).getExpenditureModel().getUpdated());
                   tot_e = Long.parseLong(explist.get(0).getExpenditureModel().getUpdated());
               } else {
                    log.info("explist is empty or null");
               }
               long ba = tot_C - tot_e;
               
                System.out.println("Tot c : "+saleList.get(0).getTotalCollection());
                
                System.out.println(ba);
                JRBeanCollectionDataSource beanCollectionDataSource = new JRBeanCollectionDataSource(saleList);
                  Map m = new HashMap();
                  System.out.println("dt1 : "+dt1);
                  System.out.println("dt2 : "+dt2);
                  m.put("dt", dt1);
                  m.put("dt2", dt2);
//                  m.put("l", irm.get(0).getItems());
                  m.put("l", nat.getSelectedItem().toString());
                  m.put("tot_c", cm.rupee(String.valueOf(tot_C)));
                  m.put("tot_e", cm.rupee(String.valueOf(tot_e)));
                  m.put("tot_bal", cm.rupee(String.valueOf(ba)));
                  m.put("REPORT_CONNECTION", c);
                  
                 
                try {
                    JasperDesign design = JRXmlLoader.load("Business_Report\\cashondata.jrxml");
                    JasperReport jasperReport = JasperCompileManager.compileReport(design);
                    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, m, beanCollectionDataSource);
                    JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
                    jasperViewer.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }

            } else {
                JOptionPane.showMessageDialog(null, "No data..!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed
ExpenditureDAL expenditureDAL = new ExpenditureDAL();
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        try {
          String s = JOptionPane.showInputDialog("Add Expenditure");
            System.out.println("s : "+s);
            
          if(s!=null && s.trim().isEmpty()){
              JOptionPane.showMessageDialog(expCombo, "Enter some data please.");
          } else {
              ExpenditureModel em = new ExpenditureModel(1, s.trim(), s, s);
              em.setActive(true);
              
              
              expenditureDAL.addExpenditureName(em);
          updateExpenditure();    
          }
          
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void expDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expDeleteBtnActionPerformed
        try {
            ExpenditureAmountModel amountModel = ((ExpenditureTableModel)this.expTable.getModel()).getModel(expTable.getSelectedRow());
            expenditureDAL.deleteExpenditureAmount(amountModel);
            updateExpenditureTable();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_expDeleteBtnActionPerformed

    private void expAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expAddBtnActionPerformed
        try {
            int id = getExpenditureId();
            System.out.println("EXPMdl : "+id);
            if(expAmt.getText().trim().isEmpty())
                JOptionPane.showMessageDialog(expCombo, "Enter expenditure amount..!");
            else {
                ExpenditureAmountModel amountModel = new ExpenditureAmountModel(
                    id,
                    ((ExpenditureModel)this.expCombo.getSelectedItem()),
                    expAmt.getText().trim(),
                    cm.datesaveformat(dat2.getDate()),
                    null);
                expenditureDAL.addExpenditureAmount(amountModel);
                
                expAmt.setText("");
                updateExpenditureTable();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_expAddBtnActionPerformed

    private void dat2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dat2PropertyChange
            jButton1ActionPerformed(null);
    }//GEN-LAST:event_dat2PropertyChange

    private void dat1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dat1PropertyChange
 jButton1ActionPerformed(null);
 
    }//GEN-LAST:event_dat1PropertyChange

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
            int id = getExpenditureId();
            if(id!=-1){
                
            System.out.println("EXPMdl : "+id);

            ExpenditureModel em = new ExpenditureModel();
            em.setActive(false);
            em.setExpId(id);
            int op = JOptionPane.showConfirmDialog(null, "Are you want to delete "+this.expCombo.getSelectedItem());
            System.out.println("op "+op);
            if(op==0){
            expenditureDAL.deActivateExpenditureName(em);
              
          
                updateExpenditure();
            }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashOnDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashOnDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashOnDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashOnDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashOnDate().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cname;
    private com.toedter.calendar.JDateChooser dat1;
    private com.toedter.calendar.JDateChooser dat2;
    private javax.swing.JButton expAddBtn;
    private javax.swing.JTextField expAmt;
    private javax.swing.JComboBox expCombo;
    private javax.swing.JButton expDeleteBtn;
    private javax.swing.JTable expTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox nat;
    // End of variables declaration//GEN-END:variables

    private int getExpenditureId() {
        
        if(this.expCombo.getSelectedIndex()!=0)
            return ((ExpenditureModel)this.expCombo.getSelectedItem()).getExpId();
        else
            JOptionPane.showMessageDialog(this, "Please select some thing...");
        return -1;
    }
}
