/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Fruit.ui;

import Fruit.Common.CommonMethods;
import Fruit.DAL.ReportDAL;
import Fruit.Model.RegistrationModel;
import Fruit.test.Test1;
import com.User.StatementModel;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import practise.WhAPIMessageSender;



/**
 *
 * @author Raffiuddin
 */
public class CustomerStatementForm extends javax.swing.JFrame {

    /**
     * Creates new form CustomerStatementForm
     */
    List<RegistrationModel> customerModelList = new ArrayList<>();
    RegistrationModel registrationModel;
    List<String> items = new ArrayList<>();
    Fruit.test.Test1 test1;
    Fruit.Common.CommonMethods commonMethods = new CommonMethods();
    private int customerId;
    private String cty;
    static Logger logger = LogManager.getLogger(CustomerStatementForm.class);
    private JasperPrint jasperPrint;
    private static String PDF_PATH = config.Config.getInstancce().getProperty("pdf_path");
    private String toMobile;
    public CustomerStatementForm() {
        initComponents();
        updateDropDown();
        cname.requestFocus();
        date2.setDate(new Date());
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Fruit/Resource/strawberry.png")));
    }
public void updateDropDown(){
        items.clear();
        Map m =new HashMap();
        
        customerModelList.clear();
     if(commonMethods.getSuppliers()!=null){
            customerModelList = commonMethods.getCustomers();
         for (RegistrationModel customerModelList1 : customerModelList) {
             items.add(customerModelList1.toString());
         }
        
        }
        Test1.setupAutoComplete(cname, (ArrayList<String>) items);   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        date1 = new com.toedter.calendar.JDateChooser();
        date2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        sendMessage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer statement");

        date1.setDateFormatString("dd/MM/yyyy");

        date2.setDateFormatString("dd/MM/yyyy");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("-");

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Name  ");
        jPanel2.add(jLabel2);

        cname.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                cnameCaretUpdate(evt);
            }
        });
        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnameKeyReleased(evt);
            }
        });
        jPanel2.add(cname);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/search-small.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Statement");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        sendMessage.setText("Send Message");
        sendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(168, 168, 168)
                        .addComponent(sendMessage)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(date2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(sendMessage))
                .addContainerGap(322, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
//List<StatementModel> statementModel = new ArrayList<>();
ReportDAL reportDAL = new ReportDAL();

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        List<StatementModel> slist = new ArrayList<>();

        try {
            long startTime=System.currentTimeMillis();
            String dt1 = "", dt2 = "";
            if(customerId!=0){
                if(date1.getDate()!=null)
                    dt1 = commonMethods.datesaveformat(date1.getDate());
                if(date2.getDate()!=null)
                    dt2 = commonMethods.datesaveformat(date2.getDate());
                String pbal = reportDAL.getCustomerBallanceByDate(customerId, dt1);
                logger.info("pbal : "+pbal);
                int totslB = 0;
                if(pbal != null){
                slist.add(new StatementModel(
                        0, null, null, null, "Balance", commonMethods.rupee(pbal)));
                totslB += commonMethods.rupeeToInt(pbal);
                } 
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
             List<StatementModel>   statementModel = reportDAL.getCustomerT_Id(customerId, dt1, dt2);
//                logger.info(statementModel.size());
//                logger.info("T_ID  ");
                    logger.info("\tDate  ");
                    logger.info("\tItems  ");
                    logger.info("\tpurchase  ");
                    logger.info("\tpaid  ");
                    logger.info("\tbalance  ");
                    System.out.println("Total tradnsactions T_ID "+statementModel.size());
                provideSatamentbyTid(statementModel, totslB, slist, customerId);
                
//                for(StatementModel model: slist){
//                    logger.info(model.getDate());
//                    logger.info("\t"+model.getItems());
//                    logger.info("\t"+model.getPtotal());
//                    logger.info("\t"+model.getCashPaid());
//                    logger.info("\t"+model.getTotalBalance());
//                    
//                }
                logger.info(System.currentTimeMillis()- startTime);
                if(slist.size()>0){
                  JRBeanCollectionDataSource beanCollectionDataSource = new JRBeanCollectionDataSource(slist);
                  Map m = new HashMap();
                  m.put("cname", this.cname.getText().trim());
                  m.put("pl", this.cty);
                try {
                    JasperDesign design = JRXmlLoader.load("Business_Report\\statementreport.jrxml");
                    JasperReport jasperReport = JasperCompileManager.compileReport(design);
                    jasperPrint = JasperFillManager.fillReport(jasperReport, m, beanCollectionDataSource);
                    JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
                    jasperViewer.setVisible(true);
                    
                    
                    
                } catch (Exception e) {
                    e.printStackTrace();
                }
                } else {
                    JOptionPane.showMessageDialog(null, "No data");
                }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyReleased
        keySearch();
 
    }//GEN-LAST:event_cnameKeyReleased

    private void cnameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_cnameCaretUpdate
cnameKeyReleased(null);
    }//GEN-LAST:event_cnameCaretUpdate

    private void sendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageActionPerformed
        sendMsgfromJasper(jasperPrint, this.cname.getText().trim(), toMobile, false);
    }//GEN-LAST:event_sendMessageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerStatementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerStatementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerStatementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerStatementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerStatementForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cname;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton sendMessage;
    // End of variables declaration//GEN-END:variables

    public static void createPath() {
        String directoryName = PDF_PATH;
        File directory = new File(directoryName);
        if (! directory.exists()){
            directory.mkdir();
            logger.info(directoryName+ " path created");
            // If you require it to make the entire directory path including parents,
            // use directory.mkdirs(); here instead.
        }
    }

    public void keySearch() {
        try {
                   int cidIn = this.items.indexOf(this.cname.getText().trim());
                   
       //            logger.info(" sgfg : "+cidIn);
                   if(cidIn >= 0){
                       
                       customerId = customerModelList.get(cidIn).getCsID();
                       cty = customerModelList.get(cidIn).getCity();
                       toMobile = customerModelList.get(cidIn).getMobile();
       //                logger.info("CID : "+customerId);
       //                if(customerId!=0){
       //                   cusBalance = trxDAL.getCustomerBalance(customerId);
       //                   preBal.setText(commonMethods.rupee(Integer.toString(cusBalance)));
       //                }
       //                upDateTable();
                   } 
               } catch (Exception e) {
                   e.printStackTrace();
               }
    }

    public void provideSatamentbyTid(List<StatementModel> statementModel, int totslB, List<StatementModel> slist,int customerId) throws NumberFormatException {
        //loop is for total trx.
    for(StatementModel model:statementModel){
        
        logger.info("T_ID = "+model.getSno());
        logger.info("\tDate = "+model.getDate());
        logger.info("\t"+model.getItems());
        logger.info("v \t"+model.getPtotal());
        logger.info("\t"+model.getCashPaid());
        logger.info("\t Bal"+model.getTotalBalance());
        String pto = "0";
        if(model.getPtotal()!=null)
            pto = model.getPtotal();
        if(Integer.parseInt(pto)!=0){
            
            //totslB += Integer.parseInt(pto);
            
            List<StatementModel> l = reportDAL.getCustomerTtlTrxBy_Tid(model.getSno());
             int ftotal = 0;//logger.info("id   "+model.getSno()+ " SIZE "+l.size());
            for(int i=0;i<l.size();i++){
                
//                    logger.info("\t"+l.get(i).getDate());
//                    logger.info("\t"+l.get(i).getItems());
//                    logger.info("\t"+l.get(i).getPtotal());
//                    logger.info("\t"+l.get(i).getCashPaid());
//                    logger.info("\t" +l.get(i).getTotalBalance());
//                    logger.info("");
                StatementModel sm1 = null;
                if(i==0){
                    
                    if(l.size()==1){
                        sm1 = new StatementModel(
                        0,
                        commonMethods.dateviewformat(java.sql.Date.valueOf(l.get(i).getDate())),
                        l.get(i).getItems(),
                        l.get(i).getRate(),
                        commonMethods.rupee(l.get(i).getRtotal()),
                        commonMethods.rupee(l.get(i).getPtotal()),
                        commonMethods.rupee(l.get(i).getCashPaid()),
                        commonMethods.rupee(String.valueOf(totslB += (commonMethods.rupeeToInt(commonMethods.rupee(l.get(i).getPtotal())) - 
                                commonMethods.rupeeToInt(commonMethods.rupee(l.get(i).getCashPaid())))))
                        );
                    } else {
                        sm1 = new StatementModel(
                        0,
                        commonMethods.dateviewformat(java.sql.Date.valueOf(l.get(i).getDate())),
                        l.get(i).getItems(),
                        l.get(i).getRate(),
                        commonMethods.rupee(l.get(i).getRtotal()),
                        null,
                        null, 
                        null
                        );
                        ftotal = ftotal + commonMethods.rupeeToInt(commonMethods.rupee(l.get(i).getPtotal()));
                    }//logger.info("<<<<&&***** "+commonMethods.rupee(l.get(i).getPtotal()));
                } else if(i==l.size()-1){
             sm1 = new StatementModel(
                    0,
                    null,
                    l.get(i).getItems(),
                        l.get(i).getRate(),
                        commonMethods.rupee(l.get(i).getRtotal()),
                       commonMethods.rupee(l.get(i).getPtotal()),
                    commonMethods.rupee(l.get(i).getCashPaid()), 
                    commonMethods.rupee(String.valueOf(totslB += (commonMethods.rupeeToInt(commonMethods.rupee(l.get(i).getPtotal())) - 
                                commonMethods.rupeeToInt(commonMethods.rupee(l.get(i).getCashPaid())))))
                    );ftotal = ftotal + commonMethods.rupeeToInt(commonMethods.rupee(l.get(i).getPtotal()));
                    //logger.info("<<<<&&***** "+commonMethods.rupee(l.get(i).getCashPaid()));
                } else {
             sm1 = new StatementModel(
                    0,
                    null,
                    l.get(i).getItems(),
                        l.get(i).getRate(),
                        commonMethods.rupee(l.get(i).getRtotal()),
                       null,
                    null, 
                    null
                    );ftotal = ftotal + commonMethods.rupeeToInt(commonMethods.rupee(l.get(i).getPtotal()));
                }
                slist.add(sm1);
            }
            
            //logger.info(model.getSno()+"<<<<&&***** ftotal "+ftotal );
            
            
            
        } else if(model.getPtotal()==null && model.getCashPaid()==null){
            
            StatementModel sms=reportDAL.getCustomerPreBal(customerId, model.getSno());
//                        logger.info("prev : "+sms.getTotalBalance());
            sms.setDate(commonMethods.dateviewformat(java.sql.Date.valueOf(sms.getDate())));
            sms.setTotalBalance(commonMethods.rupee(String.valueOf(totslB += commonMethods.rupeeToInt(sms.getTotalBalance()))));
        slist.add(sms);
        
        } else if(model.getPtotal()==null && model.getCashPaid()!=null){
            System.out.println("customerId "+customerId+" model.getSno() "+model.getSno());
            StatementModel sms=reportDAL.getCustomerDamOrDiscount1(customerId, model.getSno());
//                        logger.info("prev : "+sms.getTotalBalance());
            System.out.println("sms "+sms);
            if(sms.getDate() != null)
            sms.setDate(commonMethods.dateviewformat(java.sql.Date.valueOf(sms.getDate())));
            sms.setTotalBalance((commonMethods.rupee(String.valueOf(totslB -= commonMethods.rupeeToInt(commonMethods.rupee(sms.getCashPaid()))))));
        slist.add(sms);
        
        } else {
            System.err.println("tid : "+model.getCashPaid());
            
            StatementModel sm = new StatementModel(
                    0,
                    commonMethods.dateviewformat(java.sql.Date.valueOf(model.getDate())),
                    null,
                    null,
                    commonMethods.rupee(model.getCashPaid()), 
                    commonMethods.rupee(String.valueOf(totslB -= commonMethods.rupeeToInt(commonMethods.rupee(model.getCashPaid()))))
                    );
            slist.add(sm);
            
            
            
        }
    }
    }

    public void sendMsgfromJasper(JasperPrint jasperPrint1, String custName, String toMobileNo, boolean isValid) {
        try {
            createPath();
            String filePath = PDF_PATH + custName +".pdf";
            
            JasperExportManager.exportReportToPdfFile(jasperPrint1, filePath);
            
            logger.info("filePaht "+filePath);
            
            String fileName = custName+".pdf";
            if(toMobileNo.trim().length()==10)
                toMobileNo = "91".concat(toMobileNo);
            logger.info("fileName "+fileName+ " send to Mobile "+ toMobileNo);
            
            WhAPIMessageSender sender = new WhAPIMessageSender(filePath, toMobileNo, custName, false);
            String checkValid = "valid";
//            if(!isValid)
//                checkValid = sender.checkValid();
            
            System.out.println(" Valid "+checkValid);
//            if("valid".equalsIgnoreCase(checkValid)){
                logger.info("Valid no, so going to send msg.");
                Thread t1 = new Thread(sender);
                t1.start();
            
//            } else {
//                JOptionPane.showMessageDialog(rootPane, "Customer No is not Watsup no."+toMobileNo);
//            }
            
            
            
            
        } catch (Exception e) {
            logger.error("Exception While sending message ",e);
            e.printStackTrace();
        }
    }


}
