/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Fruit.ui;

import Fruit.Common.CommonMethods;
import Fruit.DAL.CustomerDAL;
import Fruit.Model.RegistrationModel;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author raffiuddin
 */
public class CustomerRegistration extends javax.swing.JFrame {

    /**
     * Creates new form CustomerRegistration
     */
    static CustomerRegistration registration = null;
    Fruit.Common.CommonMethods commonMethods = new CommonMethods();
    CustomerDAL registrationDAL = new CustomerDAL();
    public CustomerRegistration() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Fruit/Resource/strawberry.png")));
    }

    public static CustomerRegistration getInstance(){
        if(registration == null)
            registration = new CustomerRegistration();
        
        return registration;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mob = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mob2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Registration");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 102, 102)), "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        jPanel3.setLayout(new java.awt.GridLayout(9, 4, 5, 10));

        jLabel2.setText("Name *");
        jPanel3.add(jLabel2);

        name.setForeground(new java.awt.Color(0, 0, 255));
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });
        jPanel3.add(name);

        jLabel3.setText("Mobile *");
        jPanel3.add(jLabel3);

        mob.setForeground(new java.awt.Color(0, 0, 255));
        mob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobKeyTyped(evt);
            }
        });
        jPanel3.add(mob);

        jLabel4.setText("Mobile 2/Land line");
        jPanel3.add(jLabel4);

        mob2.setForeground(new java.awt.Color(0, 0, 255));
        mob2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mob2KeyTyped(evt);
            }
        });
        jPanel3.add(mob2);

        jLabel5.setText("Door/Plot  No.");
        jPanel3.add(jLabel5);

        dno.setForeground(new java.awt.Color(0, 0, 255));
        jPanel3.add(dno);

        jLabel6.setText("City/Town");
        jPanel3.add(jLabel6);

        city.setForeground(new java.awt.Color(0, 0, 255));
        city.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cityKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cityKeyTyped(evt);
            }
        });
        jPanel3.add(city);

        jLabel7.setText("Pin");
        jPanel3.add(jLabel7);

        pin.setForeground(new java.awt.Color(0, 0, 255));
        pin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pinKeyTyped(evt);
            }
        });
        jPanel3.add(pin);

        jLabel8.setText("State");
        jPanel3.add(jLabel8);

        state.setForeground(new java.awt.Color(0, 0, 255));
        state.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stateKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stateKeyTyped(evt);
            }
        });
        jPanel3.add(state);

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("* is mandatory");
        jPanel3.add(jLabel10);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Local", "Non Local", "Mini" }));
        jPanel3.add(jComboBox1);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel3.add(cancelButton);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Registration Form");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addGap(210, 210, 210))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            
            String cName = name.getText().trim();
            String mobile = mob.getText().trim();
            String mobile2 = mob2.getText().trim();
            String plotno = dno.getText().trim();
            String cite = city.getText().trim();
            String pinNo = pin.getText().trim();
            String nativ = jComboBox1.getSelectedItem().toString().trim();
            int pinCode = 0;
            if(!pinNo.isEmpty()){
                pinCode =  Integer.parseInt(pinNo);
            }
            String stat = state.getText().trim();
//            String regDate = commonMethods.datesaveformat(customerRegDate.getDate()).trim();
            if(cName.isEmpty()){
                JOptionPane.showMessageDialog(null, "Enter customer name..!");name.requestFocus();
            } else if(mobile.isEmpty()){
                JOptionPane.showMessageDialog(null, "Enter mobile number..!");mob.requestFocus();
            } else if(mobile.length()!=10){
                JOptionPane.showMessageDialog(null, "Enter 10 digits mobile number..!");mob.requestFocus();
            } else if(jComboBox1.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(null, "Select native..!");jComboBox1.requestFocus();
            } else {
           
            byte[] photo = null;
            RegistrationModel model = new RegistrationModel(
                    1, cName, mobile, mobile2, null, cite, pinCode, stat, plotno, true,nativ);
                //            System.out.println("ds : "+model.getCity());
                int val = registrationDAL.getCustomerByName(model);
                if(val==0){
            registrationDAL.addCustomer(model);
            cancelButtonActionPerformed(evt);
            Entry e = EntryForm.getSaleEntryForm().entry1;
            e.updateDropDown();
                } else if(val==1){
                    JOptionPane.showMessageDialog(null, "Customer already registered..!");
                    name.requestFocus();
                }
            }
            
                    
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
 char c = evt.getKeyChar();
        if (!(Character.isLetter(c) || (c == evt.VK_BACK_SPACE) || 
                (c == evt.VK_SPACE) || (c == evt.VK_PERIOD) || c == evt.VK_DELETE)) {
//            JOptionPane.showMessageDialog(null, "enter Alphabets only");
            evt.consume();
        }
    }//GEN-LAST:event_nameKeyTyped

    private void cityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityKeyTyped
        nameKeyTyped(evt);
    }//GEN-LAST:event_cityKeyTyped

    private void stateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stateKeyTyped
        nameKeyTyped(evt);
    }//GEN-LAST:event_stateKeyTyped

    private void mobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobKeyTyped
 char c = evt.getKeyChar();
//        System.out.println("len : "+(mob.getText().trim().length()>=10));
        if (!(Character.isDigit(c) || (c == evt.VK_BACK_SPACE) || c == evt.VK_DELETE )) {
//            JOptionPane.showMessageDialog(null, "enter Alphabets only");
            evt.consume();
        }
        if(mob.getText().trim().length()>=10)
            evt.consume();
    }//GEN-LAST:event_mobKeyTyped

    private void mob2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mob2KeyTyped
        mobKeyTyped(evt);
    }//GEN-LAST:event_mob2KeyTyped

    private void pinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinKeyTyped
        mobKeyTyped(evt);
    }//GEN-LAST:event_pinKeyTyped

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        
        name.setText("");
        mob.setText("");
        mob2.setText("");
        city.setText("");
        pin.setText("");
        state.setText("");
        dno.setText("");
        
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        try {
            if(name.getText().isEmpty()){
                
            }else{
            name.setText(commonMethods.firstLeterToCap(name.getText()));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_nameKeyReleased

    private void cityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityKeyReleased
try {
            if(city.getText().isEmpty()){
                
            }else{
            city.setText(commonMethods.firstLeterToCap(city.getText().trim()));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cityKeyReleased

    private void stateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stateKeyReleased
        try {
            if(state.getText().isEmpty()){
                
            }else{
            state.setText(commonMethods.firstLeterToCap(state.getText().trim()));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_stateKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                CustomerRegistration.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField city;
    private javax.swing.JTextField dno;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField mob;
    private javax.swing.JTextField mob2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pin;
    private javax.swing.JTextField state;
    // End of variables declaration//GEN-END:variables
}
