/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Fruit.ui;

import Fruit.Common.CommonMethods;
import Fruit.DAL.InvoiceDAL;
import Fruit.DAL.ProductDAL;
import Fruit.Model.ProductCategoryModel;
import Fruit.Model.ProductEntryModel;
import Fruit.Model.RegistrationModel;
import Fruit.Model.SaleCatelogModel;
import Fruit.Model.SaleTransactionModel;
import Fruit.TableModel.SaleCatelogTableModel;
import Fruit.test.Test1;
import com.User.SaleBean;
import java.awt.Toolkit;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author raffiuddin
 */
public class DoupReport extends javax.swing.JFrame {

    /**
     * Creates new form DoupReport
     */
    Connection con;
    private Object[] columnNames = {"Items","Category","Quantity","UnitCost","Total"};
    ProductDAL productDAL;
    static Fruit.Common.CommonMethods commonMethods = new CommonMethods();
    Fruit.Model.ProductCategoryModel categoryModel;
    Fruit.Model.SaleEntryTrxModel trxModel ;
    SaleCatelogModel saleCatelogModel;
    List<SaleCatelogModel> catelogModelList = new ArrayList<>();
    static List<RegistrationModel> customerModelList = new ArrayList<>();
    RegistrationModel registrationModel;
    public  List<String> items = new ArrayList<>();
    Fruit.test.Test1 test1;
    Fruit.DAL.InvoiceDAL trxDAL = new InvoiceDAL();
    private int tbindex;
    public DoupReport() {
        initComponents();
        entryDate.setDate(new Date());
        updateProductList();
        updateProductCategoryList();
//        table_sale.getTableHeader().setBackground(Color.BLACK);
//        table_sale.getTableHeader().setForeground(Color.white);
        updateDropDown();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Fruit/Resource/strawberry.png")));
    }
    public void updateDropDown(){
        items.clear();
     if(commonMethods.getSuppliers()!=null){
            customerModelList = commonMethods.getSuppliers();
         for (RegistrationModel customerModelList1 : customerModelList) {
             items.add(customerModelList1.toString());
         }
        
        }
        Test1.setupAutoComplete(cname, (ArrayList<String>) items);   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        entryDate = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemList = new javax.swing.JList();
        jPanel14 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        qntytxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        unitcosttxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        unittottxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_sale = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        edit_table_sale_button = new javax.swing.JButton();
        delete_table_sale_button = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        cname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        trkNo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        transName = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        expper = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        exp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lryHire = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cooli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cash = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ktcash = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        amc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tot = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        gsale = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lessEFR = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        netSale = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        advPay = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        paid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Farmer Report");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        entryDate.setForeground(new java.awt.Color(0, 102, 102));
        entryDate.setDateFormatString("dd/MM/yyyy");
        entryDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jPanel3.setLayout(new java.awt.BorderLayout(0, 5));

        itemList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemList.setForeground(new java.awt.Color(0, 204, 0));
        itemList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Apple", "Orange" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        itemList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        itemList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                itemListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(itemList);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setForeground(new java.awt.Color(159, 128, 35));
        jLabel1.setText("Items                                   ");
        jPanel14.add(jLabel1);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/smalladdsym.png"))); // NOI18N
        jLabel10.setToolTipText("Add Product");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel14.add(jLabel10);

        jPanel3.add(jPanel14, java.awt.BorderLayout.PAGE_START);

        jPanel4.add(jPanel3);

        jPanel5.setLayout(new java.awt.GridLayout(1, 4, 5, 0));

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.X_AXIS));

        qntytxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        qntytxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qntytxtKeyReleased(evt);
            }
        });
        jPanel12.add(qntytxt);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" X");
        jPanel12.add(jLabel3);

        jPanel5.add(jPanel12);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        unitcosttxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        unitcosttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unitcosttxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                unitcosttxtKeyTyped(evt);
            }
        });
        jPanel13.add(unitcosttxt);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" =");
        jPanel13.add(jLabel4);

        jPanel5.add(jPanel13);

        unittottxt.setEditable(false);
        unittottxt.setForeground(new java.awt.Color(0, 37, 194));
        unittottxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(unittottxt);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/Actions-list-add-icon.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "Items List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(204, 0, 51)));
        jPanel7.setLayout(new java.awt.BorderLayout(0, 3));

        table_sale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Items", "Category", "Quantity", "UnitCost", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_sale.setToolTipText("Sale Items");
        table_sale.setGridColor(new java.awt.Color(204, 204, 204));
        table_sale.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_saleMouseClicked(evt);
            }
        });
        table_sale.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                table_saleMouseDragged(evt);
            }
        });
        table_sale.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                table_salePropertyChange(evt);
            }
        });
        table_sale.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                table_saleVetoableChange(evt);
            }
        });
        jScrollPane3.setViewportView(table_sale);

        jPanel7.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        edit_table_sale_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db-edit-icon.png"))); // NOI18N
        edit_table_sale_button.setText("Edit");
        edit_table_sale_button.setEnabled(false);
        edit_table_sale_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_table_sale_buttonActionPerformed(evt);
            }
        });
        jPanel8.add(edit_table_sale_button);

        delete_table_sale_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db-remove-icon.png"))); // NOI18N
        delete_table_sale_button.setText("Remove");
        delete_table_sale_button.setEnabled(false);
        delete_table_sale_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_table_sale_buttonActionPerformed(evt);
            }
        });
        jPanel8.add(delete_table_sale_button);

        jPanel7.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        cname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cname.setForeground(new java.awt.Color(235, 46, 46));
        cname.setText("Enter Supplier name");
        cname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnameFocusLost(evt);
            }
        });
        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnameKeyReleased(evt);
            }
        });
        jPanel11.add(cname);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/smalladdsym.png"))); // NOI18N
        jLabel8.setToolTipText("Add supplier");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel8);

        jLabel11.setText("Truck No  *");

        jLabel12.setText("Transport");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(trkNo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(transName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(entryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(trkNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(transName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(entryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new java.awt.GridLayout(4, 4, 5, 8));

        jLabel2.setText("  Expen.(%)");
        jPanel6.add(jLabel2);

        expper.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                expperKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expperKeyTyped(evt);
            }
        });
        jPanel6.add(expper);

        jLabel20.setText("  Expenditure");
        jPanel6.add(jLabel20);

        exp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                expKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expKeyTyped(evt);
            }
        });
        jPanel6.add(exp);

        jLabel5.setText("  Lory Hire");
        jPanel6.add(jLabel5);

        lryHire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lryHireKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lryHireKeyTyped(evt);
            }
        });
        jPanel6.add(lryHire);

        jLabel6.setText("  Cooli");
        jPanel6.add(jLabel6);

        cooli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cooliKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cooliKeyTyped(evt);
            }
        });
        jPanel6.add(cooli);

        jLabel7.setText("  Cash");
        jPanel6.add(jLabel7);

        cash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cashKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cashKeyTyped(evt);
            }
        });
        jPanel6.add(cash);

        jLabel9.setText("  Kata Cash");
        jPanel6.add(jLabel9);

        ktcash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ktcashKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ktcashKeyTyped(evt);
            }
        });
        jPanel6.add(ktcash);

        jLabel13.setText("  AMC");
        jPanel6.add(jLabel13);

        amc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amcKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amcKeyTyped(evt);
            }
        });
        jPanel6.add(amc);

        jLabel14.setText("  Total");
        jPanel6.add(jLabel14);

        tot.setEditable(false);
        jPanel6.add(tot);

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new java.awt.GridLayout(3, 4, 5, 15));

        jLabel15.setText("  Gross Sale");
        jPanel9.add(jLabel15);
        jPanel9.add(gsale);

        jLabel16.setText("Less EFR");
        jPanel9.add(jLabel16);
        jPanel9.add(lessEFR);

        jLabel17.setText("  Net Sale");
        jPanel9.add(jLabel17);
        jPanel9.add(netSale);

        jLabel18.setText("Advance Payment");
        jPanel9.add(jLabel18);

        advPay.setEditable(false);
        jPanel9.add(advPay);

        jLabel19.setText("  Paid");
        jPanel9.add(jLabel19);

        paid.setEditable(false);
        jPanel9.add(paid);

        jButton2.setText("Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2);

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_itemListValueChanged
        try {
            if(evt.getValueIsAdjusting()){
                ProductEntryModel entryModel = ((ProductEntryModel)this.itemList.getSelectedValue());
                System.out.println("hi1 "+entryModel.getpId());
                updateProductCategoryLisByProduct(entryModel.getpId());
                //            List<ProductCategoryModel> categoryModel = ((ProductCategoryModel)this.categoryModel);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_itemListValueChanged

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

        try {
            ProductCreate.getInstance().setVisible(true);
        } catch (Exception e) {
            System.err.println("Exception in jLabel10MouseClicked ");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void qntytxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qntytxtKeyReleased

        try {
            unitcosttxtKeyReleased(evt);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_qntytxtKeyReleased

    private void unitcosttxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitcosttxtKeyReleased

        try {
            String s = qntytxt.getText().trim().replaceAll(",", "");
            String str;
            if(s.equalsIgnoreCase("")){
                qntytxt.setText("");
            } else {
                String s2 = unitcosttxt.getText().trim().replaceAll(",", "");
                if(s2.isEmpty()){

                }else{

                    //                    if(md.mul(Integer.parseInt(s), Integer.parseInt(s2))>=1000)
                    //                    {
                        str = commonMethods.rupee(Integer.toString(commonMethods.mul(Integer.parseInt(s), Integer.parseInt(s2)))).trim();
                        //                    }
                    //                    else{
                        //                        str = Integer.toString(md.mul(Integer.parseInt(s), Integer.parseInt(s2)));
                        //                    }
                    //                    qntytxt.setText(md.rupee(s));
                    unitcosttxt.setText(commonMethods.rupee(s2));
                    unittottxt.setText(str);
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_unitcosttxtKeyReleased

    private void unitcosttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitcosttxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_unitcosttxtKeyTyped
int qunty = 0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if(itemList.isSelectionEmpty()){
                JOptionPane.showMessageDialog(null, "Please select something in Items List", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);
                itemList.requestFocus();
                //            } else if(categoryList.isSelectionEmpty()){
                //                JOptionPane.showMessageDialog(null, "Please select Quantity type", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);
                //                categoryList.requestFocus();
            } else if(qntytxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please give Quantity", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);
                qntytxt.requestFocus();

                //            } else if(unitcosttxt.getText().trim().isEmpty()){
                //                JOptionPane.showMessageDialog(null, "Please give unitcost", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);
                //                unitcosttxt.requestFocus();
                //
                //            } else if(unittottxt.getText().trim().isEmpty()){
                //                JOptionPane.showMessageDialog(null, "Please give unitcost", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);
                //                unittottxt.requestFocus();
            } else {
                String item = itemList.getSelectedValue().toString().trim();
                //                String itemtype = categoryList.getSelectedValue().toString().trim();
                String qnty = qntytxt.getText().trim().replaceAll(",", "");
                qunty += commonMethods.rupeeToInt(qnty);
                String unitcost = unitcosttxt.getText().trim().replaceAll(",", "");
                String utot = unittottxt.getText().trim().replaceAll(",", "");
                String dt="";
                if(entryDate.getDate() != null)
                dt = commonMethods.datesaveformat(entryDate.getDate());
                int pId = ((ProductEntryModel)this.itemList.getSelectedValue()).getpId();
                //                int catId = ((ProductCategoryModel)this.categoryList.getSelectedValue()).getCatId();
                ProductEntryModel productEntryModel = new ProductEntryModel(
                    item, "", true, dt, pId);
                ProductCategoryModel productCategoryModel = new ProductCategoryModel(
                    "", "", true, dt, 1, 1, productEntryModel);
                SaleTransactionModel transactionModel = new SaleTransactionModel(
                    commonMethods.rupeeToInt(qnty), commonMethods.rupeeToInt(unitcost), commonMethods.rupeeToInt(utot), pId, 1, 1);
                SaleCatelogModel saleCatelogModel = new SaleCatelogModel(productCategoryModel, transactionModel,1);
                //                System.out.println("pid : "+catId);
                //                DefaultTableModel dml = (DefaultTableModel) table_sale.getModel();
                catelogModelList.add(saleCatelogModel);
                SaleCatelogTableModel catelogTableModel = new SaleCatelogTableModel(catelogModelList);
                table_sale.setModel(catelogTableModel);
                //                String cnt = Integer.toString(dml.getRowCount()+1);
                //                Object[] cols = {"Items ("+cnt+")","QuantityType","Quantity","UnitCost","Total"};
                //                Object[] rowData = {item,itemtype,qnty,unitcost,utot};
                //                dml.setColumnIdentifiers(cols);
                //                if(tbindex!=-1){
                    //                    dml.insertRow(tbindex, rowData);
                    //                    tbindex = -1;
                    //                }else{
                    //                dml.addRow(rowData);
                    //                }

                table_saleVetoableChange(null);
                qntytxt.setText("");
                unitcosttxt.setText("");
                unittottxt.setText("");
                itemList.clearSelection();
                //                categoryList.clearSelection();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void table_saleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_saleMouseClicked

        table_saleMouseDragged(evt);
    }//GEN-LAST:event_table_saleMouseClicked

    private void table_saleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_saleMouseDragged
        try {
            int r = table_sale.getSelectedRowCount();
            if(r>0){
                edit_table_sale_button.setEnabled(true);delete_table_sale_button.setEnabled(true);
            } else {
                edit_table_sale_button.setEnabled(false);delete_table_sale_button.setEnabled(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_table_saleMouseDragged

    private void table_salePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_table_salePropertyChange
        //        try {
            //            if(table_sale.getRowCount()>0){
                //                long tot = 0;
                //                for(int i = 0 ; i < table_sale.getRowCount() ; i++){
                    //                    tot += Long.parseLong(table_sale.getModel().getValueAt(i, 4).toString().replaceAll(",", ""));
                    //                }
                //                ftotal.setText(new Fruit.Common.CommonMethods().rupee(String.valueOf(tot)));
                //            }
            //            if(table_sale.getSelectedRows().length>0){
                //                edit_table_sale_button.setEnabled(true);
                //                delete_table_sale_button.setEnabled(true);
                //            } else{
                //                edit_table_sale_button.setEnabled(false);
                //                delete_table_sale_button.setEnabled(false);
                //            }
            //        } catch (Exception e) {
            //            e.printStackTrace();
            //        }
        try {
            table_saleVetoableChange(evt);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_table_salePropertyChange

    private void table_saleVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_table_saleVetoableChange
        try {
            if(table_sale.getRowCount()>0){
                //                System.err.println("sdgdfgdfg");
                long tot = 0;
                for(int i = 0 ; i < table_sale.getRowCount() ; i++){
                    tot += Long.parseLong(table_sale.getModel().getValueAt(i, 4).toString().replaceAll(",", ""));
                }

                gsale.setText(new Fruit.Common.CommonMethods().rupee(String.valueOf(tot)));
                String p = paid.getText().trim();long pa=0,ba=0;
                if(!p.equalsIgnoreCase("")){
                    pa = Long.parseLong(p);
                    ba = tot - pa;
                } else {
                    ba = tot;

                }
                paid.setText(new Fruit.Common.CommonMethods().rupee(String.valueOf(pa)));
//                balance.setText(new Fruit.Common.CommonMethods().rupee(String.valueOf(ba)));
            }
            if(table_sale.getSelectedRows().length>0){
                edit_table_sale_button.setEnabled(true);
                delete_table_sale_button.setEnabled(true);
            } else{
                edit_table_sale_button.setEnabled(false);
                delete_table_sale_button.setEnabled(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_table_saleVetoableChange

    private void edit_table_sale_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_table_sale_buttonActionPerformed
        try {
            if(table_sale.getSelectedRowCount()>0){
                tbindex = table_sale.getSelectedRow();
                saleCatelogModel = catelogModelList.get(tbindex);

                itemList.setSelectedValue(saleCatelogModel.getCategoryModel().getProductEntryModel().getProductName().trim(), true);
                //                categoryList.setSelectedValue(saleCatelogModel.getCategoryModel().getCategoryName().trim(), true);
                qntytxt.setText(Integer.toString(saleCatelogModel.getTransactionModel().getQnty()));
                unitcosttxt.setText(Integer.toString(saleCatelogModel.getTransactionModel().getUcost()));
                unittottxt.setText(Integer.toString(saleCatelogModel.getTransactionModel().getUtot()));
                catelogModelList.remove(tbindex);
                SaleCatelogTableModel tableModel = new SaleCatelogTableModel(catelogModelList);
                table_sale.setModel(tableModel);
                table_saleVetoableChange(null);
                //                DefaultTableModel dml = (DefaultTableModel) table_sale.getModel();
                //                dml.removeRow(tbindex);
                //                 String cnt = Integer.toString(dml.getRowCount());

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_edit_table_sale_buttonActionPerformed

    private void delete_table_sale_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_table_sale_buttonActionPerformed

        try {
            int[] rows = table_sale.getSelectedRows();
            for(int i = 0; i < rows.length; i++){
                catelogModelList.remove(rows[i]);
            }
            SaleCatelogTableModel catelogTableModel = new SaleCatelogTableModel(catelogModelList);
            table_sale.setModel(catelogTableModel);
            table_saleVetoableChange(null);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_delete_table_sale_buttonActionPerformed

    private void cnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnameFocusGained
        try {
            if(cname.getText().trim().equalsIgnoreCase("Enter Supplier name")){
                cname.setText("");
            }else {

            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_cnameFocusGained

    private void cnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnameFocusLost
        try {
            if(cname.getText().trim().equalsIgnoreCase("")){
                cname.setText("Enter Supplier name");
            }else{

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cnameFocusLost

    private void cnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyReleased

        try {

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cnameKeyReleased

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        try {
            SuplierRegistration.getInstance().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    
    

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
            if(table_sale.getRowCount() > 0){
                List<SaleBean> beans = new ArrayList<>();
//                InvoiceReportModel irm = ((DetailedInvoiceReportTableModel)this.table_sale.getModel()).getModel(table_sale.getSelectedRow());
//                List<SaleBean> list = reportDAL.getTrkDetails(irm);
                SaleBean bean = null;
               for(int i=0; i < catelogModelList.size(); i++) {
                   bean = new SaleBean(i, null, null, catelogModelList.get(i).getCategoryModel().getProductEntryModel().getProductName()
                           , null, String.valueOf(catelogModelList.get(i).getTransactionModel().getQnty()),
                           commonMethods.rupee(String.valueOf(catelogModelList.get(i).getTransactionModel().getUcost())),
                           commonMethods.rupee(String.valueOf(catelogModelList.get(i).getTransactionModel().getUtot())));
                   beans.add(bean);
               }
               if(beans.size()>0){
                  JRBeanCollectionDataSource beanCollectionDataSource = new JRBeanCollectionDataSource(beans);
                  Map<String,Object> m = new HashMap();
                  m.put("sp", cname.getText().trim());
                  m.put("trk", trkNo.getText());
                  m.put("invdt", commonMethods.dateviewformat(entryDate.getDate()));
                  m.put("exp", commonMethods.rupee(exp.getText().trim()));
                  m.put("expp", (expper.getText().trim()));
                  m.put("hire", commonMethods.rupee(lryHire.getText().trim()));
                  m.put("cooli", commonMethods.rupee(cooli.getText().trim()));
                  m.put("cash", commonMethods.rupee(cash.getText().trim()));
                  m.put("kata", commonMethods.rupee(ktcash.getText().trim()));
                  m.put("amc", commonMethods.rupee(amc.getText().trim()));
                  m.put("gr", (gsale.getText().trim()));
                  m.put("ftot", (tot.getText().trim()));
                  m.put("netSale", (netSale.getText().trim()));
                  m.put("qty", getQnty());
                  
                    
                try {
                    JasperDesign design = JRXmlLoader.load("Business_Report\\doup.jrxml");
                    JasperReport jasperReport = JasperCompileManager.compileReport(design);
                    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, m, beanCollectionDataSource);
                    JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
                    jasperViewer.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
            } else {
                   JOptionPane.showMessageDialog(null, "No data..!");
               }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void expKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expKeyTyped
 try {
            char c = evt.getKeyChar();
//            boolean t = Integer.parseInt(ftotal.getText().trim().replaceAll(",", "")) < Integer.parseInt(balance.getText().trim().replaceAll(",", ""));
//            System.out.println(t);
        if (!(Character.isDigit(c) || (c == evt.VK_BACK_SPACE) || c == evt.VK_DELETE ) ) {
//            JOptionPane.showMessageDialog(null, "enter  only");
            evt.consume();
        } 
        if(c == '0' && paid.getText().trim().equals("")){
//            System.out.println("sdf");
              evt.consume();
            }
        } catch (Exception e) {
            System.err.println("Exception in paidTxt keyTypedEvent");
            e.printStackTrace();
        }
    }//GEN-LAST:event_expKeyTyped

    private void lryHireKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lryHireKeyTyped
        expKeyTyped(evt);
    }//GEN-LAST:event_lryHireKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        new DoupReport().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cooliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cooliKeyTyped
        expKeyTyped(evt);
    }//GEN-LAST:event_cooliKeyTyped

    private void cashKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashKeyTyped
expKeyTyped(evt);
    }//GEN-LAST:event_cashKeyTyped

    private void ktcashKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ktcashKeyTyped
expKeyTyped(evt);
    }//GEN-LAST:event_ktcashKeyTyped

    private void amcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amcKeyTyped
expKeyTyped(evt);
    }//GEN-LAST:event_amcKeyTyped

    private void expKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expKeyReleased
        try {
            int exptxt=0,lryhir=0,coli=0,cas=0,kt=0,amc1 = 0;
            int ftot =0;
            
            if(!exp.getText().trim().isEmpty()){
                
                exptxt = commonMethods.rupeeToInt(exp.getText());
                
            }
            if(!lryHire.getText().trim().isEmpty()){
                
                lryhir = commonMethods.rupeeToInt(lryHire.getText());
            }
            if(!cooli.getText().trim().isEmpty()){
                
                coli = commonMethods.rupeeToInt(cooli.getText());
            }
            if(!cash.getText().trim().isEmpty()){
                
                cas = commonMethods.rupeeToInt(cash.getText());
            }
            if(!ktcash.getText().trim().isEmpty()){
                
                kt = commonMethods.rupeeToInt(ktcash.getText());
            }
            if(!amc.getText().trim().isEmpty()){
                
                amc1 = commonMethods.rupeeToInt(amc.getText());
            }
            ftot = exptxt + lryhir + coli + cas + kt + amc1;
            tot.setText(commonMethods.rupee(String.valueOf(ftot)));
            lessEFR.setText(commonMethods.rupee(String.valueOf(ftot)));
            int grs = commonMethods.rupeeToInt(gsale.getText().trim());
            int net = grs - ftot;
            System.out.println("dsf : "+commonMethods.rupee(String.valueOf(net)));
            netSale.setText(commonMethods.rupee(String.valueOf(net)));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_expKeyReleased

    private void lryHireKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lryHireKeyReleased
        expKeyReleased(evt);
    }//GEN-LAST:event_lryHireKeyReleased

    private void cooliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cooliKeyReleased
expKeyReleased(evt);
    }//GEN-LAST:event_cooliKeyReleased

    private void cashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashKeyReleased
expKeyReleased(evt);
    }//GEN-LAST:event_cashKeyReleased

    private void ktcashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ktcashKeyReleased
expKeyReleased(evt);
    }//GEN-LAST:event_ktcashKeyReleased

    private void amcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amcKeyReleased
expKeyReleased(evt);
    }//GEN-LAST:event_amcKeyReleased

    private void expperKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expperKeyReleased
        try {
            int gs = commonMethods.rupeeToInt(gsale.getText());
//            System.out.println("gs : "+gs);
//            System.out.println("exper : "+expper.getText());
//            System.out.println("exper% : "+(commonMethods.rupeeToInt(expper.getText())/100));
            int exp1 = (gs*commonMethods.rupeeToInt(expper.getText()))/100;
            System.out.println("expen : "+exp1);
            exp.setText(commonMethods.rupee(String.valueOf(exp1)));
            expKeyReleased(evt);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_expperKeyReleased

    private void expperKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expperKeyTyped

        // TODO add your handling code here:
        expKeyTyped(evt);
    }//GEN-LAST:event_expperKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoupReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoupReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoupReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoupReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoupReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField advPay;
    private javax.swing.JTextField amc;
    private javax.swing.JTextField cash;
    private static javax.swing.JTextField cname;
    private javax.swing.JTextField cooli;
    private javax.swing.JButton delete_table_sale_button;
    private javax.swing.JButton edit_table_sale_button;
    private com.toedter.calendar.JDateChooser entryDate;
    private javax.swing.JTextField exp;
    private javax.swing.JTextField expper;
    private javax.swing.JTextField gsale;
    private javax.swing.JList itemList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField ktcash;
    private javax.swing.JTextField lessEFR;
    private javax.swing.JTextField lryHire;
    private javax.swing.JTextField netSale;
    private javax.swing.JTextField paid;
    private javax.swing.JTextField qntytxt;
    private javax.swing.JTable table_sale;
    private javax.swing.JTextField tot;
    private javax.swing.JTextField transName;
    private javax.swing.JTextField trkNo;
    private javax.swing.JTextField unitcosttxt;
    private javax.swing.JTextField unittottxt;
    // End of variables declaration//GEN-END:variables

    public void updateProductList() {
        DefaultListModel defaultListModel = new DefaultListModel();
//        ListModel listModel = (ListModel) commonMethods.loadProductComboo();
        for(int i=0;i<commonMethods.loadProductComboo().size();i++)
        defaultListModel.addElement(commonMethods.loadProductComboo().get(i));
        this.itemList.setModel(defaultListModel);
        
    }
    public void updateProductCategoryList() {
        DefaultListModel defaultListModel = new DefaultListModel();
//        ListModel listModel = (ListModel) commonMethods.loadProductComboo();
        for(int i=0;i<commonMethods.loadProductCategoryComboo().size();i++)
        defaultListModel.addElement(commonMethods.loadProductCategoryComboo().get(i));
//        this.categoryList.setModel(defaultListModel);
        
    }
    private void updateProductCategoryLisByProduct(int pID) {
        DefaultListModel defaultListModel = new DefaultListModel();
//        ListModel listModel = (ListModel) commonMethods.loadProductComboo();
//        System.out.println("sixe : "+commonMethods.loadProductCategoryCombooByProduct(pID).size());
        for(int i=0;i<commonMethods.loadProductCategoryCombooByProduct(pID).size();i++)
        defaultListModel.addElement(commonMethods.loadProductCategoryCombooByProduct(pID).get(i));
//        this.categoryList.setModel(defaultListModel);
        
    }

    private String getQnty() {
        try {
            int qnty= 0;
            for(int i=0; i<catelogModelList.size(); i++){
                qnty += catelogModelList.get(i).getTransactionModel().getQnty();
            }
            return String.valueOf(qnty);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return "0";
    }

}
