/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Fruit.ui;

import Fruit.Common.CommonMethods;
import Fruit.DAL.DiscountDAL;
import Fruit.Model.DiscountModel;
import Fruit.Model.RegistrationModel;
import Fruit.TableModel.Discount_Damage_PreBalanceTableModel;
import Fruit.test.Test1;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Raffiuddin
 */
public class EditPre_Balance extends javax.swing.JFrame {

    /**
     * Creates new form EditPre_Balance
     */
      List<String> items = new ArrayList<>();
    Fruit.Common.CommonMethods commonMethods = new CommonMethods();
    private List<RegistrationModel> customerModelList;
    DiscountDAL discountDAL=new DiscountDAL();
private int customerId = 0;
DiscountModel model =null;
    public EditPre_Balance() {
        initComponents();
        updateDropDown();
        cname.requestFocus();
        dat2.setDate(new Date());
        discountTable.getTableHeader().setBackground(Color.DARK_GRAY);
        discountTable.getTableHeader().setForeground(Color.white);
        discountTable.getColumnModel().getColumn(0).setMaxWidth(45);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Fruit/Resource/strawberry.png")));
   
    }
     public void updateDropDown(){
        items.clear();
     if(commonMethods.getSuppliers()!=null){
            customerModelList = commonMethods.getCustomers();
         for (RegistrationModel customerModelList1 : customerModelList) {
             items.add(customerModelList1.toString());
         }
        
        }
        Test1.setupAutoComplete(cname, (ArrayList<String>) items);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dat1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        dat2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        discountTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        edate = new com.toedter.calendar.JDateChooser();
        amount = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit previous balance ");

        dat1.setDateFormatString("dd-MM-yyyy");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("-");

        dat2.setDateFormatString("dd-MM-yyyy");

        discountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Date", "Amount", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        discountTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(discountTable);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db-edit-icon.png"))); // NOI18N
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel6.add(editButton);

        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db-updat.jpg"))); // NOI18N
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel6.add(updateButton);

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db-remove-icon.png"))); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel6.add(deleteButton);

        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/refresh-1.png"))); // NOI18N
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel6.add(resetButton);

        jPanel7.setLayout(new java.awt.GridLayout(3, 0, 5, 10));

        edate.setDateFormatString("dd/MM/yyyy");
        jPanel7.add(edate);

        amount.setForeground(new java.awt.Color(0, 0, 255));
        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountKeyReleased(evt);
            }
        });
        jPanel7.add(amount);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        jLabel2.setText("Name");
        jPanel3.add(jLabel2);

        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnameKeyReleased(evt);
            }
        });
        jPanel3.add(cname);

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/search-small.png"))); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel3.add(searchButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dat1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dat2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(dat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 13, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        try {
            //            System.out.println(discountTable.getSelectedRow());
            if(discountTable.getSelectedRow()!=-1){
                edate.setDate(java.sql.Date.valueOf(discountTable.getValueAt(discountTable.getSelectedRow(), 1).toString()));
//                System.out.println(discountTable.getValueAt(discountTable.getSelectedRow(), 1));
                amount.setText(commonMethods.rupee(discountTable.getValueAt(discountTable.getSelectedRow(), 3).toString()));
                model = ((Discount_Damage_PreBalanceTableModel)this.discountTable.getModel()).getModel(discountTable.getSelectedRow());
//                if(model.getMsg().equalsIgnoreCase("discount")){
//                    upReason.setSelectedIndex(1);
//                } else {
//                    upReason.setSelectedIndex(2);
//                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
//            if(upReason.getSelectedIndex()==0){
//                JOptionPane.showMessageDialog(null, "Select damage / discount");
//                upReason.requestFocus();
//            } else {
                System.out.println("bal "+(model.getBal()+(model.getAmount())));
                int upbal = model.getAmount()-commonMethods.rupeeToInt(amount.getText());
                model.setBal((model.getBal()+model.getAmount())-commonMethods.rupeeToInt(amount.getText()));
                model.setAmount(commonMethods.rupeeToInt(amount.getText()));
//                model.setMsg(upReason.getSelectedItem().toString());

                //            System.out.println("bal "+(model.getBal()+model.getAmount()));
                model.setDt(commonMethods.datesaveformat(edate.getDate()));

                discountDAL.updatePre_Balance(model);
                discountDAL.updateAfterPrev_Balance(upbal, customerId, model.getId());
                searchButtonActionPerformed(evt);
                resetButtonActionPerformed(evt);
//            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            if(discountTable.getSelectedRowCount()>0){
                model = ((Discount_Damage_PreBalanceTableModel)this.discountTable.getModel()).getModel(discountTable.getSelectedRow());
                System.out.println("bal "+(model.getBal()+(model.getAmount())));
                int upbal = model.getAmount();
                model.setBal((model.getBal()+model.getAmount())-commonMethods.rupeeToInt(amount.getText()));
                model.setAmount(commonMethods.rupeeToInt(amount.getText()));
//                model.setMsg(upReason.getSelectedItem().toString());

                //            System.out.println("bal "+(model.getBal()+model.getAmount()));
                model.setDt(commonMethods.datesaveformat(edate.getDate()));

                discountDAL.deletePre_Balance(model);
                discountDAL.updateAfterPrev_Balance(upbal, customerId, model.getId());
                searchButtonActionPerformed(evt);
                resetButtonActionPerformed(evt);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        try {
            amount.setText("");
            edate.setDate(null);
//            upReason.setSelectedIndex(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_resetButtonActionPerformed

    private void amountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyReleased

        try {
            amount.setText(commonMethods.rupee(amount.getText().trim().replaceAll(",", "")));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_amountKeyReleased

    private void cnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyReleased

        int cidIn = this.items.indexOf(this.cname.getText().trim());

        //            System.out.println(" sgfg : "+cidIn);
        if(cidIn >= 0){

            customerId = customerModelList.get(cidIn).getCsID();
        }
    }//GEN-LAST:event_cnameKeyReleased

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try {
            if(customerId!=0){
                List<DiscountModel> dm = discountDAL.getPrev_Balance(customerId, null, null);
                Fruit.TableModel.Discount_Damage_PreBalanceTableModel ddpbtm = new Discount_Damage_PreBalanceTableModel(dm);
                discountTable.setModel(ddpbtm);
                discountTable.getColumnModel().getColumn(0).setMaxWidth(45);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPre_Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPre_Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPre_Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPre_Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPre_Balance().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JTextField cname;
    private com.toedter.calendar.JDateChooser dat1;
    private com.toedter.calendar.JDateChooser dat2;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTable discountTable;
    private com.toedter.calendar.JDateChooser edate;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
