/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Fruit.ui;

import Fruit.Common.CommonMethods;
import Fruit.DAL.DiscountDAL;
import Fruit.DAL.ProductDAL;
import Fruit.DAL.TrxDAL;
import Fruit.Model.DiscountModel;
import Fruit.Model.InvoiceModel;
import Fruit.Model.ProductCategoryModel;
import Fruit.Model.ProductEntryModel;
import Fruit.Model.RegistrationModel;
import Fruit.Model.SaleCatelogModel;
import Fruit.Model.SaleEntryTrxModel;
import Fruit.Model.SaleTransactionModel;
import Fruit.TableModel.SaleCatelogTableModel;
import Fruit.test.Test1;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raffiuddin
 */
public class FinalReport extends javax.swing.JFrame {

    /**
     * Creates new form FinalReport
     */
    
    Connection con;
    private Object[] columnNames = {"Items","Category","Quantity","UnitCost","Total"};
    ProductDAL productDAL;
    Fruit.Common.CommonMethods commonMethods = new CommonMethods();
    Fruit.Model.ProductCategoryModel categoryModel;
    Fruit.Model.SaleEntryTrxModel trxModel;
    SaleCatelogModel saleCatelogModel;
    List<SaleCatelogModel> catelogModelList = new ArrayList<>();
    List<RegistrationModel> customerModelList = new ArrayList<>();
    RegistrationModel registrationModel;
    List<String> items = new ArrayList<>();
    Fruit.test.Test1 test1;
    TrxDAL trxDAL = new TrxDAL();
    int loadID=0;
    Fruit.Common.CommonMethods md = new Fruit.Common.CommonMethods();
    int tbindex=-1;
    int customerId = 0;
    int cusBalance = 0;
    DiscountDAL discountDAL = new DiscountDAL();
    public FinalReport() {
        initComponents();
        entryDate.setDate(new Date());
        updateProductList();
        updateProductCategoryList();
//        table_sale.getTableHeader().setBackground(Color.DARK_GRAY);
//        table_sale.getTableHeader().setForeground(Color.white);
        
        
        updateDropDown();
        cname.requestFocus();
    }
    
      public void updateDropDown(){
        items.clear();
     if(commonMethods.getSuppliers()!=null){
            customerModelList = commonMethods.getCustomers();
         for (RegistrationModel customerModelList1 : customerModelList) {
             items.add(customerModelList1.toString());
         }
        
        }
        Test1.setupAutoComplete(cname, (ArrayList<String>) items);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        entryDate = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        categoryList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        qntytxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        unitcosttxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        unittottxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_sale = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        edit_table_sale_button = new javax.swing.JButton();
        delete_table_sale_button = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        cname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        preBal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ftotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        paid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        comboDiscount = new javax.swing.JComboBox();
        discount = new javax.swing.JTextField();
        dicountSubmitButton = new javax.swing.JButton();
        cancelDiscountButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        entryDate.setDateFormatString("dd/MM/yyyy");
        entryDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        entryDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entryDateMouseExited(evt);
            }
        });
        entryDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                entryDatePropertyChange(evt);
            }
        });

        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jPanel5.setLayout(new java.awt.BorderLayout(0, 10));

        itemList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemList.setForeground(new java.awt.Color(0, 204, 0));
        itemList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Apple", "Orange" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        itemList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        itemList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                itemListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(itemList);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Items");
        jPanel5.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout(0, 10));

        categoryList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        categoryList.setForeground(new java.awt.Color(0, 204, 0));
        categoryList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Kg", "Box" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        categoryList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(categoryList);

        jPanel6.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Category");
        jPanel6.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 4, 5, 0));

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.X_AXIS));

        qntytxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        qntytxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qntytxtKeyReleased(evt);
            }
        });
        jPanel12.add(qntytxt);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" X");
        jPanel12.add(jLabel3);

        jPanel7.add(jPanel12);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        unitcosttxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        unitcosttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unitcosttxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                unitcosttxtKeyTyped(evt);
            }
        });
        jPanel13.add(unitcosttxt);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" =");
        jPanel13.add(jLabel4);

        jPanel7.add(jPanel13);

        unittottxt.setEditable(false);
        unittottxt.setForeground(new java.awt.Color(0, 37, 194));
        unittottxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel7.add(unittottxt);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/Actions-list-add-icon.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Items List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(204, 0, 51)));
        jPanel8.setLayout(new java.awt.BorderLayout(0, 3));

        table_sale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Items", "Category", "Quantity", "UnitCost", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_sale.setToolTipText("Sale Items");
        table_sale.setGridColor(new java.awt.Color(204, 204, 204));
        table_sale.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_saleMouseClicked(evt);
            }
        });
        table_sale.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                table_saleMouseDragged(evt);
            }
        });
        table_sale.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                table_salePropertyChange(evt);
            }
        });
        table_sale.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                table_saleVetoableChange(evt);
            }
        });
        jScrollPane3.setViewportView(table_sale);

        jPanel8.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel9.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        edit_table_sale_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db-edit-icon.png"))); // NOI18N
        edit_table_sale_button.setText("Edit");
        edit_table_sale_button.setEnabled(false);
        edit_table_sale_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_table_sale_buttonActionPerformed(evt);
            }
        });
        jPanel9.add(edit_table_sale_button);

        delete_table_sale_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db-remove-icon.png"))); // NOI18N
        delete_table_sale_button.setText("Remove");
        delete_table_sale_button.setEnabled(false);
        delete_table_sale_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_table_sale_buttonActionPerformed(evt);
            }
        });
        jPanel9.add(delete_table_sale_button);

        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_END);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        cname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cname.setForeground(new java.awt.Color(235, 46, 46));
        cname.setText("Enter Customer name");
        cname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnameMouseClicked(evt);
            }
        });
        cname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnameFocusLost(evt);
            }
        });
        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnameKeyReleased(evt);
            }
        });
        jPanel11.add(cname);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/smalladdsym.png"))); // NOI18N
        jLabel8.setToolTipText("Add Customer");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel8);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(entryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(entryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel14.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/shop-cart-apply-icon.png"))); // NOI18N
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel14.add(submitButton);

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/shop-cart-exclude-icon.png"))); // NOI18N
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel14.add(cancelButton);

        jPanel15.setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Balance");
        jPanel15.add(jLabel5);

        preBal.setEditable(false);
        preBal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        preBal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preBalActionPerformed(evt);
            }
        });
        jPanel15.add(preBal);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Total");
        jPanel15.add(jLabel6);

        ftotal.setEditable(false);
        ftotal.setBackground(new java.awt.Color(255, 255, 255));
        ftotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ftotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel15.add(ftotal);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Paid");
        jPanel15.add(jLabel7);

        paid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paid.setForeground(new java.awt.Color(255, 0, 51));
        paid.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paidFocusLost(evt);
            }
        });
        paid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paidKeyTyped(evt);
            }
        });
        jPanel15.add(paid);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Total Balance");
        jPanel15.add(jLabel9);

        balance.setEditable(false);
        balance.setBackground(new java.awt.Color(255, 255, 255));
        balance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        balance.setForeground(new java.awt.Color(0, 0, 255));
        balance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel15.add(balance);

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Discount/Damage/Pre.Balance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel16.setLayout(new java.awt.GridLayout(2, 2, 10, 30));

        comboDiscount.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Discount", "Damage", "Pre. Balance" }));
        jPanel16.add(comboDiscount);

        discount.setForeground(new java.awt.Color(0, 0, 204));
        discount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                discountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                discountKeyTyped(evt);
            }
        });
        jPanel16.add(discount);

        dicountSubmitButton.setText("Submit");
        dicountSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dicountSubmitButtonActionPerformed(evt);
            }
        });
        jPanel16.add(dicountSubmitButton);

        cancelDiscountButton.setText("Cancel");
        cancelDiscountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelDiscountButtonActionPerformed(evt);
            }
        });
        jPanel16.add(cancelDiscountButton);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryDateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entryDateMouseExited
        cnameKeyReleased(null);
    }//GEN-LAST:event_entryDateMouseExited

    private void entryDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_entryDatePropertyChange
        cnameKeyReleased(null);
    }//GEN-LAST:event_entryDatePropertyChange

    private void itemListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_itemListValueChanged
        try {
            if(evt.getValueIsAdjusting()){
                ProductEntryModel entryModel = ((ProductEntryModel)this.itemList.getSelectedValue());
                //            System.out.println("hi1 "+entryModel.getpId());
                updateProductCategoryLisByProduct(entryModel.getpId());
                //            List<ProductCategoryModel> categoryModel = ((ProductCategoryModel)this.categoryModel);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_itemListValueChanged

    private void qntytxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qntytxtKeyReleased

        try {
            unitcosttxtKeyReleased(evt);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_qntytxtKeyReleased

    private void unitcosttxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitcosttxtKeyReleased

        try {
            String s = qntytxt.getText().trim().replaceAll(",", "");
            String str;
            if(s.equalsIgnoreCase("")){
                qntytxt.setText("");
            } else {
                String s2 = unitcosttxt.getText().trim().replaceAll(",", "");
                if(s2.isEmpty()){

                }else{

                    //                    if(md.mul(Integer.parseInt(s), Integer.parseInt(s2))>=1000)
                    //                    {
                        str = md.rupee(Integer.toString(md.mul(Integer.parseInt(s), Integer.parseInt(s2)))).trim();
                        //                    }
                    //                    else{
                        //                        str = Integer.toString(md.mul(Integer.parseInt(s), Integer.parseInt(s2)));
                        //                    }
                    //                    qntytxt.setText(md.rupee(s));
                    unitcosttxt.setText(md.rupee(s2));
                    unittottxt.setText(str);
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_unitcosttxtKeyReleased

    private void unitcosttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitcosttxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_unitcosttxtKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if(itemList.isSelectionEmpty()){
                JOptionPane.showMessageDialog(null, "Please select something in Items List", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);
                itemList.requestFocus();
            } else if(categoryList.isSelectionEmpty()){
                JOptionPane.showMessageDialog(null, "Please select Quantity type", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);
                categoryList.requestFocus();
            } else if(qntytxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please give Quantity", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);
                qntytxt.requestFocus();

            } else if(unitcosttxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please give unitcost", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);
                unitcosttxt.requestFocus();

            } else if(unittottxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please give unitcost", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);
                unittottxt.requestFocus();
            } else {
                String item = itemList.getSelectedValue().toString().trim();
                String itemtype = categoryList.getSelectedValue().toString().trim();
                String qnty = qntytxt.getText().trim().replaceAll(",", "");
                String unitcost = unitcosttxt.getText().trim().replaceAll(",", "");
                String utot = unittottxt.getText().trim().replaceAll(",", "");
                String dt="";

                if(entryDate.getDate() != null)
                dt = commonMethods.datesaveformat(entryDate.getDate());
                int pId = ((ProductEntryModel)this.itemList.getSelectedValue()).getpId();
                int catId = ((ProductCategoryModel)this.categoryList.getSelectedValue()).getCatId();
                List<InvoiceModel> listofInvoiceModel = new ArrayList();
                //                listofInvoiceModel = trxDAL.getProductQntyByCatId(catId);
//                listofInvoiceModel = trxDAL.getProductQntyByP_Id(pId);
                ImageIcon icon = new ImageIcon("Reports.jpg");
                int invoiceID =0, qntity=0, stock=0, sold=0, ldID =0;
                String truckno = "";
                if(listofInvoiceModel.size()==0) {

                    JOptionPane.showMessageDialog( null , "No stock");

                } else {

                    if(listofInvoiceModel.size()>1) {
                        Object[] args = new Object[listofInvoiceModel.size()];
                        List<String> index = new ArrayList();
                        for(int i=0 ; i<listofInvoiceModel.size();i++){
                            args[i] = listofInvoiceModel.get(i).getTrkNo();
                            index.add(listofInvoiceModel.get(i).getTrkNo());
                        }
                        String s = (String) JOptionPane.showInputDialog(
                            this,
                            "Select Truck / load :"
                            ,
                            "Select Dialog",
                            JOptionPane.PLAIN_MESSAGE,
                            icon,
                            args,
                            "Damage");

                        //                    System.out.println("S : "+s);
                        //                    System.out.println("invoice id : "+index.indexOf(s));
                        //                    System.out.println("invoice id : "+listofInvoiceModel.get(index.indexOf(s)).getInvoiceId());
                        //                    System.out.println("invoice id : "+listofInvoiceModel.get(index.indexOf(s)).getTrkNo());
                        qntity = listofInvoiceModel.get(index.indexOf(s)).getQnty();
                        stock = listofInvoiceModel.get(index.indexOf(s)).getStock();

                        sold = listofInvoiceModel.get(index.indexOf(s)).getSold();
                        if(sold ==0 && stock==0)
                        stock = qntity;
                        truckno = listofInvoiceModel.get(index.indexOf(s)).getTrkNo();
                        invoiceID = listofInvoiceModel.get(index.indexOf(s)).getInvoiceId();
                        ldID = listofInvoiceModel.get(index.indexOf(s)).getLoadId();
                        loadID = listofInvoiceModel.get(index.indexOf(s)).getLoadId();
                    } else if (listofInvoiceModel.size()==1) {
                        invoiceID = listofInvoiceModel.get(0).getInvoiceId();
                        qntity = listofInvoiceModel.get(0).getQnty();
                        stock = listofInvoiceModel.get(0).getStock();
                        loadID = listofInvoiceModel.get(0).getLoadId();
                        sold = listofInvoiceModel.get(0).getSold();
                        ldID = listofInvoiceModel.get(0).getLoadId();
                        if(sold==0 && stock==0)
                        stock = qntity;
                    }

                    System.out.println("load : "+ldID);
                    ProductEntryModel productEntryModel = new ProductEntryModel(
                        item, "", true, dt, pId);
                    ProductCategoryModel productCategoryModel = new ProductCategoryModel(
                        itemtype, "", true, dt, catId, 1, productEntryModel);
                    SaleTransactionModel transactionModel = new SaleTransactionModel(
                        Integer.parseInt(qnty), Integer.parseInt(unitcost), Integer.parseInt(utot), pId, 1, ldID);
                    //                    System.out.println("qnty : "+qntity);
                    //                    System.out.println("inv id : "+invoiceID);
                    //                    System.out.println("qnty : "+qntity);
                    //                    System.out.println("stock : "+stock);
                    //                    System.out.println("sold : "+sold);
                    SaleCatelogModel saleCatelogModel = new SaleCatelogModel(productCategoryModel, transactionModel, invoiceID);
                    int qty = Integer.parseInt(qnty) ;
                    for(int i=0; i<catelogModelList.size();i++){
                        if(catelogModelList.get(i).getInvoiceId() == invoiceID){
                            qty += catelogModelList.get(i).getTransactionModel().getQnty();

                        }
                    }
                    System.out.println("qnty : "+qntity+ " qty "+qty);
                    if(qty > stock){
                        JOptionPane.showMessageDialog(null, "Low stock : "+stock+"\n in : "+truckno);

                    } else {
                        catelogModelList.add(saleCatelogModel);
                        SaleCatelogTableModel catelogTableModel = new SaleCatelogTableModel(catelogModelList);
                        table_sale.setModel(catelogTableModel);

                        table_saleVetoableChange(null);
                        qntytxt.setText("");
                        unitcosttxt.setText("");
                        unittottxt.setText("");
                        itemList.clearSelection();
                        categoryList.clearSelection();
                    }
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void table_saleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_saleMouseClicked

        table_saleMouseDragged(evt);
    }//GEN-LAST:event_table_saleMouseClicked

    private void table_saleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_saleMouseDragged
        try {
            int r = table_sale.getSelectedRowCount();
            if(r>0){
                edit_table_sale_button.setEnabled(true);delete_table_sale_button.setEnabled(true);
            } else {
                edit_table_sale_button.setEnabled(false);delete_table_sale_button.setEnabled(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_table_saleMouseDragged

    private void table_salePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_table_salePropertyChange
        //        try {
            //            if(table_sale.getRowCount()>0){
                //                long tot = 0;
                //                for(int i = 0 ; i < table_sale.getRowCount() ; i++){
                    //                    tot += Long.parseLong(table_sale.getModel().getValueAt(i, 4).toString().replaceAll(",", ""));
                    //                }
                //                ftotal.setText(new Fruit.Common.CommonMethods().rupee(String.valueOf(tot)));
                //            }
            //            if(table_sale.getSelectedRows().length>0){
                //                edit_table_sale_button.setEnabled(true);
                //                delete_table_sale_button.setEnabled(true);
                //            } else{
                //                edit_table_sale_button.setEnabled(false);
                //                delete_table_sale_button.setEnabled(false);
                //            }
            //        } catch (Exception e) {
            //            e.printStackTrace();
            //        }
        try {
            table_saleVetoableChange(evt);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_table_salePropertyChange

    private void table_saleVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_table_saleVetoableChange
        try {
            upDateTable();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_table_saleVetoableChange
public void upDateTable(){
        if(table_sale.getRowCount()>0){
//                System.err.println("sdgdfgdfg");
                long tot = 0;
                for(int i = 0 ; i < table_sale.getRowCount() ; i++){
                    tot += Long.parseLong(table_sale.getModel().getValueAt(i, 4).toString().replaceAll(",", ""));
                }
                
                ftotal.setText(new Fruit.Common.CommonMethods().rupee(String.valueOf(tot)));
                String p = paid.getText().trim();long pa=0,ba=0;
                if(!p.equalsIgnoreCase("")){
                 pa = Long.parseLong(p);
                 ba = tot - pa;
                } else {
                   ba = tot;
                   
                }
                paid.setText(new Fruit.Common.CommonMethods().rupee(String.valueOf(pa)));
                if(!preBal.getText().trim().isEmpty())
                ba = ba + Long.parseLong(preBal.getText().trim().replaceAll(",", ""));
                balance.setText(new Fruit.Common.CommonMethods().rupee(String.valueOf(ba)));
            }
            if(table_sale.getSelectedRows().length>0){
                edit_table_sale_button.setEnabled(true);
                delete_table_sale_button.setEnabled(true);
            } else{
                edit_table_sale_button.setEnabled(false);
                delete_table_sale_button.setEnabled(false);
            }
    }
    private void edit_table_sale_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_table_sale_buttonActionPerformed
        try {
            if(table_sale.getSelectedRowCount()>0){
                tbindex = table_sale.getSelectedRow();
                saleCatelogModel = catelogModelList.get(tbindex);
                System.out.println("afdsd : "+saleCatelogModel.getCategoryModel().getProductEntryModel().getProductName().trim());
                this.itemList.setSelectedValue((Object)this.saleCatelogModel.getCategoryModel().getProductEntryModel().getProductName(),true);
                categoryList.setSelectedValue((Object)saleCatelogModel.getCategoryModel().getCategoryName().trim(), true);
                //                itemList.setSelectedIndex(0);
                qntytxt.setText(Integer.toString(saleCatelogModel.getTransactionModel().getQnty()));
                unitcosttxt.setText(Integer.toString(saleCatelogModel.getTransactionModel().getUcost()));
                unittottxt.setText(Integer.toString(saleCatelogModel.getTransactionModel().getUtot()));
                catelogModelList.remove(tbindex);
                SaleCatelogTableModel tableModel = new SaleCatelogTableModel(catelogModelList);
                table_sale.setModel(tableModel);
                table_saleVetoableChange(null);
                //                DefaultTableModel dml = (DefaultTableModel) table_sale.getModel();
                //                dml.removeRow(tbindex);
                //                 String cnt = Integer.toString(dml.getRowCount());

                upDateTable();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_edit_table_sale_buttonActionPerformed

    private void delete_table_sale_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_table_sale_buttonActionPerformed

        try {
            int[] rows = table_sale.getSelectedRows();
            for(int i = 0; i < rows.length; i++){
                catelogModelList.remove(rows[i]);
            }
            SaleCatelogTableModel catelogTableModel = new SaleCatelogTableModel(catelogModelList);
            table_sale.setModel(catelogTableModel);
            table_saleVetoableChange(null);upDateTable();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_delete_table_sale_buttonActionPerformed

    private void cnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnameMouseClicked
        try {
            int cidIn = this.items.indexOf(this.cname.getText().trim());

            //            System.out.println("sdfg : "+cidIn);
            if(cidIn >= 0){

                customerId = customerModelList.get(cidIn).getCsID();
                //                System.out.println("CID : "+customerId);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cnameMouseClicked

    private void cnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnameFocusGained
        try {
            if(cname.getText().trim().equalsIgnoreCase("Enter Customer name")){
                cname.setText("");
            }else {

            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_cnameFocusGained

    private void cnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnameFocusLost
        try {
            if(cname.getText().trim().equalsIgnoreCase("")){
                cname.setText("Enter Customer name");
            }else{

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cnameFocusLost

    private void cnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyReleased

        try {
            int cidIn = this.items.indexOf(this.cname.getText().trim());

            //            System.out.println(" sgfg : "+cidIn);
            if(cidIn >= 0){

                customerId = customerModelList.get(cidIn).getCsID();
                //                System.out.println("CID : "+customerId);
                if(customerId!=0){
                    String pb="";
                    //                    if(entryDate.getDate()!=null){
                        cusBalance = new TrxDAL().getCustomerBalance(customerId);

                        //                    }
                    //                    System.out.println("bal : "+cusBalance);

                    preBal.setText(commonMethods.rupee(Integer.toString(cusBalance)));
                } else {
                    preBal.setText("0");
                }
                upDateTable();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cnameKeyReleased

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        try {
            CustomerRegistration.getInstance().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try {
            if(ftotal.getText().trim().isEmpty() || ftotal.getText().trim().equals("0")){

                if(!paid.getText().trim().isEmpty() && table_sale.getRowCount()==0){
                    int pd = commonMethods.rupeeToInt(paid.getText().trim());
                    int bl = commonMethods.rupeeToInt(balance.getText());
                    trxModel = new SaleEntryTrxModel(
                        customerId , 0, pd, bl, 0, commonMethods.datesaveformat(entryDate.getDate()));
                    int i=trxDAL.addCustomerTrx(trxModel);
                    if(i>0)
                    JOptionPane.showMessageDialog(null, "Transaction successful..!");
                    cancelButtonActionPerformed(evt);

                } else {
                    JOptionPane.showMessageDialog(null, "No data for transaction..!");
                }
            }else{
                int tot = Integer.parseInt(ftotal.getText().trim().replaceAll(",", ""));
                int pd = Integer.parseInt(paid.getText().trim().replaceAll(",", ""));
                int bl = Integer.parseInt(balance.getText().trim().replaceAll(",", ""));

                //            System.out.println(" SDFSDF "+this.items.indexOf(this.cname.getText().trim()));
                int cidIn = this.items.indexOf(this.cname.getText().trim());

                if(cidIn < 0){

                    JOptionPane.showMessageDialog(null, "Enter customer name..!");
                    cname.setText("");
                    cname.requestFocus();
                } else {
                    customerId = customerModelList.get(cidIn).getCsID();
                    trxModel = new SaleEntryTrxModel(
                        customerId , tot, pd, bl, 0, commonMethods.datesaveformat(entryDate.getDate()));
                    int t_ID = trxDAL.addCustomerTrx(trxModel);
                    //                System.err.println("T_ID : "+t_ID);

                    for(int i = 0; i < catelogModelList.size(); i++){
                        SaleTransactionModel saleTransactionModel = new SaleTransactionModel(
                            catelogModelList.get(i).getTransactionModel().getQnty(),
                            catelogModelList.get(i).getTransactionModel().getUcost(),
                            catelogModelList.get(i).getTransactionModel().getUtot(),
                            catelogModelList.get(i).getCategoryModel().getCatId(),
                            t_ID,catelogModelList.get(i).getTransactionModel().getInvoiceId());
                        trxDAL.addCustomerTtlTrx(saleTransactionModel);

                    }
                    //                customerModelList.clear();
                    catelogModelList.clear();
                    JOptionPane.showMessageDialog(null, "Transaction successful..!");
                    cancelButtonActionPerformed(evt);

                }

            }
        } catch (Exception e) {
            System.err.println("Exception in sale submitbutton : ");
            e.printStackTrace();
        }

    }//GEN-LAST:event_submitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed

        try {
            cname.setText("Enter Customer name");
            itemList.clearSelection();
            categoryList.clearSelection();
            qntytxt.setText("");
            unitcosttxt.setText("");
            unittottxt.setText("");
            DefaultTableModel dml = new DefaultTableModel(columnNames, 0);
            table_sale.setModel(dml);
            ftotal.setText("");
            paid.setText("");
            balance.setText("");cname.requestFocus();
            customerId=0;
            cusBalance=0;
            preBal.setText("");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void preBalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preBalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preBalActionPerformed

    private void paidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paidFocusGained
        try {
            if(paid.getText().trim().equals("0")){
                paid.setText("");
            }
        } catch (Exception e) {

            e.printStackTrace();
        }
    }//GEN-LAST:event_paidFocusGained

    private void paidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paidFocusLost
        try {
            if(paid.getText().trim().equals("")){
                paid.setText("0");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_paidFocusLost

    private void paidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidKeyReleased
        try {
            if(!paid.getText().trim().isEmpty()){
                String pa = paid.getText().trim().replaceAll(",", "");

                if(Integer.parseInt(pa)>0)
                balance.setText(md.rupee(Integer.toString(md.sub((commonMethods.rupeeToInt(ftotal.getText())+cusBalance), Integer.parseInt(pa)))));
                else if(Integer.parseInt(pa) == 0 ){
                    balance.setText(ftotal.getText().trim());
                    //                   System.out.println("sad");
                }
            } else {
                balance.setText(ftotal.getText().trim());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_paidKeyReleased

    private void paidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidKeyTyped

        try {
            char c = evt.getKeyChar();
            //            boolean t = Integer.parseInt(ftotal.getText().trim().replaceAll(",", "")) < Integer.parseInt(balance.getText().trim().replaceAll(",", ""));
            //            System.out.println(t);
            if (!(Character.isDigit(c) || (c == evt.VK_BACK_SPACE) || c == evt.VK_DELETE ) ) {
                //            JOptionPane.showMessageDialog(null, "enter  only");
                evt.consume();

            }
            if(commonMethods.rupeeToInt(ftotal.getText())+commonMethods.rupeeToInt(preBal.getText())< commonMethods.rupeeToInt(paid.getText()+c)){
                System.out.println("sdfgdfg");
                evt.consume();
            }

            if(c == '0' && paid.getText().trim().equals("")){
                //            System.out.println("sdf");
                evt.consume();
            }
        } catch (Exception e) {
            System.err.println("Exception in paidTxt keyTypedEvent");
            e.printStackTrace();
        }
    }//GEN-LAST:event_paidKeyTyped

    private void discountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountKeyReleased
        try {
            discount.setText(commonMethods.rupee(discount.getText().trim().replaceAll(",", "")));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_discountKeyReleased

    private void discountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountKeyTyped

        try {
            char c = evt.getKeyChar();
            //            boolean t = Integer.parseInt(ftotal.getText().trim().replaceAll(",", "")) < Integer.parseInt(balance.getText().trim().replaceAll(",", ""));
            //            System.out.println(t);
            if (!(Character.isDigit(c) || (c == evt.VK_BACK_SPACE) || c == evt.VK_DELETE ) ) {
                //            JOptionPane.showMessageDialog(null, "enter  only");
                evt.consume();

            }
            if(commonMethods.rupeeToInt(ftotal.getText())>0){
                //                System.out.println("sdfgdfg");
                evt.consume();
            }
            if(!comboDiscount.getSelectedItem().toString().equalsIgnoreCase("Pre. Balance")){
                if(commonMethods.rupeeToInt(preBal.getText())< commonMethods.rupeeToInt(discount.getText()+c)){
                    //                System.out.println("sdfgdfg");
                    evt.consume();
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_discountKeyTyped

    private void dicountSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dicountSubmitButtonActionPerformed
        try {
            String dis = discount.getText().trim().replaceAll(",", "");
            if(comboDiscount.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(null, "Select Discount /\n Damage /\n Previous balance");
            } else {
                String op = comboDiscount.getSelectedItem().toString();
                if(dis.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Enter "+op+" amount");
                } else {
                    if(op.equalsIgnoreCase("Pre. Balance")){
                        DiscountModel dm = new DiscountModel(
                            1,
                            Integer.parseInt(dis),
                            cusBalance + Integer.parseInt(dis),
                            customerId,
                            op,
                            commonMethods.datesaveformat(entryDate.getDate()), null);
                        discountDAL.addDiscount_Damage(dm);
                    } else {
                        DiscountModel dm = new DiscountModel(
                            1,
                            Integer.parseInt(dis),
                            cusBalance - Integer.parseInt(dis),
                            customerId,
                            op,
                            commonMethods.datesaveformat(entryDate.getDate()), null);
                        discountDAL.addDiscount_Damage(dm);
                    }
                    cancelDiscountButtonActionPerformed(evt);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_dicountSubmitButtonActionPerformed

    private void cancelDiscountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelDiscountButtonActionPerformed
        try {
            discount.setText("");
            comboDiscount.setSelectedIndex(0);
            cancelButtonActionPerformed(evt);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cancelDiscountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balance;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelDiscountButton;
    private javax.swing.JList categoryList;
    private javax.swing.JTextField cname;
    private javax.swing.JComboBox comboDiscount;
    private javax.swing.JButton delete_table_sale_button;
    private javax.swing.JButton dicountSubmitButton;
    private javax.swing.JTextField discount;
    private javax.swing.JButton edit_table_sale_button;
    private com.toedter.calendar.JDateChooser entryDate;
    private javax.swing.JTextField ftotal;
    private javax.swing.JList itemList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField paid;
    private javax.swing.JTextField preBal;
    private javax.swing.JTextField qntytxt;
    private javax.swing.JButton submitButton;
    private javax.swing.JTable table_sale;
    private javax.swing.JTextField unitcosttxt;
    private javax.swing.JTextField unittottxt;
    // End of variables declaration//GEN-END:variables

    public void updateProductList() {
        DefaultListModel defaultListModel = new DefaultListModel();
//        ListModel listModel = (ListModel) commonMethods.loadProductComboo();
        for(int i=0;i<commonMethods.loadProductComboo().size();i++)
        defaultListModel.addElement(commonMethods.loadProductComboo().get(i));
        this.itemList.setModel(defaultListModel);
        
    }
    public void updateProductCategoryList() {
        DefaultListModel defaultListModel = new DefaultListModel();
//        ListModel listModel = (ListModel) commonMethods.loadProductComboo();
        for(int i=0;i<commonMethods.loadProductCategoryComboo().size();i++)
        defaultListModel.addElement(commonMethods.loadProductCategoryComboo().get(i));
        this.categoryList.setModel(defaultListModel);
        
    }
    public void updateProductCategoryLisByProduct(int pID) {
        DefaultListModel defaultListModel = new DefaultListModel();
//        ListModel listModel = (ListModel) commonMethods.loadProductComboo();
//        System.out.println("sixe : "+commonMethods.loadProductCategoryCombooByProduct(pID).size());
        for(int i=0;i<commonMethods.loadProductCategoryCombooByProduct(pID).size();i++)
        defaultListModel.addElement(commonMethods.loadProductCategoryCombooByProduct(pID).get(i));
        this.categoryList.setModel(defaultListModel);
        
    }

}
