/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Fruit.ui;

import Fruit.test.*;
import Fruit.Common.CommonMethods;
import Fruit.DAL.InvoiceDAL;
import Fruit.DAL.ProductDAL;
import Fruit.Model.InvoiceEntryModel;
import Fruit.Model.InvoiceModel;
import Fruit.Model.ProductCategoryModel;
import Fruit.Model.ProductEntryModel;
import Fruit.Model.RegistrationModel;
import Fruit.Model.SaleCatelogModel;
import Fruit.Model.SaleEntryTrxModel;
import Fruit.Model.SaleTransactionModel;
import Fruit.TableModel.SaleCatelogTableModel;
import java.awt.Color;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raffiuddin
 */
public class InvoiceEntry extends javax.swing.JPanel {

    /**
     * Creates new form InvoiceEntry
     */
    Connection con;
    private Object[] columnNames = {"Items","Category","Quantity","UnitCost","Total"};
    ProductDAL productDAL;
    static Fruit.Common.CommonMethods commonMethods = new CommonMethods();
    Fruit.Model.ProductCategoryModel categoryModel;
    Fruit.Model.SaleEntryTrxModel trxModel ;
    SaleCatelogModel saleCatelogModel;
    List<SaleCatelogModel> catelogModelList = new ArrayList<>();
    static List<RegistrationModel> customerModelList = new ArrayList<>();
    RegistrationModel registrationModel;
    public  List<String> items = new ArrayList<>();
    Fruit.test.Test1 test1;
    Fruit.DAL.InvoiceDAL trxDAL = new InvoiceDAL();
    public InvoiceEntry() {
        initComponents();
        entryDate.setDate(new Date());
        updateProductList();
        updateProductCategoryList();
        table_sale.getTableHeader().setBackground(Color.DARK_GRAY);
        table_sale.getTableHeader().setForeground(Color.white);
        updateDropDown();
        
        
    }
    public void updateDropDown(){
        items.clear();
     if(commonMethods.getSuppliers()!=null){
            customerModelList = commonMethods.getSuppliers();
         for (RegistrationModel customerModelList1 : customerModelList) {
             items.add(customerModelList1.toString());
         }
        
        }
        Test1.setupAutoComplete(cname, (ArrayList<String>) items);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        entryDate = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemList = new javax.swing.JList();
        jPanel14 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        qntytxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        unitcosttxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        unittottxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_sale = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        edit_table_sale_button = new javax.swing.JButton();
        delete_table_sale_button = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        cname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        trkNo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        transName = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ftotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        paid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        entryDate.setForeground(new java.awt.Color(0, 102, 102));
        entryDate.setDateFormatString("dd/MM/yyyy");
        entryDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jPanel2.setLayout(new java.awt.BorderLayout(0, 5));

        itemList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemList.setForeground(new java.awt.Color(0, 204, 0));
        itemList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Apple", "Orange" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        itemList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        itemList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                itemListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(itemList);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setForeground(new java.awt.Color(159, 128, 35));
        jLabel1.setText("Items                                   ");
        jPanel14.add(jLabel1);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/smalladdsym.png"))); // NOI18N
        jLabel10.setToolTipText("Add Product");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel14.add(jLabel10);

        jPanel2.add(jPanel14, java.awt.BorderLayout.PAGE_START);

        jPanel4.add(jPanel2);

        jPanel5.setLayout(new java.awt.GridLayout(1, 4, 5, 0));

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.X_AXIS));

        qntytxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        qntytxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qntytxtKeyReleased(evt);
            }
        });
        jPanel12.add(qntytxt);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" X");
        jPanel12.add(jLabel3);

        jPanel5.add(jPanel12);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        unitcosttxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        unitcosttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unitcosttxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                unitcosttxtKeyTyped(evt);
            }
        });
        jPanel13.add(unitcosttxt);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" =");
        jPanel13.add(jLabel4);

        jPanel5.add(jPanel13);

        unittottxt.setEditable(false);
        unittottxt.setForeground(new java.awt.Color(0, 37, 194));
        unittottxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(unittottxt);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/Actions-list-add-icon.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "Items List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(204, 0, 51)));
        jPanel7.setLayout(new java.awt.BorderLayout(0, 3));

        table_sale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Items", "Category", "Quantity", "UnitCost", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_sale.setToolTipText("Sale Items");
        table_sale.setGridColor(new java.awt.Color(204, 204, 204));
        table_sale.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_saleMouseClicked(evt);
            }
        });
        table_sale.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                table_saleMouseDragged(evt);
            }
        });
        table_sale.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                table_salePropertyChange(evt);
            }
        });
        table_sale.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                table_saleVetoableChange(evt);
            }
        });
        jScrollPane3.setViewportView(table_sale);

        jPanel7.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        edit_table_sale_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db-edit-icon.png"))); // NOI18N
        edit_table_sale_button.setText("Edit");
        edit_table_sale_button.setEnabled(false);
        edit_table_sale_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_table_sale_buttonActionPerformed(evt);
            }
        });
        jPanel8.add(edit_table_sale_button);

        delete_table_sale_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db-remove-icon.png"))); // NOI18N
        delete_table_sale_button.setText("Remove");
        delete_table_sale_button.setEnabled(false);
        delete_table_sale_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_table_sale_buttonActionPerformed(evt);
            }
        });
        jPanel8.add(delete_table_sale_button);

        jPanel7.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        cname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cname.setForeground(new java.awt.Color(235, 46, 46));
        cname.setText("Enter Supplier name");
        cname.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                cnameCaretUpdate(evt);
            }
        });
        cname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnameFocusLost(evt);
            }
        });
        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnameKeyReleased(evt);
            }
        });
        jPanel11.add(cname);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/smalladdsym.png"))); // NOI18N
        jLabel8.setToolTipText("Add supplier");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel8);

        jLabel11.setText("Truck No  *");

        jLabel12.setText("Transport");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(trkNo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(transName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(entryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(entryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(trkNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(transName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel10.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/shop-cart-apply-icon.png"))); // NOI18N
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel10.add(submitButton);

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/shop-cart-exclude-icon.png"))); // NOI18N
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel10.add(cancelButton);

        jPanel9.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        jLabel5.setText("Total");
        jPanel9.add(jLabel5);

        ftotal.setEditable(false);
        ftotal.setBackground(new java.awt.Color(255, 255, 255));
        ftotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ftotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel9.add(ftotal);

        jLabel6.setText("Paid");
        jPanel9.add(jLabel6);

        paid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paid.setForeground(new java.awt.Color(255, 0, 51));
        paid.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paidFocusLost(evt);
            }
        });
        paid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paidKeyTyped(evt);
            }
        });
        jPanel9.add(paid);

        jLabel7.setText("Balance");
        jPanel9.add(jLabel7);

        balance.setEditable(false);
        balance.setBackground(new java.awt.Color(255, 255, 255));
        balance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        balance.setForeground(new java.awt.Color(0, 0, 255));
        balance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel9.add(balance);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnameFocusGained
        try {
            if(cname.getText().trim().equalsIgnoreCase("Enter Supplier name")){
                cname.setText("");
            }else {
                
            }
                
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cnameFocusGained
    
    private void cnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnameFocusLost
        try {
            if(cname.getText().trim().equalsIgnoreCase("")){
                cname.setText("Enter Supplier name");
            }else{
                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cnameFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if(itemList.isSelectionEmpty()){
                JOptionPane.showMessageDialog(null, "Please select something in Items List", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);
                itemList.requestFocus();
//            } else if(categoryList.isSelectionEmpty()){
//                JOptionPane.showMessageDialog(null, "Please select Quantity type", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);    
//                categoryList.requestFocus();
            } else if(qntytxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please give Quantity", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);    
                qntytxt.requestFocus();
            
//            } else if(unitcosttxt.getText().trim().isEmpty()){
//                JOptionPane.showMessageDialog(null, "Please give unitcost", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);    
//                unitcosttxt.requestFocus();
//            
//            } else if(unittottxt.getText().trim().isEmpty()){
//                JOptionPane.showMessageDialog(null, "Please give unitcost", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);    
//                unittottxt.requestFocus();
            } else {
                String item = itemList.getSelectedValue().toString().trim();
//                String itemtype = categoryList.getSelectedValue().toString().trim();
                String qnty = qntytxt.getText().trim().replaceAll(",", "");
                String unitcost = unitcosttxt.getText().trim().replaceAll(",", "");
                String utot = unittottxt.getText().trim().replaceAll(",", "");
                String dt="";
                if(entryDate.getDate() != null)
                 dt = commonMethods.datesaveformat(entryDate.getDate());
                int pId = ((ProductEntryModel)this.itemList.getSelectedValue()).getpId();
//                int catId = ((ProductCategoryModel)this.categoryList.getSelectedValue()).getCatId();
                ProductEntryModel productEntryModel = new ProductEntryModel(
                        item, "", true, dt, pId);
                ProductCategoryModel productCategoryModel = new ProductCategoryModel(
                        "", "", true, dt, 1, 1, productEntryModel);
                SaleTransactionModel transactionModel = new SaleTransactionModel(
                        commonMethods.rupeeToInt(qnty), commonMethods.rupeeToInt(unitcost), commonMethods.rupeeToInt(utot), pId, 1, 1);
                SaleCatelogModel saleCatelogModel = new SaleCatelogModel(productCategoryModel, transactionModel,1);
//                System.out.println("pid : "+catId);
//                DefaultTableModel dml = (DefaultTableModel) table_sale.getModel();
                catelogModelList.add(saleCatelogModel);
                SaleCatelogTableModel catelogTableModel = new SaleCatelogTableModel(catelogModelList);
                table_sale.setModel(catelogTableModel);
//                String cnt = Integer.toString(dml.getRowCount()+1);
//                Object[] cols = {"Items ("+cnt+")","QuantityType","Quantity","UnitCost","Total"};
//                Object[] rowData = {item,itemtype,qnty,unitcost,utot};
//                dml.setColumnIdentifiers(cols);
//                if(tbindex!=-1){
//                    dml.insertRow(tbindex, rowData);
//                    tbindex = -1;
//                }else{
//                dml.addRow(rowData);
//                }
                
                table_saleVetoableChange(null);
                qntytxt.setText("");
                unitcosttxt.setText("");
                unittottxt.setText("");
                itemList.clearSelection();
//                categoryList.clearSelection();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void qntytxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qntytxtKeyReleased

        try {
            unitcosttxtKeyReleased(evt);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_qntytxtKeyReleased
Fruit.Common.CommonMethods md = new Fruit.Common.CommonMethods();
    private void unitcosttxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitcosttxtKeyReleased

        try {
            String s = qntytxt.getText().trim().replaceAll(",", "");
            String str;
            if(s.equalsIgnoreCase("")){
                qntytxt.setText("");
            } else {
                String s2 = unitcosttxt.getText().trim().replaceAll(",", "");
                if(s2.isEmpty()){
                    
                }else{
                    
//                    if(md.mul(Integer.parseInt(s), Integer.parseInt(s2))>=1000)
//                    {
                        str = md.rupee(Integer.toString(md.mul(Integer.parseInt(s), Integer.parseInt(s2)))).trim();
//                    }
//                    else{
//                        str = Integer.toString(md.mul(Integer.parseInt(s), Integer.parseInt(s2)));
//                    }
//                    qntytxt.setText(md.rupee(s));
                    unitcosttxt.setText(md.rupee(s2));
                    unittottxt.setText(str);
                }
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_unitcosttxtKeyReleased

    private void unitcosttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitcosttxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_unitcosttxtKeyTyped

    private void delete_table_sale_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_table_sale_buttonActionPerformed

        try {
                int[] rows = table_sale.getSelectedRows();
                for(int i = 0; i < rows.length; i++){
                    catelogModelList.remove(rows[i]);
                }
                SaleCatelogTableModel catelogTableModel = new SaleCatelogTableModel(catelogModelList);
                table_sale.setModel(catelogTableModel);
                table_saleVetoableChange(null);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_delete_table_sale_buttonActionPerformed
int tbindex=-1;
    private void edit_table_sale_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_table_sale_buttonActionPerformed
        try {
            if(table_sale.getSelectedRowCount()>0){
                tbindex = table_sale.getSelectedRow();
                saleCatelogModel = catelogModelList.get(tbindex);
                
                itemList.setSelectedValue(saleCatelogModel.getCategoryModel().getProductEntryModel().getProductName().trim(), true);
//                categoryList.setSelectedValue(saleCatelogModel.getCategoryModel().getCategoryName().trim(), true);
                qntytxt.setText(Integer.toString(saleCatelogModel.getTransactionModel().getQnty()));
                unitcosttxt.setText(Integer.toString(saleCatelogModel.getTransactionModel().getUcost()));
                unittottxt.setText(Integer.toString(saleCatelogModel.getTransactionModel().getUtot()));
                catelogModelList.remove(tbindex);
                SaleCatelogTableModel tableModel = new SaleCatelogTableModel(catelogModelList);
                table_sale.setModel(tableModel);
                table_saleVetoableChange(null);
//                DefaultTableModel dml = (DefaultTableModel) table_sale.getModel();
//                dml.removeRow(tbindex);
//                 String cnt = Integer.toString(dml.getRowCount());
                
                
                
            } 
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_edit_table_sale_buttonActionPerformed
    
    private void table_salePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_table_salePropertyChange
//        try {
//            if(table_sale.getRowCount()>0){
//                long tot = 0;
//                for(int i = 0 ; i < table_sale.getRowCount() ; i++){
//                    tot += Long.parseLong(table_sale.getModel().getValueAt(i, 4).toString().replaceAll(",", ""));
//                }
//                ftotal.setText(new Fruit.Common.CommonMethods().rupee(String.valueOf(tot)));
//            }
//            if(table_sale.getSelectedRows().length>0){
//                edit_table_sale_button.setEnabled(true);
//                delete_table_sale_button.setEnabled(true);
//            } else{
//                edit_table_sale_button.setEnabled(false);
//                delete_table_sale_button.setEnabled(false);
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
        try {
                table_saleVetoableChange(evt);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_table_salePropertyChange

    private void table_saleVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_table_saleVetoableChange
        try {
            if(table_sale.getRowCount()>0){
//                System.err.println("sdgdfgdfg");
                long tot = 0;
                for(int i = 0 ; i < table_sale.getRowCount() ; i++){
                    tot += Long.parseLong(table_sale.getModel().getValueAt(i, 4).toString().replaceAll(",", ""));
                }
                
                ftotal.setText(new Fruit.Common.CommonMethods().rupee(String.valueOf(tot)));
                String p = paid.getText().trim();long pa=0,ba=0;
                if(!p.equalsIgnoreCase("")){
                 pa = Long.parseLong(p);
                 ba = tot - pa;
                } else {
                   ba = tot;
                   
                }
                paid.setText(new Fruit.Common.CommonMethods().rupee(String.valueOf(pa)));
                balance.setText(new Fruit.Common.CommonMethods().rupee(String.valueOf(ba)));
            }
            if(table_sale.getSelectedRows().length>0){
                edit_table_sale_button.setEnabled(true);
                delete_table_sale_button.setEnabled(true);
            } else{
                edit_table_sale_button.setEnabled(false);
                delete_table_sale_button.setEnabled(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_table_saleVetoableChange

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed

        try {
            cname.setText("Enter Supplier name");
            itemList.clearSelection();
//            categoryList.clearSelection();
            qntytxt.setText("");
            unitcosttxt.setText("");
            unittottxt.setText("");
            DefaultTableModel dml = new DefaultTableModel(columnNames, 0);
            table_sale.setModel(dml);
            ftotal.setText("");
            paid.setText("");
            balance.setText("");cname.requestFocus();
            trkNo.setText("");
            transName.setText("");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void table_saleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_saleMouseDragged
        try {
            int r = table_sale.getSelectedRowCount();
            if(r>0){
                edit_table_sale_button.setEnabled(true);delete_table_sale_button.setEnabled(true);
            } else { 
                edit_table_sale_button.setEnabled(false);delete_table_sale_button.setEnabled(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_table_saleMouseDragged

    private void table_saleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_saleMouseClicked

        table_saleMouseDragged(evt);
    }//GEN-LAST:event_table_saleMouseClicked
int customerId = 0;

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try {
            if(table_sale.getRowCount()<0){
                JOptionPane.showMessageDialog(null, "No data for transaction..!");
            } else {
            int tot = commonMethods.rupeeToInt(ftotal.getText());
            int pd = commonMethods.rupeeToInt(paid.getText());
            int bl = commonMethods.rupeeToInt(balance.getText());
            
//            System.out.println(" SDFSDF "+this.items.indexOf(this.cname.getText().trim()));
            int cidIn = this.items.indexOf(this.cname.getText().trim());
            
            
            if(cidIn < 0){
                
                JOptionPane.showMessageDialog(null, "Enter Supplier name..!");
                cname.setText("");
                cname.requestFocus();
            } else {
                customerId = customerModelList.get(cidIn).getCsID();
                trxModel = new SaleEntryTrxModel(
                customerId , tot, pd, bl, 0, commonMethods.datesaveformat(entryDate.getDate()));
                InvoiceModel im = new InvoiceModel(
                        1, 1, 1, 1, commonMethods.datesaveformat(entryDate.getDate()), 1, 1, trkNo.getText().trim(),
                        transName.getText().trim(), true);
                InvoiceEntryModel entryModel = new InvoiceEntryModel(im, tot);
                int t_ID = trxDAL.addSupplierTrx(entryModel);
//                System.err.println("T_ID : "+t_ID);
            
                for(int i = 0; i < catelogModelList.size(); i++){
                    SaleTransactionModel saleTransactionModel = new SaleTransactionModel(
                        catelogModelList.get(i).getTransactionModel().getQnty(),
                        catelogModelList.get(i).getTransactionModel().getUcost(),
                        catelogModelList.get(i).getTransactionModel().getUtot(),
                        catelogModelList.get(i).getCategoryModel().getProductEntryModel().getpId(),
                        customerId,t_ID);
                    saleTransactionModel.setSuplierId(customerId);
                    trxDAL.addSupplierTtlTrx(saleTransactionModel);
                
                }
//                customerModelList.clear();
                customerId = 0;
                catelogModelList.clear();
                JOptionPane.showMessageDialog(null, "Transaction successful..!");
                cancelButtonActionPerformed(evt);
            
            
            }
            
//            DefaultTableModel dml = (DefaultTableModel) table_sale.getModel();
            
            
//            for(int i=0; i < dml.getRowCount() ; i++){
//               SaleTransactionModel bean = new SaleTransactionModel(
//                       Integer.parseInt(dml.getValueAt(i, 2).toString()),
//                       Integer.parseInt(dml.getValueAt(i, 3).toString()),
//                       Integer.parseInt(dml.getValueAt(i, 4).toString()), 
//                       Integer.parseInt(dml.getValueAt(i, 1).toString()),
//                       Integer.parseInt(dml.getValueAt(i, 2).toString()),
//                       Integer.parseInt(dml.getValueAt(i, 2).toString())
//               );
               
               
//            }
            
            }
        } catch (Exception e) {
            System.err.println("Exception in sale submitbutton : ");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_submitButtonActionPerformed

    public void keyTyped(){
        
    }
    private void paidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidKeyTyped

        try {
            char c = evt.getKeyChar();
            boolean t = Integer.parseInt(ftotal.getText().trim().replaceAll(",", "")) < Integer.parseInt(balance.getText().trim().replaceAll(",", ""));
            System.out.println(t);
        if (!(Character.isDigit(c) || (c == evt.VK_BACK_SPACE) || c == evt.VK_DELETE ) && t) {
//            JOptionPane.showMessageDialog(null, "enter  only");
            evt.consume();
        } 
        if(c == '0' && paid.getText().trim().equals("")){
//            System.out.println("sdf");
              evt.consume();
            }
        } catch (Exception e) {
            System.err.println("Exception in paidTxt keyTypedEvent");
            e.printStackTrace();
        }
    }//GEN-LAST:event_paidKeyTyped

    private void paidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paidFocusGained
        try {
            if(paid.getText().trim().equals("0")){
                paid.setText("");
            }
        } catch (Exception e) {
            
            e.printStackTrace();
        }
    }//GEN-LAST:event_paidFocusGained

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        try {
            SuplierRegistration.getInstance().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void paidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paidFocusLost
        try {
            if(paid.getText().trim().equals("")){
                paid.setText("0");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_paidFocusLost

    private void paidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidKeyReleased
        try {
            if(!paid.getText().trim().isEmpty()){
            String pa = paid.getText().trim().replaceAll(",", "");
               
               if(Integer.parseInt(pa)>0)
               balance.setText(md.rupee(Integer.toString(md.sub(Integer.parseInt(ftotal.getText().trim().replaceAll(",", "")), Integer.parseInt(pa)))));
               else if(Integer.parseInt(pa) == 0){
                   balance.setText(ftotal.getText().trim());
//                   System.out.println("sad");
               }
            } else {
                balance.setText(ftotal.getText().trim());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_paidKeyReleased

    private void itemListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_itemListValueChanged
        try {
            if(evt.getValueIsAdjusting()){
            ProductEntryModel entryModel = ((ProductEntryModel)this.itemList.getSelectedValue());
            System.out.println("hi1 "+entryModel.getpId());
            updateProductCategoryLisByProduct(entryModel.getpId());
//            List<ProductCategoryModel> categoryModel = ((ProductCategoryModel)this.categoryModel);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_itemListValueChanged

    private void cnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyReleased

        try {
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cnameKeyReleased

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

        try {
            ProductCreate.getInstance().setVisible(true);
        } catch (Exception e) {
            System.err.println("Exception in jLabel10MouseClicked ");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void cnameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_cnameCaretUpdate
cnameKeyReleased(null);
    }//GEN-LAST:event_cnameCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balance;
    private javax.swing.JButton cancelButton;
    private static javax.swing.JTextField cname;
    private javax.swing.JButton delete_table_sale_button;
    private javax.swing.JButton edit_table_sale_button;
    private com.toedter.calendar.JDateChooser entryDate;
    private javax.swing.JTextField ftotal;
    private javax.swing.JList itemList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField paid;
    private javax.swing.JTextField qntytxt;
    private javax.swing.JButton submitButton;
    private javax.swing.JTable table_sale;
    private javax.swing.JTextField transName;
    private javax.swing.JTextField trkNo;
    private javax.swing.JTextField unitcosttxt;
    private javax.swing.JTextField unittottxt;
    // End of variables declaration//GEN-END:variables

    public void updateProductList() {
        DefaultListModel defaultListModel = new DefaultListModel();
//        ListModel listModel = (ListModel) commonMethods.loadProductComboo();
        for(int i=0;i<commonMethods.loadProductComboo().size();i++)
        defaultListModel.addElement(commonMethods.loadProductComboo().get(i));
        this.itemList.setModel(defaultListModel);
        
    }
    public void updateProductCategoryList() {
        DefaultListModel defaultListModel = new DefaultListModel();
//        ListModel listModel = (ListModel) commonMethods.loadProductComboo();
        for(int i=0;i<commonMethods.loadProductCategoryComboo().size();i++)
        defaultListModel.addElement(commonMethods.loadProductCategoryComboo().get(i));
//        this.categoryList.setModel(defaultListModel);
        
    }
    private void updateProductCategoryLisByProduct(int pID) {
        DefaultListModel defaultListModel = new DefaultListModel();
//        ListModel listModel = (ListModel) commonMethods.loadProductComboo();
//        System.out.println("sixe : "+commonMethods.loadProductCategoryCombooByProduct(pID).size());
        for(int i=0;i<commonMethods.loadProductCategoryCombooByProduct(pID).size();i++)
        defaultListModel.addElement(commonMethods.loadProductCategoryCombooByProduct(pID).get(i));
//        this.categoryList.setModel(defaultListModel);
        
    }

    
    
    
    
    
}
