/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Fruit.ui;

import Fruit.test.*;
import Fruit.Common.CommonMethods;
import Fruit.DAL.InvoiceDAL;
import Fruit.DAL.ProductDAL;
import Fruit.Model.InvoiceEntryModel;
import Fruit.Model.InvoiceModel;
import Fruit.Model.ProductCategoryModel;
import Fruit.Model.ProductEntryModel;
import Fruit.Model.RegistrationModel;
import Fruit.Model.SaleCatelogModel;
import Fruit.Model.SaleEntryTrxModel;
import Fruit.Model.SaleTransactionModel;
import Fruit.TableModel.SaleCatelogTableModel;
import java.awt.Color;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raffiuddin
 */
public class InvoiceEntryEdit extends javax.swing.JPanel {

    /**
     * Creates new form InvoiceEntry
     */
    Connection con;
    private Object[] columnNames = {"Items","Category","Quantity","UnitCost","Total"};
    ProductDAL productDAL;
    static Fruit.Common.CommonMethods commonMethods = new CommonMethods();
    Fruit.Model.ProductCategoryModel categoryModel;
    Fruit.Model.SaleEntryTrxModel trxModel ;
    SaleCatelogModel saleCatelogModel;
    ArrayList<SaleCatelogModel> catelogModelList = new ArrayList<>();
    static List<RegistrationModel> supplierModelList = new ArrayList<>();
    RegistrationModel registrationModel;
    public  List<String> items = new ArrayList<>();
    Fruit.test.Test1 test1;
    Fruit.DAL.InvoiceDAL trxDAL = new InvoiceDAL();
    private ArrayList<SaleCatelogModel> catelogModelListdel = new ArrayList<>();
    
    public InvoiceEntryEdit() {
        initComponents();
        entryDate.setDate(new Date());
        updateProductList();
        //updateProductCategoryList();
        table_sale.getTableHeader().setBackground(Color.DARK_GRAY);
        table_sale.getTableHeader().setForeground(Color.white);
        updateDropDown();
        
        
    }
    public JTextField getInvoiceIdComp(){
        return this.invId;
        
    }
    
     public InvoiceEntryEdit(String invoiceId) {
        initComponents();
        entryDate.setDate(new Date());
        updateProductList();
        //updateProductCategoryList();
        table_sale.getTableHeader().setBackground(Color.DARK_GRAY);
        table_sale.getTableHeader().setForeground(Color.white);
        updateDropDown();
        invId.setText(invoiceId);
        // SwingUtilities.invokeLater(null);
    }
    public void updateDropDown(){
        items.clear();
        supplierModelList = commonMethods.getSuppliers();
     if(supplierModelList!=null){
            
         for (RegistrationModel supplierList : supplierModelList) {
             items.add(supplierList.toString());
         }
        
        }
        Test1.setupAutoComplete(cname, (ArrayList<String>) items);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        entryDate = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemList = new javax.swing.JList();
        jPanel14 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        qntytxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        unitcosttxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        unittottxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_sale = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        edit_table_sale_button = new javax.swing.JButton();
        delete_table_sale_button = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        cname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        transName = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        invId = new javax.swing.JTextField();
        invoiceIdSearch = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        trkNo = new javax.swing.JTextField();
        truckNoSearch = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ftotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        paid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        entryDate.setForeground(new java.awt.Color(0, 102, 102));
        entryDate.setDateFormatString("dd/MM/yyyy");
        entryDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jPanel2.setLayout(new java.awt.BorderLayout(0, 5));

        itemList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemList.setForeground(new java.awt.Color(0, 204, 0));
        itemList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Apple", "Orange" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        itemList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        itemList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                itemListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(itemList);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setForeground(new java.awt.Color(159, 128, 35));
        jLabel1.setText("Items                               ");
        jPanel14.add(jLabel1);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/smalladdsym.png"))); // NOI18N
        jLabel10.setToolTipText("Add Product");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel14.add(jLabel10);

        jPanel2.add(jPanel14, java.awt.BorderLayout.PAGE_START);

        jPanel4.add(jPanel2);

        jPanel5.setLayout(new java.awt.GridLayout(1, 4, 5, 0));

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.X_AXIS));

        qntytxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        qntytxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qntytxtKeyReleased(evt);
            }
        });
        jPanel12.add(qntytxt);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" X");
        jPanel12.add(jLabel3);

        jPanel5.add(jPanel12);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        unitcosttxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        unitcosttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unitcosttxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                unitcosttxtKeyTyped(evt);
            }
        });
        jPanel13.add(unitcosttxt);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" =");
        jPanel13.add(jLabel4);

        jPanel5.add(jPanel13);

        unittottxt.setEditable(false);
        unittottxt.setForeground(new java.awt.Color(0, 37, 194));
        unittottxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(unittottxt);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/Actions-list-add-icon.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "Items List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(204, 0, 51)));
        jPanel7.setLayout(new java.awt.BorderLayout(0, 3));

        table_sale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Items", "Category", "Quantity", "UnitCost", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_sale.setToolTipText("Sale Items");
        table_sale.setGridColor(new java.awt.Color(204, 204, 204));
        table_sale.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_saleMouseClicked(evt);
            }
        });
        table_sale.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                table_saleMouseDragged(evt);
            }
        });
        table_sale.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                table_salePropertyChange(evt);
            }
        });
        table_sale.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                table_saleVetoableChange(evt);
            }
        });
        jScrollPane3.setViewportView(table_sale);

        jPanel7.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        edit_table_sale_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db-edit-icon.png"))); // NOI18N
        edit_table_sale_button.setText("Edit");
        edit_table_sale_button.setEnabled(false);
        edit_table_sale_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_table_sale_buttonActionPerformed(evt);
            }
        });
        jPanel8.add(edit_table_sale_button);

        delete_table_sale_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db-remove-icon.png"))); // NOI18N
        delete_table_sale_button.setText("Remove");
        delete_table_sale_button.setEnabled(false);
        delete_table_sale_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_table_sale_buttonActionPerformed(evt);
            }
        });
        jPanel8.add(delete_table_sale_button);

        jPanel7.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        cname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cname.setForeground(new java.awt.Color(235, 46, 46));
        cname.setText("Enter Supplier name");
        cname.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                cnameCaretUpdate(evt);
            }
        });
        cname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnameFocusLost(evt);
            }
        });
        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnameKeyReleased(evt);
            }
        });
        jPanel11.add(cname);

        jLabel12.setText("Transport");

        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.LINE_AXIS));

        jLabel13.setText("Invoice no    ");
        jPanel16.add(jLabel13);
        jPanel16.add(invId);

        invoiceIdSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        invoiceIdSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/search-small.png"))); // NOI18N
        invoiceIdSearch.setToolTipText("Add supplier");
        invoiceIdSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        invoiceIdSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoiceIdSearchMouseClicked(evt);
            }
        });
        jPanel16.add(invoiceIdSearch);

        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        jLabel11.setText("Truck No      ");
        jPanel17.add(jLabel11);
        jPanel17.add(trkNo);

        truckNoSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        truckNoSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/search-small.png"))); // NOI18N
        truckNoSearch.setToolTipText("Add supplier");
        truckNoSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        truckNoSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                truckNoSearchMouseClicked(evt);
            }
        });
        jPanel17.add(truckNoSearch);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entryDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(transName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(entryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transName)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel10.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/shop-cart-apply-icon.png"))); // NOI18N
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel10.add(submitButton);

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/shop-cart-exclude-icon.png"))); // NOI18N
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel10.add(cancelButton);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/data-remove-icon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton2);

        jPanel9.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        jLabel5.setText("Total");
        jPanel9.add(jLabel5);

        ftotal.setEditable(false);
        ftotal.setBackground(new java.awt.Color(255, 255, 255));
        ftotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ftotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel9.add(ftotal);

        jLabel6.setText("Paid");
        jPanel9.add(jLabel6);

        paid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paid.setForeground(new java.awt.Color(255, 0, 51));
        paid.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paidFocusLost(evt);
            }
        });
        paid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paidKeyTyped(evt);
            }
        });
        jPanel9.add(paid);

        jLabel7.setText("Balance");
        jPanel9.add(jLabel7);

        balance.setEditable(false);
        balance.setBackground(new java.awt.Color(255, 255, 255));
        balance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        balance.setForeground(new java.awt.Color(0, 0, 255));
        balance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel9.add(balance);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnameFocusGained
        try {
            if(cname.getText().trim().equalsIgnoreCase("Enter Supplier name")){
                cname.setText("");
            }else {
                
            }
                
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cnameFocusGained
    
    private void cnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnameFocusLost
        try {
            if(cname.getText().trim().equalsIgnoreCase("")){
                cname.setText("Enter Supplier name");
            }else{
                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cnameFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if(itemList.isSelectionEmpty()){
                JOptionPane.showMessageDialog(null, "Please select something in Items List", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);
                itemList.requestFocus();
//            } else if(categoryList.isSelectionEmpty()){
//                JOptionPane.showMessageDialog(null, "Please select Quantity type", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);    
//                categoryList.requestFocus();
            } else if(qntytxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please give Quantity", "Add to Sale", JOptionPane.INFORMATION_MESSAGE);    
                qntytxt.requestFocus();
            } else {
                String item = itemList.getSelectedValue().toString().trim();
//                String itemtype = categoryList.getSelectedValue().toString().trim();
                String qnty = qntytxt.getText().trim().replaceAll(",", "");
                String unitcost = unitcosttxt.getText().trim().replaceAll(",", "");
                String utot = unittottxt.getText().trim().replaceAll(",", "");
                String dt="";
                if(entryDate.getDate() != null)
                 dt = commonMethods.datesaveformat(entryDate.getDate());
                int pId = ((ProductEntryModel)this.itemList.getSelectedValue()).getpId();
//                int catId = ((ProductCategoryModel)this.categoryList.getSelectedValue()).getCatId();
                ProductEntryModel productEntryModel = new ProductEntryModel(
                        item, "", true, dt, pId);
                ProductCategoryModel productCategoryModel = new ProductCategoryModel(
                        "", "", true, dt, 0, 0, productEntryModel);
                SaleTransactionModel transactionModel = new SaleTransactionModel(
                        commonMethods.rupeeToInt(qnty), commonMethods.rupeeToInt(unitcost), commonMethods.rupeeToInt(utot), pId, loadId, invoiceId);
                transactionModel.setLoadId(loadId);
                transactionModel.setSuplierId(customerId);
                SaleCatelogModel saleCatelogModel = new SaleCatelogModel(productCategoryModel, transactionModel,invoiceId);
                
                if(tbindex==-1)
                  catelogModelList.add(saleCatelogModel);
                else
                    catelogModelList.add(tbindex, saleCatelogModel);
                System.out.println("loadid while adding "+saleCatelogModel.getTransactionModel().getLoadId()+" [pid "+saleCatelogModel.getCategoryModel().getProductEntryModel().getpId());
                SaleCatelogTableModel catelogTableModel = new SaleCatelogTableModel(catelogModelList);
                table_sale.setModel(catelogTableModel);

                System.out.println(" dellist size "+catelogModelListdel.size());
                table_saleVetoableChange(null);
//                invoiceId = 0;
                loadId = 0;
                customerId=0;
                tbindex=-1;
                qntytxt.setText("");
                unitcosttxt.setText("");
                unittottxt.setText("");
                itemList.clearSelection();
//                categoryList.clearSelection();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void qntytxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qntytxtKeyReleased

        try {
            unitcosttxtKeyReleased(evt);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_qntytxtKeyReleased
Fruit.Common.CommonMethods md = new Fruit.Common.CommonMethods();
    private void unitcosttxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitcosttxtKeyReleased

        try {
            String s = qntytxt.getText().trim().replaceAll(",", "");
            String str;
            if(s.equalsIgnoreCase("")){
                qntytxt.setText("");
            } else {
                String s2 = unitcosttxt.getText().trim().replaceAll(",", "");
                if(s2.isEmpty()){
                    
                }else{
                    
                str = md.rupee(Integer.toString(md.mul(Integer.parseInt(s), Integer.parseInt(s2)))).trim();
                unitcosttxt.setText(md.rupee(s2));
                unittottxt.setText(str);
                }
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_unitcosttxtKeyReleased

    private void unitcosttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitcosttxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_unitcosttxtKeyTyped

    private void delete_table_sale_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_table_sale_buttonActionPerformed

        try {
                int[] rows = table_sale.getSelectedRows();
                for(int i = 0; i < rows.length; i++){
                    System.out.println(catelogModelList.get(rows[i]).getTransactionModel().getLoadId()+" loadid removed.");
                    catelogModelList.remove(rows[i]);
                }
                SaleCatelogTableModel catelogTableModel = new SaleCatelogTableModel(catelogModelList);
                table_sale.setModel(catelogTableModel);
                table_saleVetoableChange(null);
            System.out.println(" dellist size "+catelogModelListdel.size());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_delete_table_sale_buttonActionPerformed
int tbindex=-1,invoiceId=0,loadId=0;
    private void edit_table_sale_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_table_sale_buttonActionPerformed
        try {
            if(table_sale.getSelectedRowCount()>0){
                tbindex = table_sale.getSelectedRow();
                saleCatelogModel = catelogModelList.get(tbindex);
                Object object = saleCatelogModel.getCategoryModel().getProductEntryModel().getProductName().trim();
                itemList.setSelectedValue(object, true);
//                categoryList.setSelectedValue(saleCatelogModel.getCategoryModel().getCategoryName().trim(), true);
                qntytxt.setText(Integer.toString(saleCatelogModel.getTransactionModel().getQnty()));
                unitcosttxt.setText(Integer.toString(saleCatelogModel.getTransactionModel().getUcost()));
                unittottxt.setText(Integer.toString(saleCatelogModel.getTransactionModel().getUtot()));
                invoiceId = saleCatelogModel.getTransactionModel().getInvoiceId();
                loadId = catelogModelList.get(tbindex).getTransactionModel().getLoadId();
//                System.out.println("load id  : "+loadId);
                catelogModelList.remove(tbindex);
                SaleCatelogTableModel tableModel = new SaleCatelogTableModel(catelogModelList);
                table_sale.setModel(tableModel);
                table_saleVetoableChange(null);
                System.out.println(" dellist size "+catelogModelListdel.size());
            } 
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_edit_table_sale_buttonActionPerformed
    
    private void table_salePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_table_salePropertyChange
//        try {
//            if(table_sale.getRowCount()>0){
//                long tot = 0;
//                for(int i = 0 ; i < table_sale.getRowCount() ; i++){
//                    tot += Long.parseLong(table_sale.getModel().getValueAt(i, 4).toString().replaceAll(",", ""));
//                }
//                ftotal.setText(new Fruit.Common.CommonMethods().rupee(String.valueOf(tot)));
//            }
//            if(table_sale.getSelectedRows().length>0){
//                edit_table_sale_button.setEnabled(true);
//                delete_table_sale_button.setEnabled(true);
//            } else{
//                edit_table_sale_button.setEnabled(false);
//                delete_table_sale_button.setEnabled(false);
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
        try {
                table_saleVetoableChange(evt);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_table_salePropertyChange

    private void table_saleVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_table_saleVetoableChange
        try {
            if(table_sale.getRowCount()>0){
//                System.err.println("sdgdfgdfg");
                long tot = 0;
                for(int i = 0 ; i < table_sale.getRowCount() ; i++){
                    tot += Long.parseLong(table_sale.getModel().getValueAt(i, 4).toString().replaceAll(",", ""));
                }
                
                ftotal.setText(new Fruit.Common.CommonMethods().rupee(String.valueOf(tot)));
                String p = paid.getText().trim();long pa=0,ba=0;
                if(!p.equalsIgnoreCase("")){
                 pa = Long.parseLong(p);
                 ba = tot - pa;
                } else {
                   ba = tot;
                   
                }
                paid.setText(new Fruit.Common.CommonMethods().rupee(String.valueOf(pa)));
                balance.setText(new Fruit.Common.CommonMethods().rupee(String.valueOf(ba)));
            }
            if(table_sale.getSelectedRows().length>0){
                edit_table_sale_button.setEnabled(true);
                delete_table_sale_button.setEnabled(true);
            } else{
                edit_table_sale_button.setEnabled(false);
                delete_table_sale_button.setEnabled(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_table_saleVetoableChange

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed

        try {
            cname.setText("Enter Supplier name");
            itemList.clearSelection();
//            categoryList.clearSelection();
            qntytxt.setText("");
            unitcosttxt.setText("");
            unittottxt.setText("");
            DefaultTableModel dml = new DefaultTableModel(columnNames, 0);
            catelogModelList.clear();
            catelogModelListdel.clear();
          
                    
            table_sale.setModel(dml);
            ftotal.setText("");
            paid.setText("");
            trkNo.setText("");
            invId.setText("");
            balance.setText("");cname.requestFocus();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void table_saleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_saleMouseDragged
        try {
            int r = table_sale.getSelectedRowCount();
            if(r>0){
                edit_table_sale_button.setEnabled(true);delete_table_sale_button.setEnabled(true);
            } else { 
                edit_table_sale_button.setEnabled(false);delete_table_sale_button.setEnabled(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_table_saleMouseDragged

    private void table_saleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_saleMouseClicked

        table_saleMouseDragged(evt);
    }//GEN-LAST:event_table_saleMouseClicked
int customerId = 0;

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try {
            System.out.println(" dellist size "+catelogModelListdel.size());
            if(table_sale.getRowCount()<0){
                JOptionPane.showMessageDialog(null, "No data for transaction..!");
            } else {
            int tot = commonMethods.rupeeToInt(ftotal.getText());
            int pd = commonMethods.rupeeToInt(paid.getText());
            int bl = commonMethods.rupeeToInt(balance.getText());
            
//            System.out.println(" SDFSDF "+this.items.indexOf(this.cname.getText().trim()));
            int cidIn = this.items.indexOf(this.cname.getText().trim());
            
            
            if(cidIn < 0){
                
                JOptionPane.showMessageDialog(null, "Enter Supplier name..!");
                cname.setText("");
                cname.requestFocus();
            } else {
                customerId = supplierModelList.get(cidIn).getCsID();
                System.out.println("invoiceId "+invoiceId);
                trxModel = new SaleEntryTrxModel(
                customerId , tot, pd, bl, 0, commonMethods.datesaveformat(entryDate.getDate()));
                InvoiceModel im = new InvoiceModel(
                        invoiceId, 1, 1, 1, commonMethods.datesaveformat(entryDate.getDate()), 1, 1, trkNo.getText().trim(),
                        transName.getText().trim(), true);
                InvoiceEntryModel entryModel = new InvoiceEntryModel(im, tot);
                int invoiceId = trxDAL.updateSupplierTrx(entryModel);
//                System.err.println("invid : "+invoiceId);
//                System.err.println("T_ID : "+t_ID);
                System.out.println("list size "+catelogModelList.size());
                for(int i = 0; i < catelogModelList.size(); i++){
//                    SaleTransactionModel saleTransactionModel = new SaleTransactionModel(
//                        catelogModelList.get(i).getTransactionModel().getQnty(),
//                        catelogModelList.get(i).getTransactionModel().getUcost(),
//                        catelogModelList.get(i).getTransactionModel().getUtot(),
//                        catelogModelList.get(i).getCategoryModel().getProductEntryModel().getpId(),
//                        catelogModelList.get(i).getTransactionModel().gettId(),invoiceId);
//                        saleTransactionModel.setLoadId(catelogModelList.get(i).getTransactionModel().getLoadId());
                        
                       SaleTransactionModel  saleTransactionModel= catelogModelList.get(i).getTransactionModel();
                       saleTransactionModel.setSuplierId(customerId);
                    if(catelogModelList.get(i).getTransactionModel().getLoadId()==0)
                       trxDAL.addSupplierTtlTrx(saleTransactionModel);
                    else
                       trxDAL.updateSupplierTtlTrx(saleTransactionModel, catelogModelList.get(i).getTransactionModel().getLoadId());
                
                }

                    
                    List<SaleCatelogModel> actualDelList = new ArrayList<>();
                    System.out.println("delList size "+catelogModelListdel.size());
                   for(int delIndex=0; delIndex<catelogModelListdel.size();delIndex++){
                        boolean addToDel = true;
                        SaleCatelogModel delModel = catelogModelListdel.get(delIndex);
                        for(int listIndex=0; listIndex < catelogModelList.size();listIndex++){
                            if(delModel.getTransactionModel().getLoadId()==catelogModelList.get(listIndex).getTransactionModel().getLoadId()){
                            System.out.println("Loadid "+catelogModelListdel.get(delIndex).getTransactionModel().getLoadId());

                             addToDel = false;
                            }
                        }    
                        System.out.println("delIndex "+delIndex+ " " +addToDel);
                        if(addToDel){
                            System.out.print("Loadid going to delete "+delModel.getTransactionModel().getLoadId());
                            actualDelList.add(delModel);
                        }
                    }
                    
                    
                    
                    for(int i=0;i<actualDelList.size();i++){
                        System.out.println("Enter into delete ");
                        trxDAL.deleteSupplierTtlTrx(actualDelList.get(i).getTransactionModel().getLoadId());
                    }
                        
                    
//                }
//                customerModelList.clear();
                catelogModelList.clear();
                catelogModelListdel.clear();
                customerId = 0;
                invoiceId = 0;
                catelogModelList.clear();
                JOptionPane.showMessageDialog(null, "Transaction successful..!");
                cancelButtonActionPerformed(evt);
            
            
            }
            
            
            }
        } catch (Exception e) {
            System.err.println("Exception in sale submitbutton : ");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_submitButtonActionPerformed

    public void keyTyped(){
        
    }
    private void paidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidKeyTyped

        try {
            char c = evt.getKeyChar();
            boolean t = Integer.parseInt(ftotal.getText().trim().replaceAll(",", "")) < Integer.parseInt(balance.getText().trim().replaceAll(",", ""));
            System.out.println(t);
        if (!(Character.isDigit(c) || (c == evt.VK_BACK_SPACE) || c == evt.VK_DELETE ) && t) {
//            JOptionPane.showMessageDialog(null, "enter  only");
            evt.consume();
        } 
        if(c == '0' && paid.getText().trim().equals("")){
//            System.out.println("sdf");
              evt.consume();
            }
        } catch (Exception e) {
            System.err.println("Exception in paidTxt keyTypedEvent");
            e.printStackTrace();
        }
    }//GEN-LAST:event_paidKeyTyped

    private void paidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paidFocusGained
        try {
            if(paid.getText().trim().equals("0")){
                paid.setText("");
            }
        } catch (Exception e) {
            
            e.printStackTrace();
        }
    }//GEN-LAST:event_paidFocusGained

    private void truckNoSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_truckNoSearchMouseClicked
        try {
              String id = trkNo.getText().trim();
            if(id.isEmpty()){
                JOptionPane.showMessageDialog(null, "Enter Truck No..! ");
                trkNo.requestFocus();
            } else if(entryDate.getDate() == null){
                JOptionPane.showMessageDialog(null, "Enter date..! ");
                trkNo.requestFocus();
            } else {
                catelogModelList = idal.getInvoiceByTruckNo(id,commonMethods.datesaveformat(entryDate.getDate()));
                catelogModelListdel = (ArrayList<SaleCatelogModel>) catelogModelList.clone();
                Fruit.TableModel.SaleCatelogTableModel model =new SaleCatelogTableModel(catelogModelList);
                table_sale.setModel(model);
                if(catelogModelList.size()>0){
                cname.setText(catelogModelList.get(0).getCategoryModel().getCategoryNameShort());
                customerId = catelogModelList.get(0).getCategoryModel().getProCatId();
                invId.setText(Integer.toString(catelogModelList.get(0).getTransactionModel().getInvoiceId()));
                invoiceId = (catelogModelList.get(0).getTransactionModel().getInvoiceId());
                
//                entryDate.setDate(java.sql.Date.valueOf(catelogModelList.get(0).getCategoryModel().getProductEntryModel().getProductNameShort()));
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid Truck No/date..!");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_truckNoSearchMouseClicked

    private void paidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paidFocusLost
        try {
            if(paid.getText().trim().equals("")){
                paid.setText("0");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_paidFocusLost

    private void paidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidKeyReleased
        try {
            if(!paid.getText().trim().isEmpty()){
            String pa = paid.getText().trim().replaceAll(",", "");
               
               if(Integer.parseInt(pa)>0)
               balance.setText(md.rupee(Integer.toString(md.sub(Integer.parseInt(ftotal.getText().trim().replaceAll(",", "")), Integer.parseInt(pa)))));
               else if(Integer.parseInt(pa) == 0){
                   balance.setText(ftotal.getText().trim());
//                   System.out.println("sad");
               }
            } else {
                balance.setText(ftotal.getText().trim());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_paidKeyReleased

    private void itemListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_itemListValueChanged
        try {
            if(evt.getValueIsAdjusting()){
            ProductEntryModel entryModel = ((ProductEntryModel)this.itemList.getSelectedValue());
//            System.out.println("hi1 "+entryModel.getpId());
            updateProductCategoryLisByProduct(entryModel.getpId());
//            List<ProductCategoryModel> categoryModel = ((ProductCategoryModel)this.categoryModel);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_itemListValueChanged

    private void cnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyReleased

        try {
            int cidIn = this.items.indexOf(this.cname.getText().trim());
            
//            System.out.println(" sgfg : "+cidIn);
            if(cidIn >= 0){
                
                customerId = supplierModelList.get(cidIn).getCsID();
//                System.out.println("CID : "+customerId);
                
            } 
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cnameKeyReleased

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

        try {
            ProductCreate.getInstance().setVisible(true);
        } catch (Exception e) {
            System.err.println("Exception in jLabel10MouseClicked ");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel10MouseClicked
Fruit.DAL.InvoiceDAL idal = new InvoiceDAL();
Fruit.Common.CommonMethods cm = new CommonMethods();

    private void invoiceIdSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceIdSearchMouseClicked
        try {
            String id = invId.getText().trim();
            if(id.isEmpty()){
                JOptionPane.showMessageDialog(null, "Enter Invoice No..! ");
                invId.requestFocus();
            } else {
                catelogModelList = idal.getInvoiceById(cm.rupeeToInt(id));
                catelogModelListdel = (ArrayList<SaleCatelogModel>) catelogModelList.clone();
                Fruit.TableModel.SaleCatelogTableModel model =new SaleCatelogTableModel(catelogModelList);
                table_sale.setModel(model);
                if(catelogModelList.size()>0){
                    invoiceId = cm.rupeeToInt(id);
                cname.setText(catelogModelList.get(0).getCategoryModel().getCategoryNameShort());
                customerId = catelogModelList.get(0).getTransactionModel().getSuplierId();
//                    System.out.println((catelogModelList.get(0).getCategoryModel().getProductEntryModel().getProductNameShort()));
                entryDate.setDate(java.sql.Date.valueOf(catelogModelList.get(0).getCategoryModel().getProductEntryModel().getProductNameShort()));
//                String dtt = catelogModelList.get(0).getCategoryModel().getProductEntryModel().getProductNameShort();  
//                System.out.println(new Date(dtt));
                trkNo.setText(catelogModelList.get(0).getCategoryModel().getCreted());
                
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid Id/No/date..!");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_invoiceIdSearchMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if(invoiceId!=0){
                int result = trxDAL.deleteSupplierTrx(invoiceId);

                if(result!=0)
                    JOptionPane.showMessageDialog(null, "Deleted successfully..!");
                else {
                    JOptionPane.showMessageDialog(null, "Can't delete..!");
                    
                }
                cancelButtonActionPerformed(evt);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cnameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_cnameCaretUpdate
cnameKeyReleased(null);
    }//GEN-LAST:event_cnameCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balance;
    private javax.swing.JButton cancelButton;
    private static javax.swing.JTextField cname;
    private javax.swing.JButton delete_table_sale_button;
    private javax.swing.JButton edit_table_sale_button;
    private com.toedter.calendar.JDateChooser entryDate;
    private javax.swing.JTextField ftotal;
    private javax.swing.JTextField invId;
    private javax.swing.JLabel invoiceIdSearch;
    private javax.swing.JList itemList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField paid;
    private javax.swing.JTextField qntytxt;
    private javax.swing.JButton submitButton;
    private javax.swing.JTable table_sale;
    private javax.swing.JTextField transName;
    private javax.swing.JTextField trkNo;
    private javax.swing.JLabel truckNoSearch;
    private javax.swing.JTextField unitcosttxt;
    private javax.swing.JTextField unittottxt;
    // End of variables declaration//GEN-END:variables

    public void updateProductList() {
        DefaultListModel defaultListModel = new DefaultListModel();
//        ListModel listModel = (ListModel) commonMethods.loadProductComboo();
        List productList = commonMethods.loadProductComboo();
        for(int i=0; i < productList.size() ;i++)
            defaultListModel.addElement(productList.get(i));
        
        this.itemList.setModel(defaultListModel);
        
    }
    
    public void updateProductCategoryList() {
        DefaultListModel defaultListModel = new DefaultListModel();
        List prodCatList =  commonMethods.loadProductComboo();
        for(int i=0; i < prodCatList.size(); i++)
            defaultListModel.addElement(prodCatList.get(i));
//        this.categoryList.setModel(defaultListModel);
        
    }
    private void updateProductCategoryLisByProduct(int pID) {
        DefaultListModel defaultListModel = new DefaultListModel();
//        ListModel listModel = (ListModel) commonMethods.loadProductComboo();
//        System.out.println("sixe : "+commonMethods.loadProductCategoryCombooByProduct(pID).size());
        for(int i=0;i<commonMethods.loadProductCategoryCombooByProduct(pID).size();i++)
        defaultListModel.addElement(commonMethods.loadProductCategoryCombooByProduct(pID).get(i));
//        this.categoryList.setModel(defaultListModel);
        
    }

    
}
