/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Fruit.ui;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author rafi
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    SimpleDateFormat date_view = new SimpleDateFormat("dd-MM-yyyy");
    SimpleDateFormat date_save = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat date_v = new SimpleDateFormat("dd-MM-yyyy-h-m-ss");
    Date d = new Date();
    String bdt = date_v.format(d);
    String dat = date_view.format(d);
    String dt = date_save.format(d);
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    SimpleDateFormat smp = new SimpleDateFormat("yyyy-MM-dd");
        Date startingDate = null;
        GregorianCalendar gc2 = new GregorianCalendar();
        GregorianCalendar gc1 = new GregorianCalendar();
        //gc.setTime(startingDate);
//     boolean licence = true;   
        static Logger logger = LogManager.getLogger(LoginFrame.class);
        
        {
            System.setProperty("log4configFilej2.configurationFile", "log4j2.xml");
            System.setProperty("configFile", "../Business_Report/config.properties");
        }
    public LoginFrame() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Fruit/Resource/strawberry.png")));
        try {
            
            con = Fruit.Common.DbConnection.getConnection();
//            con.setAutoCommit(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
//        System.out.println(d);
        //gc2.add(Calendar.YEAR, +1);
//        String result = smp.format(gc2.getTime()); 
//     System.out.println("time 2:  "+gc2.getTime() +"\nTime 1: "+gc1.getTime()+" \n"+gc1.getTime().before(gc2.getTime()));
//     licence = gc1.getTime().before(gc2.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pvg = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        pwd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new java.awt.GridLayout(2, 2, 10, 15));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        jLabel1.setText("Privilage");
        jPanel3.add(jLabel1);

        pvg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Admin", "Operator" }));
        jPanel3.add(pvg);

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel2.setForeground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        jLabel2.setText("Password");
        jPanel3.add(jLabel2);
        jPanel3.add(pwd);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton1)
                        .addGap(60, 60, 60)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            pvg.setSelectedIndex(0);
            pwd.setText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {       
//            String sq = "select l.licencedt from licence l WHERE l.licencedt>NOW()";
//            pst =con.prepareStatement(sq);
//            ResultSet rs_li = pst.executeQuery();
//            
//            
//            if(rs_li.next()){
                
            if(pvg.getSelectedIndex()!=0){
                if(!pwd.getText().trim().isEmpty()){
            String p = pvg.getSelectedItem().toString().trim();
            String pd = pwd.getText().trim();
            String sql = "SELECT L_ID,U_NAME,PWD from logindetails where U_NAME like '"+p+"' and PWD like '"+pd+"' ";
                pst = con.prepareStatement(sql);
                rs = pst.executeQuery();
                if(rs.next()){
                    if(rs.getString("U_NAME").equals("Operator")){
                        MainTab.getInstance().setVisible(true);
                        MainTab.jTabbedPane1.remove(3);
                        this.dispose();
                    }else{
                        
                        MainTab.getInstance().setVisible(true);
                        this.dispose();
                    }
                    logger.info("Login sucess..");
                    System.out.println("Sucess");
                } else {
                    JOptionPane.showMessageDialog(this.getRootPane(), "Invalid password !", "Message", JOptionPane.INFORMATION_MESSAGE);    
                    pwd.setText("");
                    pwd.requestFocus();
                }
                } else {
                    JOptionPane.showMessageDialog(this.getRootPane(), "Please enter password", "Message", JOptionPane.INFORMATION_MESSAGE);    
                    pwd.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this.getRootPane(), "Please select privilage", "Message", JOptionPane.INFORMATION_MESSAGE);
                pvg.requestFocus();
            }
//            } else{
//                JFrame lic = new JFrame("License Expired");
//                JLabel lb = new JLabel("<html><b>Your License has 'Expired'");
//                lb.setHorizontalAlignment((int) CENTER_ALIGNMENT);
//                lb.setForeground(Color.red);
//                lic.add(lb);
//                lic.pack();
//                lic.setSize(240, 140);
//                lic.setLocationRelativeTo(null);
//                lic.setVisible(true);
//            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                if(licence){
                    new LoginFrame().setVisible(true);
//                } else {
//                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JComboBox pvg;
    private javax.swing.JPasswordField pwd;
    // End of variables declaration//GEN-END:variables
}
