/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Fruit.ui;

import Fruit.Common.CommonMethods;
import Fruit.DAL.ProductDAL;
import Fruit.Model.ProductCategoryModel;
import Fruit.Model.ProductEntryModel;
import Fruit.TableModel.ProductCategoryTableModel;
import Fruit.TableModel.ProductEntryTableModel;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.Date;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;

/**
 *
 * @author raffiuddin
 */
public class ProductCreate extends javax.swing.JFrame {

    /**
     * Creates new form ProductCreate
     */
    private static final Logger logger = Logger.getLogger(ProductCreate.class);
    private static ProductCreate productCreate = null;
    ProductDAL productDAL = new ProductDAL();
    Fruit.Common.CommonMethods commonMethods = new CommonMethods();
    List<ProductEntryModel> productEntryModels = null;
    ProductEntryModel entryModel = null;
    ProductCategoryModel productCategoryModel = null;
    Entry e = EntryForm.getSaleEntryForm().entry1;
    
    private ProductCreate() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Fruit/Resource/strawberry.png")));
        update_Table_Product();
        update_Table_Product_cat();
        productTable.getTableHeader().setOpaque(false);
        productTable.getTableHeader().setBackground(Color.DARK_GRAY);
        productTable.getTableHeader().setForeground(Color.white);
        catTable.getTableHeader().setOpaque(false);
        catTable.getTableHeader().setBackground(Color.DARK_GRAY);
        catTable.getTableHeader().setForeground(Color.white);
//        proUpdateButton.setOpaque(false);
//        proUpdateButton.setBackground(Color.red);
    }
    
     public static ProductCreate getInstance() {
        return NewSingletonHolder.INSTANCE;
    }

    private boolean checkProctStatus(int pId) {
        try {
           return productDAL.getProdcutStatus(pId);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }
    
    private static class NewSingletonHolder {

        private static final ProductCreate INSTANCE = new ProductCreate();
    }
    
    public static ProductCreate getProductCreateObject(){
        
        if(productCreate == null)
        
        productCreate = new ProductCreate();
        
        else
            productCreate.setState(JFrame.NORMAL);
        return productCreate;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        proName = new javax.swing.JTextField();
        proShortCut = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        proCancelButton = new javax.swing.JButton();
        proUpdateButton = new javax.swing.JButton();
        proDeleteButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        catNAme = new javax.swing.JTextField();
        catShortCut = new javax.swing.JTextField();
        catAddButton = new javax.swing.JButton();
        catCancelButton = new javax.swing.JButton();
        catUpdateButton = new javax.swing.JButton();
        catDeleteButton = new javax.swing.JButton();
        proCombo = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Products");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)), "Products", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(204, 0, 0))); // NOI18N
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Short Cut"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        productTable.setGridColor(new java.awt.Color(204, 204, 204));
        productTable.setRowHeight(18);
        jScrollPane3.setViewportView(productTable);

        jPanel2.add(jScrollPane3);

        jPanel4.setLayout(new java.awt.GridLayout(3, 2, 10, 8));

        proName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        proName.setForeground(new java.awt.Color(0, 153, 0));
        proName.setText("Product ");
        proName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                proNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                proNameFocusLost(evt);
            }
        });
        proName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                proNameKeyReleased(evt);
            }
        });
        jPanel4.add(proName);

        proShortCut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        proShortCut.setForeground(new java.awt.Color(0, 153, 0));
        proShortCut.setText("Product Short Cut");
        proShortCut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                proShortCutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                proShortCutFocusLost(evt);
            }
        });
        proShortCut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                proShortCutKeyReleased(evt);
            }
        });
        jPanel4.add(proShortCut);

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/Actions-list-add-icon.png"))); // NOI18N
        addButton.setText("Add");
        addButton.setOpaque(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel4.add(addButton);

        proCancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/close_cancel.png"))); // NOI18N
        proCancelButton.setText("Cancel");
        proCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proCancelButtonActionPerformed(evt);
            }
        });
        jPanel4.add(proCancelButton);

        proUpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db-edit-icon.png"))); // NOI18N
        proUpdateButton.setText("Update");
        proUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proUpdateButtonActionPerformed(evt);
            }
        });
        jPanel4.add(proUpdateButton);

        proDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db_delete.png"))); // NOI18N
        proDeleteButton.setText("Delete");
        proDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proDeleteButtonActionPerformed(evt);
            }
        });
        jPanel4.add(proDeleteButton);

        jPanel2.add(jPanel4);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)), "Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(204, 0, 0))); // NOI18N
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        catTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Product Short", "Category", "Category Short"
            }
        ));
        catTable.setGridColor(new java.awt.Color(204, 204, 204));
        catTable.setRowHeight(18);
        jScrollPane1.setViewportView(catTable);

        jPanel3.add(jScrollPane1);

        jPanel6.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel5.setLayout(new java.awt.GridLayout(3, 2, 8, 8));

        catNAme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        catNAme.setForeground(new java.awt.Color(0, 153, 0));
        catNAme.setText("Category");
        catNAme.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                catNAmeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                catNAmeFocusLost(evt);
            }
        });
        catNAme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                catNAmeKeyReleased(evt);
            }
        });
        jPanel5.add(catNAme);

        catShortCut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        catShortCut.setForeground(new java.awt.Color(0, 153, 0));
        catShortCut.setText("Category Short Cut");
        catShortCut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                catShortCutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                catShortCutFocusLost(evt);
            }
        });
        catShortCut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                catShortCutKeyReleased(evt);
            }
        });
        jPanel5.add(catShortCut);

        catAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/Actions-list-add-icon.png"))); // NOI18N
        catAddButton.setText("Add");
        catAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catAddButtonActionPerformed(evt);
            }
        });
        jPanel5.add(catAddButton);

        catCancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/close_cancel.png"))); // NOI18N
        catCancelButton.setText("Cancel");
        catCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catCancelButtonActionPerformed(evt);
            }
        });
        jPanel5.add(catCancelButton);

        catUpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db-edit-icon.png"))); // NOI18N
        catUpdateButton.setText("Update");
        catUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catUpdateButtonActionPerformed(evt);
            }
        });
        jPanel5.add(catUpdateButton);

        catDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db-remove-icon.png"))); // NOI18N
        catDeleteButton.setText("Delete");
        catDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catDeleteButtonActionPerformed(evt);
            }
        });
        jPanel5.add(catDeleteButton);

        jPanel6.add(jPanel5, java.awt.BorderLayout.CENTER);

        proCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        proCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                proComboItemStateChanged(evt);
            }
        });
        jPanel6.add(proCombo, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jMenu1.setText("Go To");

        jMenuItem1.setText("Invoice");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void update_Table_Product() {
        
        ProductEntryTableModel medTblMdl = new ProductEntryTableModel();
        
        productTable.setModel(medTblMdl);
        Object[] pro = productDAL.getProductModelList().toArray();
        DefaultComboBoxModel boxModel = new DefaultComboBoxModel(pro);
//        boxModel.insertElementAt("Select", 0);
        
        
        proCombo.setModel(boxModel);
    }

private void update_Table_Product_cat() {
        
        ProductCategoryTableModel medTblMdl = new ProductCategoryTableModel();
        
        catTable.setModel(medTblMdl);
        Object[] pro = productDAL.getProductCatModelList().toArray();
//        DefaultComboBoxModel boxModel = new DefaultComboBoxModel(pro);
//        boxModel.insertElementAt("Select", 0);
        
        
//        proCombo.setModel(boxModel);
    }

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            String pName = proName.getText().trim();
            String pNameShort = proShortCut.getText().trim();
            if(pNameShort.isEmpty() || pNameShort.equalsIgnoreCase("Product Short Cut")){
//                JOptionPane.showMessageDialog(null, "Enter product name shortcut");
//                proShortCut.requestFocus();
                pNameShort = "";System.out.println("dsf");
            } 
            if(pName.isEmpty() || pName.equalsIgnoreCase("Product")){
                JOptionPane.showMessageDialog(null, "Enter product name ");
                proName.requestFocus();
            } else{
                ProductEntryModel entryModel = new ProductEntryModel(
                        pName, pNameShort, true, commonMethods.datesaveformat(new Date()), 1);
                
                
                int rt = productDAL.getProductByName(entryModel);
                if(rt==0){
                productDAL.addProduct(entryModel);
                } else {
                    JOptionPane.showMessageDialog(null, "Product already exists..!");
                }
                
            }
             
            InvoiceFrom.getInstance().invoiceEntry1.updateProductList();
            update_Table_Product();
            
            e.updateProductList();
            proCancelButtonActionPerformed(evt);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void proNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_proNameFocusGained
        try {
            if(proName.getText().trim().equalsIgnoreCase("Product")){ 
            proName.setText("");
            } else {

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_proNameFocusGained

    private void proNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_proNameFocusLost
        try {
            if(proName.getText().trim().equalsIgnoreCase("")){ 
            proName.setText("Product");
            } else {

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_proNameFocusLost

    private void proUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proUpdateButtonActionPerformed
        try {
            int rows[] = productTable.getSelectedRows();
            String pNameShort = "";
            if(proShortCut.getText().trim().isEmpty() || proShortCut.getText().trim().equalsIgnoreCase("Product Short Cut")){
//                JOptionPane.showMessageDialog(null, "Enter product name shortcut");
//                proShortCut.requestFocus();
                pNameShort = "";
            } else{
                pNameShort = proShortCut.getText().trim();
            }
            if(proName.getText().trim().isEmpty() || proName.getText().trim().equalsIgnoreCase("Product")){
                JOptionPane.showMessageDialog(null, "Enter product name ");
                proName.requestFocus();
            } else{
            for(int i=0; i<rows.length; i++){
                entryModel = ((ProductEntryTableModel) productTable.getModel()).getModel(rows[i]);
                entryModel.setProductName(proName.getText().trim());
                entryModel.setProductNameShort(pNameShort);
                
                int rt = productDAL.getProductByName(entryModel);
                if(rt ==0 ){
                    productDAL.updateProduct(entryModel);
                    JOptionPane.showMessageDialog(null, "Product updated..!");
                } else {
                    JOptionPane.showMessageDialog(null, "Product already exists..!");
                }
            }
            }
            update_Table_Product();
            update_Table_Product_cat();
            e.updateProductList();
            InvoiceFrom.getInstance().invoiceEntry1.updateProductList();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_proUpdateButtonActionPerformed

    private void proCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proCancelButtonActionPerformed
        try {
            proName.setText("Product");
            proShortCut.setText("Product Short Cut");
            update_Table_Product();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_proCancelButtonActionPerformed

    private void proDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proDeleteButtonActionPerformed
try {
            int rows[] = productTable.getSelectedRows();
            entryModel = null;
            
                
            
            for(int i=0; i<rows.length; i++){
                entryModel = ((ProductEntryTableModel) productTable.getModel()).getModel(rows[i]);
                if(checkProctStatus(entryModel.getpId())){
                    JOptionPane.showMessageDialog(null, entryModel.getProductName()+" is Active in some invoice/truck.");
                    return;
                }
                //                entryModel.setProductName(proName.getText().trim());
                //                entryModel.setProductNameShort(proShortCut.getText().trim());
                int op = JOptionPane.showConfirmDialog(null, "Want to delete "+entryModel.getProductName()+" ?");
                System.out.println("op "+op);
                if(op == 0){
                    productDAL.deleteProduct(entryModel);
                }
                
            }
            update_Table_Product();
            proCancelButtonActionPerformed(evt);
            e.updateProductList();
            InvoiceFrom.getInstance().invoiceEntry1.updateProductList();
            //JOptionPane.showMessageDialog(null, entryModel.getProductName()+" deleted..!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_proDeleteButtonActionPerformed

    private void proShortCutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_proShortCutFocusGained

        try {
            if(proShortCut.getText().trim().equalsIgnoreCase("Product Short Cut")){
                proShortCut.setText("");
            } else {
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_proShortCutFocusGained

    private void proShortCutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_proShortCutFocusLost
try {
            if(proShortCut.getText().trim().equalsIgnoreCase("Product Short Cut") || proShortCut.getText().trim().equalsIgnoreCase("")){
                proShortCut.setText("Product Short Cut");
            } else {
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_proShortCutFocusLost

    private void catNAmeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_catNAmeFocusGained

        try {
            if(catNAme.getText().trim().equalsIgnoreCase("Category")){
                catNAme.setText("");
            } else {
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_catNAmeFocusGained

    private void catNAmeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_catNAmeFocusLost

        try {
            if(catNAme.getText().trim().equalsIgnoreCase("Category") || catNAme.getText().trim().equalsIgnoreCase("")){
                catNAme.setText("Category");
            } else {
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_catNAmeFocusLost

    private void catShortCutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_catShortCutFocusGained

        try {
            if(catShortCut.getText().trim().equalsIgnoreCase("Category Short Cut")){
                catShortCut.setText("");
            } else {
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_catShortCutFocusGained

    private void catShortCutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_catShortCutFocusLost
         try {
            if(catShortCut.getText().trim().equalsIgnoreCase("Category Short Cut") || catShortCut.getText().trim().equalsIgnoreCase("")){
                catShortCut.setText("Category Short Cut");
            } else {
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_catShortCutFocusLost

    private void catAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catAddButtonActionPerformed
        try {
            if(proCombo.getItemCount() ==0 ){
                JOptionPane.showMessageDialog(null, "Create products!");
            } else {
            int itemId = ((ProductEntryModel)this.proCombo.getSelectedItem()).getpId();
            if(itemId != 0){
                
//                System.out.println(itemId);
                String cat = catNAme.getText().trim();
                String catshort = catShortCut.getText().trim();
                if(catshort.equalsIgnoreCase("Category Short Cut")){
//                     JOptionPane.showMessageDialog(null, "Enter category");
//                     catNAme.requestFocus();
                    catshort = "";
                }
                if(cat.equalsIgnoreCase("Category")){
                     JOptionPane.showMessageDialog(null, "Enter category");
                     catNAme.requestFocus();
                } else{
                    //Same Model class is used for both product and  productcategory entry into database.
                    ProductEntryModel entryModel = new ProductEntryModel(
                            cat, catshort, true, commonMethods.datesaveformat(new Date()), itemId);
                    //Here aggregation technique is used
                    ProductCategoryModel categoryModel = new ProductCategoryModel(
                        cat, catshort, true, commonMethods.datesaveformat(new Date()), 1, 1, entryModel);
                    int rt = productDAL.getProductCatByName(categoryModel);
                    if(rt==0){
                    productDAL.addProductCat(categoryModel);
                    catCancelButtonActionPerformed(evt);
                    e.updateProductCategoryList();
                    } else {
                        JOptionPane.showMessageDialog(null, "Category already exists..!");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Select product");
            }
            }
            update_Table_Product_cat();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_catAddButtonActionPerformed

    private void catCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catCancelButtonActionPerformed

        try {
            update_Table_Product_cat();
            catNAme.setText("Category");
            catShortCut.setText("Category Short Cut");
            proCombo.setSelectedIndex(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_catCancelButtonActionPerformed

    private void catUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catUpdateButtonActionPerformed
        try {
            int rows[] = catTable.getSelectedRows();
            String catshort = catShortCut.getText().trim();
                if(catshort.equalsIgnoreCase("Category Short Cut")){
//                     JOptionPane.showMessageDialog(null, "Enter category");
//                     catNAme.requestFocus();
                    catshort = "";
                }
                if(catNAme.getText().trim().equalsIgnoreCase("Category")){
                     JOptionPane.showMessageDialog(null, "Enter category");
                     catNAme.requestFocus();
                } else {
            for(int i=0; i<rows.length; i++){
                productCategoryModel = ((ProductCategoryTableModel) catTable.getModel()).getModel(rows[i]);
                
                productCategoryModel.setCategoryName(catNAme.getText().trim());
                productCategoryModel.setCategoryNameShort(catshort);
                int id = ((ProductEntryModel)this.proCombo.getSelectedItem()).getpId();
                entryModel = (ProductEntryModel)this.proCombo.getSelectedItem();
                productCategoryModel.setProductEntryModel(this.entryModel);
//                int id = ((ProductEntryModel)this.proCombo.getSelectedItem()).getpId();
//                productCategoryModel.setProCatId(id);
                
                int rt =productDAL.getProductCatByName(productCategoryModel);
                if(rt==0){
                productDAL.updateProductCat(productCategoryModel);
                JOptionPane.showMessageDialog(null, "Category updated..!");
                } else{
                    JOptionPane.showMessageDialog(null, "Category already exists..!");
                }
                    
            }
                }
            update_Table_Product_cat();
            catCancelButtonActionPerformed(evt);
            e.updateProductCategoryList();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_catUpdateButtonActionPerformed

    private void catDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catDeleteButtonActionPerformed
        try {
            int rows[] = catTable.getSelectedRows();
            
            for(int i=0; i<rows.length; i++){
                productCategoryModel = ((ProductCategoryTableModel) catTable.getModel()).getModel(rows[i]);
//                productCategoryModel.setCategoryName(catNAme.getText().trim());
//                productCategoryModel.setCategoryNameShort(proShortCut.getText().trim());
//                int id = ((ProductEntryModel)this.proCombo.getSelectedItem()).getpId();
//                productCategoryModel.setProCatId(id);
                productDAL.deleteProductCat(productCategoryModel);
            }
            update_Table_Product_cat();
            catCancelButtonActionPerformed(evt);
            e.updateProductCategoryList();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_catDeleteButtonActionPerformed

    private void proNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_proNameKeyReleased
        try {
            proName.setText(commonMethods.firstLeterToCap(proName.getText()));
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_proNameKeyReleased

    private void proShortCutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_proShortCutKeyReleased
        try {
            proShortCut.setText(commonMethods.firstLeterToCap(proShortCut.getText()));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_proShortCutKeyReleased

    private void catNAmeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_catNAmeKeyReleased

         try {
            catNAme.setText(commonMethods.firstLeterToCap(catNAme.getText()));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_catNAmeKeyReleased

    private void catShortCutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_catShortCutKeyReleased
try {
            catShortCut.setText(commonMethods.firstLeterToCap(catShortCut.getText()));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_catShortCutKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            InvoiceFrom.getInstance().setVisible(true);
            this.dispose();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void proComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_proComboItemStateChanged
        try {
            if(evt.getItem()==null){
                logger.info("");
            } else {
                System.out.println(evt.getItemSelectable().getSelectedObjects());
            }
        } catch (Exception e) {
            logger.error("Exception in proComboItemStateChanged ",e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_proComboItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProductCreate.getProductCreateObject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton catAddButton;
    private javax.swing.JButton catCancelButton;
    private javax.swing.JButton catDeleteButton;
    private javax.swing.JTextField catNAme;
    private javax.swing.JTextField catShortCut;
    private javax.swing.JTable catTable;
    private javax.swing.JButton catUpdateButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton proCancelButton;
    private javax.swing.JComboBox proCombo;
    private javax.swing.JButton proDeleteButton;
    private javax.swing.JTextField proName;
    private javax.swing.JTextField proShortCut;
    private javax.swing.JButton proUpdateButton;
    private javax.swing.JTable productTable;
    // End of variables declaration//GEN-END:variables
}
