/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Fruit.ui;

import Fruit.Common.DbConnection;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author rafi
 */

public class PWDChange extends javax.swing.JFrame {

    private static PWDChange change = null;
    
            static PWDChange getInstance() {
        try {
            if(change==null)
                change = new PWDChange();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        return change;
    }

    /**
     * Creates new form PWDChange
     */
    SimpleDateFormat date_view = new SimpleDateFormat("dd-MM-yyyy");
    SimpleDateFormat date_save = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat date_v = new SimpleDateFormat("dd-MM-yyyy-h-m-ss");
    Date d = new Date();
    String bdt = date_v.format(d);
    String dat = date_view.format(d);
    String dt = date_save.format(d);
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    private PWDChange createSignUp = null;
    private PWDChange() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Fruit/Resource/strawberry.png")));
        try {
            
            try {
                con = DbConnection.getConnection();
            } catch (Exception ex) {
                Logger.getLogger(PWDChange.class.getName()).log(Level.SEVERE, null, ex);
            }
            con.setAutoCommit(false);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public PWDChange getInstanace(){
        
        if(createSignUp==null) {
            createSignUp = new PWDChange();
        } else {
            this.setState(JFrame.NORMAL);
        }
        return createSignUp;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pr = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pwd2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        oldpwd = new javax.swing.JPasswordField();
        pwd1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Operator", "Admin" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        jLabel2.setText("Privilege");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        jLabel3.setText("Re-Enter New Password");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        jLabel4.setText("Current Password");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        jLabel5.setText("New Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwd1)
                    .addComponent(pr, 0, 123, Short.MAX_VALUE)
                    .addComponent(pwd2)
                    .addComponent(oldpwd))
                .addGap(95, 95, 95))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jButton1)
                .addGap(54, 54, 54)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(oldpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pwd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            pwd2.setText("");
            pr.setSelectedIndex(0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if(pr.getSelectedIndex()!=0){
                if(!oldpwd.getText().trim().isEmpty()){
                    if(!pwd1.getText().trim().isEmpty()){
                if(!pwd2.getText().trim().isEmpty()){
                    
                String p = pr.getSelectedItem().toString();
                String Oldpwd = oldpwd.getText().trim();
                String pwd = pwd2.getText().trim();
                String pwdf = pwd1.getText().trim();
                if(pwd.equals(pwdf)){
                String sql = "SELECT L_id from logindetails where U_NAME like '"+p+"' and pwd like '"+Oldpwd+"'";
                pst = con.prepareStatement(sql);
                rs = pst.executeQuery();
                if(rs.next()){
                    int cf = JOptionPane.showConfirmDialog(this.getRootPane(), "Are you want to change password", "Message", JOptionPane.INFORMATION_MESSAGE);    
                    if(cf == 0){
                        String sqlc = "UPDATE logindetails l SET l.pwd = '"+pwdf+"' WHERE l.L_id ="+rs.getInt("L_id");
                        pst = con.prepareStatement(sqlc);
                        int b = pst.executeUpdate();
                        if(b > 0){
                            con.commit();
//                            jButton2ActionPerformed(evt);
                            JOptionPane.showMessageDialog(this.getRootPane(), p+" Password changed Successfully", "Message", JOptionPane.INFORMATION_MESSAGE);    
                            this.dispose();
                        }else{
//                            JOptionPane.showMessageDialog(this.getRootPane(), "Try Again ", "Message", JOptionPane.INFORMATION_MESSAGE);    
                        }
                        
                    }
                } else {
                   JOptionPane.showMessageDialog(this.getRootPane(), "Invalid password", "Message", JOptionPane.INFORMATION_MESSAGE);     
                   oldpwd.setText("");
                   oldpwd.requestFocus();
                } 
                }else{
                    JOptionPane.showMessageDialog(this.getRootPane(), "New password didn't match", "Message", JOptionPane.INFORMATION_MESSAGE);     
                    pwd1.setText("");pwd2.setText("");pwd1.requestFocus();
                }
                } else {
                 JOptionPane.showMessageDialog(this.getRootPane(), "Please Re-Enter new password", "Message", JOptionPane.INFORMATION_MESSAGE);    
                 pwd2.setText("");
                 pwd2.requestFocus(); 
                }
                    }else{
                      
                    JOptionPane.showMessageDialog(this.getRootPane(), "Please enter new password", "Message", JOptionPane.INFORMATION_MESSAGE);    
                    pwd1.requestFocus();pwd1.setText("");
                    }
            } else {
                JOptionPane.showMessageDialog(this.getRootPane(), "Please enter current password", "Message", JOptionPane.INFORMATION_MESSAGE);        
                oldpwd.requestFocus();oldpwd.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this.getRootPane(), "Please select privilage", "Message", JOptionPane.INFORMATION_MESSAGE);
                pr.requestFocus();
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        finally {
            
            DbConnection.closeConnection(con);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PWDChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PWDChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PWDChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PWDChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PWDChange().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField oldpwd;
    private javax.swing.JComboBox pr;
    private javax.swing.JPasswordField pwd1;
    private javax.swing.JPasswordField pwd2;
    // End of variables declaration//GEN-END:variables
}
