/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Fruit.ui;

import Fruit.Common.CommonMethods;
import Fruit.DAL.ReportDAL;
import Fruit.ReportModel.BalanceModel;
import Fruit.TableModel.SaleReportTableModel;
import com.User.SaleBean;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Raffiuddin
 */
public class SaleReport extends javax.swing.JFrame {

    /**
     * Creates new form SaleReport
     */
    Fruit.DAL.ReportDAL reportDAL = new ReportDAL();
    List<BalanceModel> saleList = new ArrayList<>();
    private static SaleReport saleReport = null;
    private SaleReport() {
        initComponents();
        jTable1.getTableHeader().setBackground(Color.DARK_GRAY);
        jTable1.getTableHeader().setForeground(Color.white);
//        jTable1.getColumnModel().getColumn(0).setMaxWidth(45);
        upDateTaxes();
        trkTxt.requestFocus();
        jDateChooser1.setDate((new Date()));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Fruit/Resource/strawberry.png")));
              
    }
    public static SaleReport getInstance(){
        if(saleReport==null)
            saleReport = new SaleReport();
        return saleReport;
    }
    private void upDateTaxes(){
        ReportDAL aL = new ReportDAL();
        Object[] l = aL.getTaxes().toArray();
        DefaultComboBoxModel newModel = new DefaultComboBoxModel(l);
        newModel.insertElementAt("Select", 0);
         newModel.setSelectedItem("Select");
        jComboBox1.setModel(newModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        trkTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        amt = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        editQntity = new javax.swing.JTextField();
        editParticulars = new javax.swing.JTextField();
        editRate = new javax.swing.JTextField();
        editTotsl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sale report with taxes");

        jDateChooser1.setDateFormatString("dd/MM/yyyy");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Items", "Quantity", "Unit Cost", "Total"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setRowHeight(18);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setLayout(new java.awt.GridLayout(5, 1, 10, 10));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "%", "Lorry hire", "Cooli", "Cash", "Kata Cash", "AMC" }));
        jPanel2.add(jComboBox1);
        jPanel2.add(amt);

        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton5.setText("Report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridLayout(3, 2, 3, 3));

        jButton10.setText("Add");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10);

        jButton6.setText("Edit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);

        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);

        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);

        jButton9.setText("Cancel");
        jPanel3.add(jButton9);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        editQntity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editQntityKeyReleased(evt);
            }
        });

        editRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editRateKeyReleased(evt);
            }
        });

        editTotsl.setEditable(false);

        jLabel1.setText("Quantity");

        jLabel2.setText("Unit Cost");

        jLabel3.setText("Total");

        jLabel4.setText("Particulars");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(editParticulars, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(editQntity, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(editRate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(editTotsl, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel4))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editParticulars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editQntity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editTotsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(trkTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(trkTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
Fruit.Common.CommonMethods cm = new CommonMethods();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if(trkTxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Enter Truck no..!");
                trkTxt.requestFocus();
            } else if(jDateChooser1.getDate()==null){
            JOptionPane.showMessageDialog(null, "Enter Date..!");
            jDateChooser1.requestFocus();
            } else {
                String dt1=null,dt2=null;
                if(jDateChooser1.getDate()!=null)
                    dt1 = cm.datesaveformat(jDateChooser1.getDate());
//                if(jDateChooser2.getDate()!=null)
//                    dt2 = cm.datesaveformat(jDateChooser2.getDate());
                saleList.clear();
            saleList = reportDAL.getLoadReportPricewise(trkTxt.getText().trim(),dt1);
            if(saleList.size()>0){
            List<BalanceModel> saleList1 = reportDAL.getLoadTaxes(saleList.get(0).getSno());
            
            for(BalanceModel bm: saleList1){
//                if(bm.getName().equalsIgnoreCase("expenditure")){
//                  long  at = sumTable();
//                    System.out.println("ds s : "+at);
//                    long a = at/100;
//                    at = a*cm.rupeeToInt(bm.getCity());
//                    bm.setCity(String.valueOf(at));
//                }
                saleList.add(bm);
            }
//            System.out.println("gsdf " +saleList1.size());
            SaleReportTableModel tableModel = new SaleReportTableModel(saleList);
//            System.out.println(tableModel.getRowCount());
            jTable1.setModel(tableModel);
            } else {
                jTable1.setModel(new DefaultTableModel());
                JOptionPane.showMessageDialog(null, "No date..!");
            }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
Fruit.Common.CommonMethods cm1  = new  CommonMethods();
    public long sumTable(){
//           System.out.println("Sum : "+jTable1.getRowCount());
        long sum = 0;
    for(int i=0;i<jTable1.getRowCount();i++){
//        if(jTable1.getValueAt(i, (jTable1.getColumnCount()-1))!=null){
        sum += cm.rupeeToInt(jTable1.getValueAt(i, (jTable1.getColumnCount()-1)).toString());
//            System.out.println("Sum : "+sum);
//        }
    }
    return sum;
    
}
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            if(jComboBox1.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(null, "Select some thing");
            } else {
            int txId = ((BalanceModel)this.jComboBox1.getSelectedItem()).getSno();
            if(txId!=0){
                String amt = this.amt.getText().trim().replaceAll(",", "");
               if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("expenditure")){
                 int gr = tableSum();
                  amt = Integer.toString((gr/100)*Integer.parseInt(amt));
               } 
//            String amt = this.amt.getText().trim().replaceAll(",", "");
            reportDAL.addLoadTax(saleList.get(0).getSno(), txId, cm.datesaveformat(new Date()), Integer.parseInt(amt));
               
            jButton1ActionPerformed(evt);
            jButton2ActionPerformed(evt);
            
            } 
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed
private int tableSum(){
    int sm=0;
    for(int i=0;i<jTable1.getRowCount();i++){
      sm+=Integer.parseInt(jTable1.getValueAt(i, 3).toString().trim().replaceAll(",", ""));
    }
        return sm;
    
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            int id = ((SaleReportTableModel)this.jTable1.getModel()).getModel(jTable1.getSelectedRow()).getSno();
            if(id!=0){
               reportDAL.deleteLoadTax(id);
               jButton1ActionPerformed(evt);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
             if(saleList.size()>0){
                  List<SaleBean> bean = new ArrayList<>();
                  for(int i=0;i<saleList.size();i++){
                      if(!saleList.get(i).getBalance().equalsIgnoreCase("")){
                      SaleBean sb= new SaleBean(
                              0,
                              null,
                              null,
                              saleList.get(i).getName(),
                              null,
                              saleList.get(i).getCity(),
                              saleList.get(i).getMobile(),
                              
                              saleList.get(i).getBalance());
                      bean.add(sb);
                      }
                  }
                  
                          
                  Map m = new HashMap();
                  List<BalanceModel> saleList1 = reportDAL.getLoadTaxes(saleList.get(0).getSno());
                  List<BalanceModel> add = reportDAL.getInvDtls(saleList.get(0).getSno());
                  System.out.println(saleList1.size());
                  if(add.size()>0){
                  m.put("invdt", add.get(0).getMobile());
                  m.put("sp", add.get(0).getName());
                  m.put("qty", add.get(0).getSno());
                  }
                  m.put("trk", trkTxt.getText().trim());
                  m.put("gr", cm.rupee(String.valueOf(sumTable())));
                  int ftot = 0;
                  for(BalanceModel bm: saleList1){
                      ftot+=cm.rupeeToInt(bm.getCity());
                      if(bm.getName().trim().equalsIgnoreCase("expenditure".trim()))
                      {
                          m.put("exp", cm.rupeeToInt(bm.getCity()));System.out.println(bm.getName() +" "+bm.getCity());}
                      else {
                          if(m.get("exp")==null)
                          m.put("exp", 0);}
                      if(bm.getName().equalsIgnoreCase("Lorry hire"))
                      {
                          m.put("hire", cm.rupeeToInt(bm.getCity()));System.out.println(bm.getName() +" "+bm.getCity());}
                      else {
                          if(m.get("hire")==null)
                          m.put("hire", 0);}
                      if(bm.getName().equalsIgnoreCase("cooli"))
                      {
                          m.put("cooli", cm.rupeeToInt(bm.getCity()));System.out.println(bm.getName() +" "+bm.getCity());}
                      else {
                          if(m.get("cooli")==null)
                          m.put("cooli", 0);}
                      if(bm.getName().equalsIgnoreCase("cash"))
                      {
                          m.put("cash", cm.rupeeToInt(bm.getCity()));System.out.println(bm.getName() +" "+bm.getCity());}
                      else {
                          if(m.get("cash")==null)
                          m.put("cash", 0);}
                      if(bm.getName().equalsIgnoreCase("kata cash"))
                      {
                          m.put("kata", cm.rupeeToInt(bm.getCity()));System.out.println(bm.getName() +" "+bm.getCity());}
                      else {
                          if(m.get("kata")==null)
                          m.put("kata", 0);}
                      if(bm.getName().equalsIgnoreCase("amc"))
                      {
                          m.put("amc", cm.rupeeToInt(bm.getCity()));System.out.println(bm.getName() +" "+bm.getCity());}
                      else {
                          if(m.get("amc")==null)
                          m.put("amc", 0);}
                      
                  }
                  m.put("ftot", ftot);
                  System.out.println(m.values());
          JRBeanCollectionDataSource beanCollectionDataSource = new JRBeanCollectionDataSource(bean);
      
            
            JasperDesign design = JRXmlLoader.load("Business_Report\\saleDetailgroupBycost.jrxml");
                    JasperReport jasperReport = JasperCompileManager.compileReport(design);
                    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, m, beanCollectionDataSource);
                    JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
                    jasperViewer.setVisible(true);
            
            
             }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            jComboBox1.setSelectedIndex(0);
            amt.setText("");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
//            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            SaleReportTableModel model = (SaleReportTableModel) jTable1.getModel();
            
            int index = jTable1.getSelectedRow();
            saleList.remove(model.getModel(index));
            SaleReportTableModel model1 = new SaleReportTableModel(saleList);
            
            jTable1.setModel(model1);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton8ActionPerformed
int index = -1;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
try {
//            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            SaleReportTableModel model = (SaleReportTableModel) jTable1.getModel();
            
             index = jTable1.getSelectedRow();
            BalanceModel mda = model.getModel(index);
//            SaleReportTableModel model1 = new SaleReportTableModel(saleList);
//            
//            jTable1.setModel(model1);
            editParticulars.setText(mda.getName());
            editQntity.setText(mda.getCity());
            editRate.setText(mda.getMobile());
            editTotsl.setText(mda.getBalance());
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed
Fruit.Common.CommonMethods md = new Fruit.Common.CommonMethods();
    private void editQntityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editQntityKeyReleased
   try {
            String s = editQntity.getText().trim().replaceAll(",", "");
            String str;
            if(s.equalsIgnoreCase("")){
                editQntity.setText("");
            } else {
                String s2 = editRate.getText().trim().replaceAll(",", "");
                if(s2.isEmpty()){
                    
                }else{
                    
//                    if(md.mul(Integer.parseInt(s), Integer.parseInt(s2))>=1000)
//                    {
                        str = md.rupee(Integer.toString(md.mul(Integer.parseInt(s), Integer.parseInt(s2)))).trim();
//                    }
//                    else{
//                        str = Integer.toString(md.mul(Integer.parseInt(s), Integer.parseInt(s2)));
//                    }
//                    qntytxt.setText(md.rupee(s));
                    editRate.setText(md.rupee(s2));
                    editTotsl.setText(str);
                }
                
            }
   }catch(Exception e){
       e.printStackTrace();
   }
    }//GEN-LAST:event_editQntityKeyReleased

    private void editRateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editRateKeyReleased
        
        editQntityKeyReleased(evt);
        
    }//GEN-LAST:event_editRateKeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            
            SaleReportTableModel model = (SaleReportTableModel) jTable1.getModel();
//            
//             index = jTable1.getSelectedRow();
            
            BalanceModel mda = model.getModel(index);
            mda.setName(editParticulars.getText());
            mda.setCity(editQntity.getText());
            mda.setMobile(editRate.getText());
            mda.setBalance(editTotsl.getText());
            saleList.remove(index);
            saleList.add(index, mda);
            SaleReportTableModel model1 = new SaleReportTableModel(saleList);
            
            jTable1.setModel(model1);
            index = -1;
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            SaleReportTableModel model = (SaleReportTableModel) jTable1.getModel();
//            
//             index = jTable1.getSelectedRow();
            
            BalanceModel mda = model.getModel(index);
            mda.setName(editParticulars.getText());
            mda.setCity(editQntity.getText());
            mda.setMobile(editRate.getText());
            mda.setBalance(editTotsl.getText());
            saleList.remove(index);
            
                saleList.add(0, mda);
            
            SaleReportTableModel model1 = new SaleReportTableModel(saleList);
            
            jTable1.setModel(model1);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaleReport.getInstance().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amt;
    private javax.swing.JTextField editParticulars;
    private javax.swing.JTextField editQntity;
    private javax.swing.JTextField editRate;
    private javax.swing.JTextField editTotsl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField trkTxt;
    // End of variables declaration//GEN-END:variables
}
