/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Fruit.ui;

import Fruit.Common.CommonMethods;
import Fruit.DAL.InvoiceReportDAL;
import Fruit.DAL.TrxDAL;
import Fruit.Model.InvoiceReportModel;
import Fruit.Model.RegistrationModel;
import Fruit.TableModel.DetailedInvoiceReportTableModel;
import Fruit.test.Test1;
import static Fruit.ui.InvoiceEntry.commonMethods;
import com.User.SaleBean;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author raffiuddin
 */
public class StockDetails extends javax.swing.JFrame {
    private int customerId;
    Fruit.Common.CommonMethods cm = new CommonMethods();
    List<RegistrationModel> customerModelList = new ArrayList<>();
    Fruit.DAL.InvoiceReportDAL reportDAL = new InvoiceReportDAL();
    List<String> items = new ArrayList<>();
    private static StockDetails stockDetails = null;
    Fruit.test.Test1 test1;
    /**
     * Creates new form StockDetails
     */
    public StockDetails() {
        initComponents();
        cname.requestFocus();
         dat2.setDate(new Date());
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Fruit/Resource/strawberry.png")));
        updateDropDown();
    }
    
    public static StockDetails getInstance(){
        if(stockDetails == null) {
            stockDetails = new StockDetails();
        }
        return stockDetails;
    }
    public void updateDropDown(){
        items.clear();
     if(commonMethods.getSuppliers()!=null){
            customerModelList = commonMethods.getSuppliers();
         for (RegistrationModel customerModelList1 : customerModelList) {
             items.add(customerModelList1.toString());
         }
        
        }
        Test1.setupAutoComplete(cname, (ArrayList<String>) items);   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        discountTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        cname = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dat1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        dat2 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SupplierWise Stock");

        discountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Date", "Amount", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        discountTable.setRowHeight(20);
        discountTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(discountTable);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Name", "Truck" }));
        jPanel3.add(jComboBox2);

        cname.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                cnameCaretUpdate(evt);
            }
        });
        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnameKeyReleased(evt);
            }
        });
        jPanel3.add(cname);

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/search-small.png"))); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel3.add(searchButton);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        dat1.setDateFormatString("dd-MM-yyyy");
        jPanel2.add(dat1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("-");
        jPanel2.add(jLabel1);

        dat2.setDateFormatString("dd-MM-yyyy");
        jPanel2.add(dat2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "InActive" }));
        jPanel2.add(jComboBox1);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setText("Detail Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jButton3.setText("Delete");
        jButton3.setToolTipText("Delete only if sold=0");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);

        jButton2.setText("Update Status");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel2, jPanel3});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyReleased

        int cidIn = this.items.indexOf(this.cname.getText().trim());

        System.out.println(" sgfg : "+cidIn);
        if(cidIn >= 0){

            customerId = customerModelList.get(cidIn).getCsID();
        }
    }//GEN-LAST:event_cnameKeyReleased

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try {
            //            if(customerId!=0){
                //                List<DiscountModel> dm = discountDAL.getPrev_Balance(customerId, null, null);
                //                Fruit.TableModel.Discount_Damage_PreBalanceTableModel ddpbtm = new Discount_Damage_PreBalanceTableModel(dm);
                //                discountTable.setModel(ddpbtm);
                //                discountTable.getColumnModel().getColumn(0).setMaxWidth(45);

                //            }
            String dt1=null,dt2=null;
            if(dat1.getDate()!=null)
            dt1 = cm.datesaveformat(dat1.getDate());
            if(dat2.getDate()!=null)
            dt2 = cm.datesaveformat(dat2.getDate());
            String st = "false";
            if(jComboBox1.getSelectedIndex()==0){
                st = "true";
            }
            List<InvoiceReportModel> irms = new ArrayList<>();
            if(jComboBox2.getSelectedIndex()==0)
                irms = reportDAL.getTotalInvoiceSupplerWise(dt1, dt2, st, customerId);
            else
                irms = reportDAL.getTotalInvoiceSupplerWise(dt1, dt2, st, cname.getText().trim());
            Fruit.TableModel.DetailedInvoiceReportTableModel dirtm = new DetailedInvoiceReportTableModel(irms);
            discountTable.setModel(dirtm);
            discountTable.getColumnModel().getColumn(0).setMaxWidth(25);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if(discountTable.getSelectedRowCount()>0){
                InvoiceReportModel irm = ((DetailedInvoiceReportTableModel)this.discountTable.getModel()).getModel(discountTable.getSelectedRow());
                List<SaleBean> list = reportDAL.getTrkDetails(irm);

                if(list.size()>0){
                    JRBeanCollectionDataSource beanCollectionDataSource = new JRBeanCollectionDataSource(list);
                    Map m = new HashMap();
                    m.put("sup", irm.getName());
                    m.put("v_No", irm.getV_No());
                    m.put("stockcame", irm.getStock());
                    m.put("sold", irm.getSold());
                    m.put("bal", irm.getBalace());
                    m.put("dt", irm.getInvoiceDate());

                    try {
                        JasperDesign design = JRXmlLoader.load("Business_Report\\report1.jrxml");
                        JasperReport jasperReport = JasperCompileManager.compileReport(design);
                        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, m, beanCollectionDataSource);
                        JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
                        jasperViewer.setVisible(true);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "No data..!");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
Fruit.DAL.TrxDAL aL = new TrxDAL();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            if(discountTable.getSelectedRowCount()>0){
                int ldID= ((DetailedInvoiceReportTableModel)this.discountTable.getModel()).getModel(discountTable.getSelectedRow()).getLoadID();
                aL.setLoadStatus(ldID);
                searchButtonActionPerformed(evt);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cnameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_cnameCaretUpdate
        cnameKeyReleased(null);
    }//GEN-LAST:event_cnameCaretUpdate

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if(discountTable.getSelectedRowCount()>0 ){
                String Id = ((DetailedInvoiceReportTableModel)this.discountTable.getModel()).getModel(discountTable.getSelectedRow()).getInvoiceID();
//                if(sold==0){
//                    int ldID= ((DetailedInvoiceReportTableModel)this.discountTable.getModel()).getModel(discountTable.getSelectedRow()).getLoadID();
//                    aL.setLoadStatus(ldID);
//                    searchButtonActionPerformed(evt);
                    InvoiceEditForm editForm = new  InvoiceEditForm(Id);
                   // editForm.invoiceEntryEdit1 = new InvoiceEntryEdit(Id);
                    //System.out.println("Id to"+Id);
                    //editForm.invoiceEntryEdit1=new InvoiceEntryEdit(Id);
                    editForm.setVisible(true);
//                }else{
//                    JOptionPane.showMessageDialog(null, "Not eligible for Delete. Because sold = "+sold);
//                }
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cname;
    private com.toedter.calendar.JDateChooser dat1;
    private com.toedter.calendar.JDateChooser dat2;
    private javax.swing.JTable discountTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
