/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Fruit.ui;

import Fruit.Common.CommonMethods;
import Fruit.DAL.SupplierDAL;
import Fruit.Model.RegistrationModel;
import Fruit.TableModel.CustomerEditTableModel;
import Fruit.test.Test1;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Raffiuddin
 */
public class SupplierEdit extends javax.swing.JFrame {

    /**
     * Creates new form SupplierEdit
     */
     List<String> items = new ArrayList<>();
    Fruit.Common.CommonMethods commonMethods = new CommonMethods();
    private List<RegistrationModel> customerModelList;
    RegistrationModel model ;
    private int customerId = 0;
    private static Object object = new Object();
    SupplierDAL cdal = new SupplierDAL();
    private static SupplierEdit supplierEdit =null;
    
    public static SupplierEdit getInstance(){
        if(supplierEdit==null){
            synchronized(object){
                if(supplierEdit==null)
                    supplierEdit = new SupplierEdit();
            }
        }
        return supplierEdit;
    }
    public SupplierEdit() {
        initComponents();
        cname.requestFocus();
        updateDropDown();
        discountTable.getTableHeader().setBackground(Color.DARK_GRAY);
        discountTable.getTableHeader().setForeground(Color.white);
        discountTable.getColumnModel().getColumn(0).setMaxWidth(30);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Fruit/Resource/strawberry.png")));
    }
    public void updateDropDown(){
        items.clear();
     if(commonMethods.getSuppliers()!=null){
          customerModelList = commonMethods.getSuppliers();
         for (RegistrationModel customerModelList1 : customerModelList) {
             items.add(customerModelList1.toString());
         }
        
        }
        Test1.setupAutoComplete(cname, (ArrayList<String>) items);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        discountTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        plotNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pinNo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Supplier Details");

        discountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Name", "City", "Mobile", "Contact No", "H.No", "State", "Pin No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        discountTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(discountTable);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db-edit-icon.png"))); // NOI18N
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel6.add(editButton);

        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db-updat.jpg"))); // NOI18N
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel6.add(updateButton);

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/db-remove-icon.png"))); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel6.add(deleteButton);

        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/refresh-1.png"))); // NOI18N
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel6.add(resetButton);

        jPanel7.setLayout(new java.awt.GridLayout(4, 4, 5, 10));

        jLabel1.setText("Name");
        jPanel7.add(jLabel1);

        name.setForeground(new java.awt.Color(0, 0, 255));
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });
        jPanel7.add(name);

        jLabel3.setText("City");
        jPanel7.add(jLabel3);
        jPanel7.add(city);

        jLabel4.setText("Mobile");
        jPanel7.add(jLabel4);

        mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobileKeyTyped(evt);
            }
        });
        jPanel7.add(mobile);

        jLabel5.setText("Contact No");
        jPanel7.add(jLabel5);
        jPanel7.add(cNo);

        jLabel6.setText("H.No");
        jPanel7.add(jLabel6);
        jPanel7.add(plotNo);

        jLabel7.setText("State");
        jPanel7.add(jLabel7);
        jPanel7.add(state);

        jLabel8.setText("Pin No.");
        jPanel7.add(jLabel8);
        jPanel7.add(pinNo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        jLabel2.setText("Name");
        jPanel3.add(jLabel2);

        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnameKeyReleased(evt);
            }
        });
        jPanel3.add(cname);

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fruit/Resource/search-small.png"))); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel3.add(searchButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        try {
         
            if(discountTable.getSelectedRow()!=-1){
               
//                System.out.println(discountTable.getValueAt(discountTable.getSelectedRow(), 1));

              
                model = ((CustomerEditTableModel)this.discountTable.getModel()).getModel(discountTable.getSelectedRow());
                name.setText(model.getName());
                city.setText(model.getCity());
                mobile.setText(model.getMobile());
                cNo.setText(model.getMobile2());
                state.setText(model.getState());
                plotNo.setText(model.getPlotNo());
                pinNo.setText(Integer.toString(model.getPinNo()));
//                upReason.setSelectedItem((Object)model.getNativ());

             
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
//            if(upReason.getSelectedIndex()==0){
//                JOptionPane.showMessageDialog(null, "Select Local / Non Local");
//                upReason.requestFocus();
//            } else {
            if(name.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Enter Supplier Name..?");
                name.requestFocus();
            } else if(mobile.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Enter mobile number..?");
                mobile.requestFocus();
            }
                model.setName(name.getText().trim());
                model.setCity(city.getText().trim());
                model.setMobile(mobile.getText().trim());
                model.setMobile2(cNo.getText().trim());
                model.setPlotNo(plotNo.getText().trim());
                model.setState(state.getText().trim());
                model.setPinNo(Integer.parseInt(pinNo.getText().trim()));
//                model.setNativ(upReason.getSelectedItem().toString().trim());
                
                System.out.println(model.getCity()+" state = "+model.getState());
                cdal.updateSupplier(model);

//                searchButtonActionPerformed(evt);
                resetButtonActionPerformed(evt);
                model = null;
//            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            if(discountTable.getSelectedRowCount()>0){
                int[] rindex = discountTable.getSelectedRows();
                for(Integer i:rindex){
                    model = ((CustomerEditTableModel)this.discountTable.getModel()).getModel(i);
                    model.setActive(false);
                    cdal.deleteSupplier(model);
                    //                discountDAL.updateAfterDiscount_Damage(upbal, customerId, model.getId());
                }
                searchButtonActionPerformed(evt);
                resetButtonActionPerformed(evt);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        try {
            name.setText("");
            cNo.setText("");
            city.setText("");
            pinNo.setText("");
            plotNo.setText("");
            mobile.setText("");
            state.setText("");

//            upReason.setSelectedIndex(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_resetButtonActionPerformed

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased

        try {
            name.setText(commonMethods.firstLeterToCap(name.getText()));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_nameKeyReleased

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        try {
            char c = evt.getKeyChar();
            if (!(Character.isLetter(c) || (c == evt.VK_BACK_SPACE) ||
                (c == evt.VK_SPACE) || (c == evt.VK_PERIOD) || c == evt.VK_DELETE)) {
            //            JOptionPane.showMessageDialog(null, "enter Alphabets only");
            evt.consume();
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_nameKeyTyped

    private void cnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyReleased

        int cidIn = this.items.indexOf(this.cname.getText().trim());

        //                    System.out.println(" sgfg : "+cidIn);
        if(cidIn >= 0){

            customerId = customerModelList.get(cidIn).getCsID();
        }
    }//GEN-LAST:event_cnameKeyReleased

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try {
            int cidIn = this.items.indexOf(this.cname.getText().trim());

            //                    System.out.println(" sgfg : "+cidIn);
            if(cidIn >= 0){

                customerId = customerModelList.get(cidIn).getCsID();
            }
            if(customerId==0){
                List<RegistrationModel> dm = cdal.getSupplierModelList();

                Fruit.TableModel.CustomerEditTableModel ddpbtm = new CustomerEditTableModel(dm);
               
                discountTable.setModel(ddpbtm);
               
                discountTable.getColumnModel().getColumn(0).setMaxWidth(25);
                discountTable.getColumnModel().getColumn(8).setMaxWidth(60);
                discountTable.getColumnModel().getColumn(7).setMaxWidth(50);
            } else {

                List<RegistrationModel> dm = cdal.getSupplierModelListById(customerId);

                Fruit.TableModel.CustomerEditTableModel ddpbtm = new CustomerEditTableModel(dm);
                discountTable.setModel(ddpbtm);
//                discountTable.remove(8);
                discountTable.getColumnModel().getColumn(0).setMaxWidth(25);
                discountTable.getColumnModel().getColumn(8).setMaxWidth(60);
                discountTable.getColumnModel().getColumn(7).setMaxWidth(50);
                customerId=0;

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void mobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileKeyTyped
 char c = evt.getKeyChar();
//        System.out.println("len : "+(mob.getText().trim().length()>=10));
        if (!(Character.isDigit(c) || (c == evt.VK_BACK_SPACE) || c == evt.VK_DELETE )) {
//            JOptionPane.showMessageDialog(null, "enter Alphabets only");
            evt.consume();
        }
        if(mobile.getText().trim().length()>=10)
            evt.consume();
    }//GEN-LAST:event_mobileKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierEdit().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cNo;
    private javax.swing.JTextField city;
    private javax.swing.JTextField cname;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTable discountTable;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pinNo;
    private javax.swing.JTextField plotNo;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField state;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
