backup=D:BackUp//
bd_user=root
db_pswd=root
db_name=business_db
isMsgEnabled=true
pdf_path=pdf/
lastTranxLimit=5
companyName=WFC
msgID=nuYnWqDyuJ7DrLV5h3yN3LKjVIuwXn29
#zg1LuRgu9mJxccoLiRri1BNCT54xYVIq